FROM ubuntu:latest
MAINTAINER jjn<1556174776@qq.com>

WORKDIR /home
ADD ./../auto/p3Chain p3Chain
ADD ./../auto/daemon daemon
ADD ./../auto/daemonClose daemonClose

CMD echo "success--------------ok"
