/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * _3GPPPSDataOffStatus_anyOf.h
 *
 *
 */

#ifndef _3GPPPSDataOffStatus_anyOf_H_
#define _3GPPPSDataOffStatus_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class _3GPPPSDataOffStatus_anyOf {
 public:
  _3GPPPSDataOffStatus_anyOf();
  virtual ~_3GPPPSDataOffStatus_anyOf() = default;

  enum class e_3GPPPSDataOffStatus_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    ACTIVE,
    INACTIVE
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const _3GPPPSDataOffStatus_anyOf& rhs) const;
  bool operator!=(const _3GPPPSDataOffStatus_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// _3GPPPSDataOffStatus_anyOf members

  _3GPPPSDataOffStatus_anyOf::e_3GPPPSDataOffStatus_anyOf getValue() const;
  void setValue(_3GPPPSDataOffStatus_anyOf::e_3GPPPSDataOffStatus_anyOf value);

  friend void to_json(nlohmann::json& j, const _3GPPPSDataOffStatus_anyOf& o);
  friend void from_json(const nlohmann::json& j, _3GPPPSDataOffStatus_anyOf& o);

 protected:
  _3GPPPSDataOffStatus_anyOf::e_3GPPPSDataOffStatus_anyOf m_value =
      _3GPPPSDataOffStatus_anyOf::e_3GPPPSDataOffStatus_anyOf::
          INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::_3gpp::model

#endif /* _3GPPPSDataOffStatus_anyOf_H_ */
