/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces.   © 2024, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AcsInfo.h
 *
 * The ACS information for the 5G-RG is defined in BBF TR-069 [42] or in BBF
 * TR-369
 */

#ifndef AcsInfo_H_
#define AcsInfo_H_

#include <string>
#include "Ipv6Addr.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// The ACS information for the 5G-RG is defined in BBF TR-069 [42] or in BBF
/// TR-369
/// </summary>
class AcsInfo {
 public:
  AcsInfo();
  virtual ~AcsInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const AcsInfo& rhs) const;
  bool operator!=(const AcsInfo& rhs) const;

  /////////////////////////////////////////////
  /// AcsInfo members

  /// <summary>
  /// String providing an URI formatted according to RFC 3986.
  /// </summary>
  std::string getAcsUrl() const;
  void setAcsUrl(std::string const& value);
  bool acsUrlIsSet() const;
  void unsetAcsUrl();
  /// <summary>
  /// String identifying a IPv4 address formatted in the &#39;dotted
  /// decimal&#39; notation as defined in RFC 1166.
  /// </summary>
  std::string getAcsIpv4Addr() const;
  void setAcsIpv4Addr(std::string const& value);
  bool acsIpv4AddrIsSet() const;
  void unsetAcsIpv4Addr();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::Ipv6Addr getAcsIpv6Addr() const;
  void setAcsIpv6Addr(oai::_3gpp::model::Ipv6Addr const& value);
  bool acsIpv6AddrIsSet() const;
  void unsetAcsIpv6Addr();

  friend void to_json(nlohmann::json& j, const AcsInfo& o);
  friend void from_json(const nlohmann::json& j, AcsInfo& o);

 protected:
  std::string m_AcsUrl;
  bool m_AcsUrlIsSet;
  std::string m_AcsIpv4Addr;
  bool m_AcsIpv4AddrIsSet;
  oai::_3gpp::model::Ipv6Addr m_AcsIpv6Addr;
  bool m_AcsIpv6AddrIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* AcsInfo_H_ */
