/**
 * Nudm_UEAU
 * UDM UE Authentication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AuthenticationVector.h
 *
 *
 */

#ifndef AuthenticationVector_H_
#define AuthenticationVector_H_

#include <string>
#include "AvEapAkaPrime.h"
#include "AvType.h"
#include "Av5GHeAka.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class AuthenticationVector {
 public:
  AuthenticationVector();
  virtual ~AuthenticationVector() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const AuthenticationVector& rhs) const;
  bool operator!=(const AuthenticationVector& rhs) const;

  /////////////////////////////////////////////
  /// AuthenticationVector members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::AvType getAvType() const;
  void setAvType(oai::_3gpp::model::AvType const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getRand() const;
  void setRand(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getXres() const;
  void setXres(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getAutn() const;
  void setAutn(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getCkPrime() const;
  void setCkPrime(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getIkPrime() const;
  void setIkPrime(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getXresStar() const;
  void setXresStar(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getKausf() const;
  void setKausf(std::string const& value);

  friend void to_json(nlohmann::json& j, const AuthenticationVector& o);
  friend void from_json(const nlohmann::json& j, AuthenticationVector& o);

 protected:
  oai::_3gpp::model::AvType m_AvType;

  std::string m_Rand;

  std::string m_Xres;

  std::string m_Autn;

  std::string m_CkPrime;

  std::string m_IkPrime;

  std::string m_XresStar;

  std::string m_Kausf;
};

}  // namespace oai::_3gpp::model

#endif /* AuthenticationVector_H_ */
