/**
 * Nudm_SSAU
 * Nudm Service Specific Authorization Service.   © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AuthUpdateInfo.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

AuthUpdateInfo::AuthUpdateInfo() {
  m_InvalidityInd      = false;
  m_InvalidityIndIsSet = false;
  m_InvalidCauseIsSet  = false;
}

void AuthUpdateInfo::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool AuthUpdateInfo::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool AuthUpdateInfo::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "AuthUpdateInfo" : pathPrefix;

  return success;
}

bool AuthUpdateInfo::operator==(const AuthUpdateInfo& rhs) const {
  return

      (getAuthorizationData() == rhs.getAuthorizationData()) &&

      ((!invalidityIndIsSet() && !rhs.invalidityIndIsSet()) ||
       (invalidityIndIsSet() && rhs.invalidityIndIsSet() &&
        isInvalidityInd() == rhs.isInvalidityInd())) &&

      ((!invalidCauseIsSet() && !rhs.invalidCauseIsSet()) ||
       (invalidCauseIsSet() && rhs.invalidCauseIsSet() &&
        getInvalidCause() == rhs.getInvalidCause()))

          ;
}

bool AuthUpdateInfo::operator!=(const AuthUpdateInfo& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AuthUpdateInfo& o) {
  j                      = nlohmann::json();
  j["authorizationData"] = o.m_AuthorizationData;
  if (o.invalidityIndIsSet()) j["invalidityInd"] = o.m_InvalidityInd;
  if (o.invalidCauseIsSet()) j["invalidCause"] = o.m_InvalidCause;
}

void from_json(const nlohmann::json& j, AuthUpdateInfo& o) {
  j.at("authorizationData").get_to(o.m_AuthorizationData);
  if (j.find("invalidityInd") != j.end()) {
    j.at("invalidityInd").get_to(o.m_InvalidityInd);
    o.m_InvalidityIndIsSet = true;
  }
  if (j.find("invalidCause") != j.end()) {
    j.at("invalidCause").get_to(o.m_InvalidCause);
    o.m_InvalidCauseIsSet = true;
  }
}

oai::_3gpp::model::ServiceSpecificAuthorizationData
AuthUpdateInfo::getAuthorizationData() const {
  return m_AuthorizationData;
}
void AuthUpdateInfo::setAuthorizationData(
    oai::_3gpp::model::ServiceSpecificAuthorizationData const& value) {
  m_AuthorizationData = value;
}
bool AuthUpdateInfo::isInvalidityInd() const {
  return m_InvalidityInd;
}
void AuthUpdateInfo::setInvalidityInd(bool const value) {
  m_InvalidityInd      = value;
  m_InvalidityIndIsSet = true;
}
bool AuthUpdateInfo::invalidityIndIsSet() const {
  return m_InvalidityIndIsSet;
}
void AuthUpdateInfo::unsetInvalidityInd() {
  m_InvalidityIndIsSet = false;
}
oai::_3gpp::model::InvalidCause AuthUpdateInfo::getInvalidCause() const {
  return m_InvalidCause;
}
void AuthUpdateInfo::setInvalidCause(
    oai::_3gpp::model::InvalidCause const& value) {
  m_InvalidCause      = value;
  m_InvalidCauseIsSet = true;
}
bool AuthUpdateInfo::invalidCauseIsSet() const {
  return m_InvalidCauseIsSet;
}
void AuthUpdateInfo::unsetInvalidCause() {
  m_InvalidCauseIsSet = false;
}

}  // namespace oai::_3gpp::model
