/**
 * Nudm_SSAU
 * Nudm Service Specific Authorization Service.   © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AuthorizationUeId.h
 *
 * UE Id of the Authorization Data.
 */

#ifndef AuthorizationUeId_H_
#define AuthorizationUeId_H_

#include <string>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// UE Id of the Authorization Data.
/// </summary>
class AuthorizationUeId {
 public:
  AuthorizationUeId();
  virtual ~AuthorizationUeId() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const AuthorizationUeId& rhs) const;
  bool operator!=(const AuthorizationUeId& rhs) const;

  /////////////////////////////////////////////
  /// AuthorizationUeId members

  /// <summary>
  /// String identifying a Supi that shall contain either an IMSI, a network
  /// specific identifier, a Global Cable Identifier (GCI) or a Global Line
  /// Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall
  /// be formatted as follows  - for an IMSI \&quot;imsi-&lt;imsi&gt;\&quot;,
  /// where &lt;imsi&gt; shall be formatted according to clause 2.2    of 3GPP
  /// TS 23.003 that describes an IMSI.  - for a network specific identifier
  /// \&quot;nai-&lt;nai&gt;, where &lt;nai&gt; shall be formatted    according
  /// to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI
  /// \&quot;gci-&lt;gci&gt;\&quot;, where &lt;gci&gt; shall be formatted
  /// according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI
  /// \&quot;gli-&lt;gli&gt;\&quot;, where &lt;gli&gt; shall be formatted
  /// according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value
  /// is used as part of an URI, the string shall    only contain characters
  /// allowed according to the \&quot;lower-with-hyphen\&quot; naming convention
  /// defined in 3GPP TS 29.501.
  /// </summary>
  std::string getSupi() const;
  void setSupi(std::string const& value);
  /// <summary>
  /// String identifying a Gpsi shall contain either an External Id or an
  /// MSISDN.  It shall be formatted as follows -External Identifier&#x3D;
  /// \&quot;extid-&#39;extid&#39;, where &#39;extid&#39;  shall be formatted
  /// according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External
  /// Identifier.
  /// </summary>
  std::string getGpsi() const;
  void setGpsi(std::string const& value);
  bool gpsiIsSet() const;
  void unsetGpsi();

  friend void to_json(nlohmann::json& j, const AuthorizationUeId& o);
  friend void from_json(const nlohmann::json& j, AuthorizationUeId& o);

 protected:
  std::string m_Supi;

  std::string m_Gpsi;
  bool m_GpsiIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* AuthorizationUeId_H_ */
