/**
 * LMF Broadcast
 * LMF Broadcast Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "CipheringDataSet.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

CipheringDataSet::CipheringDataSet() {
  m_CipheringSetID      = 0;
  m_LtePosSibTypesIsSet = false;
  m_NrPosSibTypesIsSet  = false;
  m_ValidityStartTime   = "";
  m_ValidityDuration    = 0;
  m_TaiListIsSet        = false;
}

void CipheringDataSet::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool CipheringDataSet::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool CipheringDataSet::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "CipheringDataSet" : pathPrefix;

  /* CipheringSetID */ {
    const int32_t& value               = m_CipheringSetID;
    const std::string currentValuePath = _pathPrefix + ".cipheringSetID";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
    if (value > 65535) {
      success = false;
      msg << currentValuePath << ": must be less than or equal to 65535;";
    }
  }

  /* ValidityDuration */ {
    const int32_t& value               = m_ValidityDuration;
    const std::string currentValuePath = _pathPrefix + ".validityDuration";

    if (value < 1) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 1;";
    }
    if (value > 65535) {
      success = false;
      msg << currentValuePath << ": must be less than or equal to 65535;";
    }
  }

  return success;
}

bool CipheringDataSet::operator==(const CipheringDataSet& rhs) const {
  return

      (getCipheringSetID() == rhs.getCipheringSetID()) &&

      (getCipheringKey() == rhs.getCipheringKey()) &&

      (getC0() == rhs.getC0()) &&

      ((!ltePosSibTypesIsSet() && !rhs.ltePosSibTypesIsSet()) ||
       (ltePosSibTypesIsSet() && rhs.ltePosSibTypesIsSet() &&
        getLtePosSibTypes() == rhs.getLtePosSibTypes())) &&

      ((!nrPosSibTypesIsSet() && !rhs.nrPosSibTypesIsSet()) ||
       (nrPosSibTypesIsSet() && rhs.nrPosSibTypesIsSet() &&
        getNrPosSibTypes() == rhs.getNrPosSibTypes())) &&

      (getValidityStartTime() == rhs.getValidityStartTime()) &&

      (getValidityDuration() == rhs.getValidityDuration()) &&

      ((!taiListIsSet() && !rhs.taiListIsSet()) ||
       (taiListIsSet() && rhs.taiListIsSet() &&
        getTaiList() == rhs.getTaiList()))

          ;
}

bool CipheringDataSet::operator!=(const CipheringDataSet& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const CipheringDataSet& o) {
  j                   = nlohmann::json();
  j["cipheringSetID"] = o.m_CipheringSetID;
  j["cipheringKey"]   = o.m_CipheringKey;
  j["c0"]             = o.m_C0;
  if (o.ltePosSibTypesIsSet()) j["ltePosSibTypes"] = o.m_LtePosSibTypes;
  if (o.nrPosSibTypesIsSet()) j["nrPosSibTypes"] = o.m_NrPosSibTypes;
  j["validityStartTime"] = o.m_ValidityStartTime;
  j["validityDuration"]  = o.m_ValidityDuration;
  if (o.taiListIsSet()) j["taiList"] = o.m_TaiList;
}

void from_json(const nlohmann::json& j, CipheringDataSet& o) {
  j.at("cipheringSetID").get_to(o.m_CipheringSetID);
  j.at("cipheringKey").get_to(o.m_CipheringKey);
  j.at("c0").get_to(o.m_C0);
  if (j.find("ltePosSibTypes") != j.end()) {
    j.at("ltePosSibTypes").get_to(o.m_LtePosSibTypes);
    o.m_LtePosSibTypesIsSet = true;
  }
  if (j.find("nrPosSibTypes") != j.end()) {
    j.at("nrPosSibTypes").get_to(o.m_NrPosSibTypes);
    o.m_NrPosSibTypesIsSet = true;
  }
  j.at("validityStartTime").get_to(o.m_ValidityStartTime);
  j.at("validityDuration").get_to(o.m_ValidityDuration);
  if (j.find("taiList") != j.end()) {
    j.at("taiList").get_to(o.m_TaiList);
    o.m_TaiListIsSet = true;
  }
}

int32_t CipheringDataSet::getCipheringSetID() const {
  return m_CipheringSetID;
}
void CipheringDataSet::setCipheringSetID(int32_t const value) {
  m_CipheringSetID = value;
}
std::string CipheringDataSet::getCipheringKey() const {
  return m_CipheringKey;
}
void CipheringDataSet::setCipheringKey(std::string const& value) {
  m_CipheringKey = value;
}
std::string CipheringDataSet::getC0() const {
  return m_C0;
}
void CipheringDataSet::setC0(std::string const& value) {
  m_C0 = value;
}
std::string CipheringDataSet::getLtePosSibTypes() const {
  return m_LtePosSibTypes;
}
void CipheringDataSet::setLtePosSibTypes(std::string const& value) {
  m_LtePosSibTypes      = value;
  m_LtePosSibTypesIsSet = true;
}
bool CipheringDataSet::ltePosSibTypesIsSet() const {
  return m_LtePosSibTypesIsSet;
}
void CipheringDataSet::unsetLtePosSibTypes() {
  m_LtePosSibTypesIsSet = false;
}
std::string CipheringDataSet::getNrPosSibTypes() const {
  return m_NrPosSibTypes;
}
void CipheringDataSet::setNrPosSibTypes(std::string const& value) {
  m_NrPosSibTypes      = value;
  m_NrPosSibTypesIsSet = true;
}
bool CipheringDataSet::nrPosSibTypesIsSet() const {
  return m_NrPosSibTypesIsSet;
}
void CipheringDataSet::unsetNrPosSibTypes() {
  m_NrPosSibTypesIsSet = false;
}
std::string CipheringDataSet::getValidityStartTime() const {
  return m_ValidityStartTime;
}
void CipheringDataSet::setValidityStartTime(std::string const& value) {
  m_ValidityStartTime = value;
}
int32_t CipheringDataSet::getValidityDuration() const {
  return m_ValidityDuration;
}
void CipheringDataSet::setValidityDuration(int32_t const value) {
  m_ValidityDuration = value;
}
std::string CipheringDataSet::getTaiList() const {
  return m_TaiList;
}
void CipheringDataSet::setTaiList(std::string const& value) {
  m_TaiList      = value;
  m_TaiListIsSet = true;
}
bool CipheringDataSet::taiListIsSet() const {
  return m_TaiListIsSet;
}
void CipheringDataSet::unsetTaiList() {
  m_TaiListIsSet = false;
}

}  // namespace oai::_3gpp::model
