/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DataRestorationNotification.h
 *
 * Contains identities representing those UEs potentially affected by a
 * data-loss event at the UDR
 */

#ifndef DataRestorationNotification_H_
#define DataRestorationNotification_H_

#include "IdentityRange.h"
#include "SupiRange.h"
#include <string>
#include "Snssai.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Contains identities representing those UEs potentially affected by a
/// data-loss event at the UDR
/// </summary>
class DataRestorationNotification {
 public:
  DataRestorationNotification();
  virtual ~DataRestorationNotification() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const DataRestorationNotification& rhs) const;
  bool operator!=(const DataRestorationNotification& rhs) const;

  /////////////////////////////////////////////
  /// DataRestorationNotification members

  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::SupiRange> getSupiRanges() const;
  void setSupiRanges(std::vector<oai::_3gpp::model::SupiRange> const& value);
  bool supiRangesIsSet() const;
  void unsetSupiRanges();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::IdentityRange> getGpsiRanges() const;
  void setGpsiRanges(
      std::vector<oai::_3gpp::model::IdentityRange> const& value);
  bool gpsiRangesIsSet() const;
  void unsetGpsiRanges();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getResetIds() const;
  void setResetIds(std::vector<std::string> const& value);
  bool resetIdsIsSet() const;
  void unsetResetIds();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::Snssai> getSNssaiList() const;
  void setSNssaiList(std::vector<oai::_3gpp::model::Snssai> const& value);
  bool sNssaiListIsSet() const;
  void unsetSNssaiList();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getDnnList() const;
  void setDnnList(std::vector<std::string> const& value);
  bool dnnListIsSet() const;
  void unsetDnnList();
  /// <summary>
  /// Identifier of a group of NFs.
  /// </summary>
  std::string getUdrGroupId() const;
  void setUdrGroupId(std::string const& value);
  bool udrGroupIdIsSet() const;
  void unsetUdrGroupId();

  friend void to_json(nlohmann::json& j, const DataRestorationNotification& o);
  friend void from_json(
      const nlohmann::json& j, DataRestorationNotification& o);

 protected:
  std::vector<oai::_3gpp::model::SupiRange> m_SupiRanges;
  bool m_SupiRangesIsSet;
  std::vector<oai::_3gpp::model::IdentityRange> m_GpsiRanges;
  bool m_GpsiRangesIsSet;
  std::vector<std::string> m_ResetIds;
  bool m_ResetIdsIsSet;
  std::vector<oai::_3gpp::model::Snssai> m_SNssaiList;
  bool m_SNssaiListIsSet;
  std::vector<std::string> m_DnnList;
  bool m_DnnListIsSet;
  std::string m_UdrGroupId;
  bool m_UdrGroupIdIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* DataRestorationNotification_H_ */
