/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DnnRouteSelectionDescriptor.h
 *
 * Contains the route selector parameters (PDU session types, SSC modes and
 * ATSSS information) per DNN
 */

#ifndef DnnRouteSelectionDescriptor_H_
#define DnnRouteSelectionDescriptor_H_

#include <string>
#include "PduSessionType.h"
#include <vector>
#include "SscMode.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Contains the route selector parameters (PDU session types, SSC modes and
/// ATSSS information) per DNN
/// </summary>
class DnnRouteSelectionDescriptor {
 public:
  DnnRouteSelectionDescriptor();
  virtual ~DnnRouteSelectionDescriptor() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const DnnRouteSelectionDescriptor& rhs) const;
  bool operator!=(const DnnRouteSelectionDescriptor& rhs) const;

  /////////////////////////////////////////////
  /// DnnRouteSelectionDescriptor members

  /// <summary>
  /// String representing a Data Network as defined in clause 9A of 3GPP
  /// TS 23.003;  it shall contain either a DNN Network Identifier, or a full
  /// DNN with both the Network  Identifier and Operator Identifier, as
  /// specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as
  /// string in which the labels are separated by dots  (e.g.
  /// \&quot;Label1.Label2.Label3\&quot;).
  /// </summary>
  std::string getDnn() const;
  void setDnn(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::SscMode> getSscModes() const;
  void setSscModes(std::vector<oai::_3gpp::model::SscMode> const& value);
  bool sscModesIsSet() const;
  void unsetSscModes();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::PduSessionType> getPduSessTypes() const;
  void setPduSessTypes(
      std::vector<oai::_3gpp::model::PduSessionType> const& value);
  bool pduSessTypesIsSet() const;
  void unsetPduSessTypes();
  /// <summary>
  /// Indicates whether MA PDU session establishment is allowed for this DNN.
  /// When set to value true MA PDU session establishment is allowed for this
  /// DNN.
  /// </summary>
  bool isAtsssInfo() const;
  void setAtsssInfo(bool const value);
  bool atsssInfoIsSet() const;
  void unsetAtsssInfo();

  friend void to_json(nlohmann::json& j, const DnnRouteSelectionDescriptor& o);
  friend void from_json(
      const nlohmann::json& j, DnnRouteSelectionDescriptor& o);

 protected:
  std::string m_Dnn;

  std::vector<oai::_3gpp::model::SscMode> m_SscModes;
  bool m_SscModesIsSet;
  std::vector<oai::_3gpp::model::PduSessionType> m_PduSessTypes;
  bool m_PduSessTypesIsSet;
  bool m_AtsssInfo;
  bool m_AtsssInfoIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* DnnRouteSelectionDescriptor_H_ */
