/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * EbiArpMapping.h
 *
 * EBI to ARP mapping
 */

#ifndef EbiArpMapping_H_
#define EbiArpMapping_H_

#include "Arp.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// EBI to ARP mapping
/// </summary>
class EbiArpMapping {
 public:
  EbiArpMapping();
  virtual ~EbiArpMapping() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const EbiArpMapping& rhs) const;
  bool operator!=(const EbiArpMapping& rhs) const;

  /////////////////////////////////////////////
  /// EbiArpMapping members

  /// <summary>
  /// EPS Bearer Identifier
  /// </summary>
  int32_t getEpsBearerId() const;
  void setEpsBearerId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::Arp getArp() const;
  void setArp(oai::_3gpp::model::Arp const& value);

  friend void to_json(nlohmann::json& j, const EbiArpMapping& o);
  friend void from_json(const nlohmann::json& j, EbiArpMapping& o);

 protected:
  int32_t m_EpsBearerId;

  oai::_3gpp::model::Arp m_Arp;
};

}  // namespace oai::_3gpp::model

#endif /* EbiArpMapping_H_ */
