/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EcsAddrConfigInfo.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

EcsAddrConfigInfo::EcsAddrConfigInfo() {
  m_EcsServerAddrIsSet       = false;
  m_SpatialValidityCondIsSet = false;
}

void EcsAddrConfigInfo::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool EcsAddrConfigInfo::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool EcsAddrConfigInfo::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "EcsAddrConfigInfo" : pathPrefix;

  return success;
}

bool EcsAddrConfigInfo::operator==(const EcsAddrConfigInfo& rhs) const {
  return

      ((!ecsServerAddrIsSet() && !rhs.ecsServerAddrIsSet()) ||
       (ecsServerAddrIsSet() && rhs.ecsServerAddrIsSet() &&
        getEcsServerAddr() == rhs.getEcsServerAddr())) &&

      ((!spatialValidityCondIsSet() && !rhs.spatialValidityCondIsSet()) ||
       (spatialValidityCondIsSet() && rhs.spatialValidityCondIsSet() &&
        getSpatialValidityCond() == rhs.getSpatialValidityCond()))

          ;
}

bool EcsAddrConfigInfo::operator!=(const EcsAddrConfigInfo& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const EcsAddrConfigInfo& o) {
  j = nlohmann::json();
  if (o.ecsServerAddrIsSet()) j["ecsServerAddr"] = o.m_EcsServerAddr;
  if (o.spatialValidityCondIsSet())
    j["spatialValidityCond"] = o.m_SpatialValidityCond;
}

void from_json(const nlohmann::json& j, EcsAddrConfigInfo& o) {
  if (j.find("ecsServerAddr") != j.end()) {
    j.at("ecsServerAddr").get_to(o.m_EcsServerAddr);
    o.m_EcsServerAddrIsSet = true;
  }
  if (j.find("spatialValidityCond") != j.end()) {
    j.at("spatialValidityCond").get_to(o.m_SpatialValidityCond);
    o.m_SpatialValidityCondIsSet = true;
  }
}

oai::_3gpp::model::EcsServerAddr EcsAddrConfigInfo::getEcsServerAddr() const {
  return m_EcsServerAddr;
}
void EcsAddrConfigInfo::setEcsServerAddr(
    oai::_3gpp::model::EcsServerAddr const& value) {
  m_EcsServerAddr      = value;
  m_EcsServerAddrIsSet = true;
}
bool EcsAddrConfigInfo::ecsServerAddrIsSet() const {
  return m_EcsServerAddrIsSet;
}
void EcsAddrConfigInfo::unsetEcsServerAddr() {
  m_EcsServerAddrIsSet = false;
}
oai::_3gpp::model::SpatialValidityCond
EcsAddrConfigInfo::getSpatialValidityCond() const {
  return m_SpatialValidityCond;
}
void EcsAddrConfigInfo::setSpatialValidityCond(
    oai::_3gpp::model::SpatialValidityCond const& value) {
  m_SpatialValidityCond      = value;
  m_SpatialValidityCondIsSet = true;
}
bool EcsAddrConfigInfo::spatialValidityCondIsSet() const {
  return m_SpatialValidityCondIsSet;
}
void EcsAddrConfigInfo::unsetSpatialValidityCond() {
  m_SpatialValidityCondIsSet = false;
}

}  // namespace oai::_3gpp::model
