/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EmergencyInfo.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

EmergencyInfo::EmergencyInfo() {
  m_PgwFqdn            = "";
  m_PgwFqdnIsSet       = false;
  m_PgwIpAddressIsSet  = false;
  m_SmfInstanceId      = "";
  m_SmfInstanceIdIsSet = false;
  m_EpdgInd            = false;
  m_EpdgIndIsSet       = false;
  m_PlmnIdIsSet        = false;
}

void EmergencyInfo::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool EmergencyInfo::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool EmergencyInfo::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "EmergencyInfo" : pathPrefix;

  if (pgwFqdnIsSet()) {
    const std::string& value           = m_PgwFqdn;
    const std::string currentValuePath = _pathPrefix + ".pgwFqdn";

    if (value.length() < 4) {
      success = false;
      msg << currentValuePath << ": must be at least 4 characters long;";
    }
    if (value.length() > 253) {
      success = false;
      msg << currentValuePath << ": must be at most 253 characters long;";
    }
  }

  return success;
}

bool EmergencyInfo::operator==(const EmergencyInfo& rhs) const {
  return

      ((!pgwFqdnIsSet() && !rhs.pgwFqdnIsSet()) ||
       (pgwFqdnIsSet() && rhs.pgwFqdnIsSet() &&
        getPgwFqdn() == rhs.getPgwFqdn())) &&

      ((!pgwIpAddressIsSet() && !rhs.pgwIpAddressIsSet()) ||
       (pgwIpAddressIsSet() && rhs.pgwIpAddressIsSet() &&
        getPgwIpAddress() == rhs.getPgwIpAddress())) &&

      ((!smfInstanceIdIsSet() && !rhs.smfInstanceIdIsSet()) ||
       (smfInstanceIdIsSet() && rhs.smfInstanceIdIsSet() &&
        getSmfInstanceId() == rhs.getSmfInstanceId())) &&

      ((!epdgIndIsSet() && !rhs.epdgIndIsSet()) ||
       (epdgIndIsSet() && rhs.epdgIndIsSet() &&
        isEpdgInd() == rhs.isEpdgInd())) &&

      ((!plmnIdIsSet() && !rhs.plmnIdIsSet()) ||
       (plmnIdIsSet() && rhs.plmnIdIsSet() && getPlmnId() == rhs.getPlmnId()))

          ;
}

bool EmergencyInfo::operator!=(const EmergencyInfo& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const EmergencyInfo& o) {
  j = nlohmann::json();
  if (o.pgwFqdnIsSet()) j["pgwFqdn"] = o.m_PgwFqdn;
  if (o.pgwIpAddressIsSet()) j["pgwIpAddress"] = o.m_PgwIpAddress;
  if (o.smfInstanceIdIsSet()) j["smfInstanceId"] = o.m_SmfInstanceId;
  if (o.epdgIndIsSet()) j["epdgInd"] = o.m_EpdgInd;
  if (o.plmnIdIsSet()) j["plmnId"] = o.m_PlmnId;
}

void from_json(const nlohmann::json& j, EmergencyInfo& o) {
  if (j.find("pgwFqdn") != j.end()) {
    j.at("pgwFqdn").get_to(o.m_PgwFqdn);
    o.m_PgwFqdnIsSet = true;
  }
  if (j.find("pgwIpAddress") != j.end()) {
    j.at("pgwIpAddress").get_to(o.m_PgwIpAddress);
    o.m_PgwIpAddressIsSet = true;
  }
  if (j.find("smfInstanceId") != j.end()) {
    j.at("smfInstanceId").get_to(o.m_SmfInstanceId);
    o.m_SmfInstanceIdIsSet = true;
  }
  if (j.find("epdgInd") != j.end()) {
    j.at("epdgInd").get_to(o.m_EpdgInd);
    o.m_EpdgIndIsSet = true;
  }
  if (j.find("plmnId") != j.end()) {
    j.at("plmnId").get_to(o.m_PlmnId);
    o.m_PlmnIdIsSet = true;
  }
}

std::string EmergencyInfo::getPgwFqdn() const {
  return m_PgwFqdn;
}
void EmergencyInfo::setPgwFqdn(std::string const& value) {
  m_PgwFqdn      = value;
  m_PgwFqdnIsSet = true;
}
bool EmergencyInfo::pgwFqdnIsSet() const {
  return m_PgwFqdnIsSet;
}
void EmergencyInfo::unsetPgwFqdn() {
  m_PgwFqdnIsSet = false;
}
oai::_3gpp::model::IpAddress EmergencyInfo::getPgwIpAddress() const {
  return m_PgwIpAddress;
}
void EmergencyInfo::setPgwIpAddress(oai::_3gpp::model::IpAddress const& value) {
  m_PgwIpAddress      = value;
  m_PgwIpAddressIsSet = true;
}
bool EmergencyInfo::pgwIpAddressIsSet() const {
  return m_PgwIpAddressIsSet;
}
void EmergencyInfo::unsetPgwIpAddress() {
  m_PgwIpAddressIsSet = false;
}
std::string EmergencyInfo::getSmfInstanceId() const {
  return m_SmfInstanceId;
}
void EmergencyInfo::setSmfInstanceId(std::string const& value) {
  m_SmfInstanceId      = value;
  m_SmfInstanceIdIsSet = true;
}
bool EmergencyInfo::smfInstanceIdIsSet() const {
  return m_SmfInstanceIdIsSet;
}
void EmergencyInfo::unsetSmfInstanceId() {
  m_SmfInstanceIdIsSet = false;
}
bool EmergencyInfo::isEpdgInd() const {
  return m_EpdgInd;
}
void EmergencyInfo::setEpdgInd(bool const value) {
  m_EpdgInd      = value;
  m_EpdgIndIsSet = true;
}
bool EmergencyInfo::epdgIndIsSet() const {
  return m_EpdgIndIsSet;
}
void EmergencyInfo::unsetEpdgInd() {
  m_EpdgIndIsSet = false;
}
oai::_3gpp::model::PlmnId EmergencyInfo::getPlmnId() const {
  return m_PlmnId;
}
void EmergencyInfo::setPlmnId(oai::_3gpp::model::PlmnId const& value) {
  m_PlmnId      = value;
  m_PlmnIdIsSet = true;
}
bool EmergencyInfo::plmnIdIsSet() const {
  return m_PlmnIdIsSet;
}
void EmergencyInfo::unsetPlmnId() {
  m_PlmnIdIsSet = false;
}

}  // namespace oai::_3gpp::model
