/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EpsNasCipheringAlgorithm_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace oai::_3gpp::model {

EpsNasCipheringAlgorithm_anyOf::EpsNasCipheringAlgorithm_anyOf() {}

void EpsNasCipheringAlgorithm_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool EpsNasCipheringAlgorithm_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool EpsNasCipheringAlgorithm_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "EpsNasCipheringAlgorithm_anyOf" : pathPrefix;

  if (m_value ==
      EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::
          INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool EpsNasCipheringAlgorithm_anyOf::operator==(
    const EpsNasCipheringAlgorithm_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool EpsNasCipheringAlgorithm_anyOf::operator!=(
    const EpsNasCipheringAlgorithm_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const EpsNasCipheringAlgorithm_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::EEA0:
      j = "EEA0";
      break;
    case EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::EEA1:
      j = "EEA1";
      break;
    case EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::EEA2:
      j = "EEA2";
      break;
    case EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::EEA3:
      j = "EEA3";
      break;
  }
}

void from_json(const nlohmann::json& j, EpsNasCipheringAlgorithm_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "EEA0") {
    o.setValue(
        EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::EEA0);
  } else if (s == "EEA1") {
    o.setValue(
        EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::EEA1);
  } else if (s == "EEA2") {
    o.setValue(
        EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::EEA2);
  } else if (s == "EEA3") {
    o.setValue(
        EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf::EEA3);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf
EpsNasCipheringAlgorithm_anyOf::getValue() const {
  return m_value;
}
void EpsNasCipheringAlgorithm_anyOf::setValue(
    EpsNasCipheringAlgorithm_anyOf::eEpsNasCipheringAlgorithm_anyOf value) {
  m_value = value;
}

}  // namespace oai::_3gpp::model
