/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "FailureEventInfo.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

FailureEventInfo::FailureEventInfo() {}

void FailureEventInfo::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool FailureEventInfo::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool FailureEventInfo::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "FailureEventInfo" : pathPrefix;

  return success;
}

bool FailureEventInfo::operator==(const FailureEventInfo& rhs) const {
  return

      (getEvent() == rhs.getEvent()) &&

      (getFailureCode() == rhs.getFailureCode())

          ;
}

bool FailureEventInfo::operator!=(const FailureEventInfo& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const FailureEventInfo& o) {
  j                = nlohmann::json();
  j["event"]       = o.m_Event;
  j["failureCode"] = o.m_FailureCode;
}

void from_json(const nlohmann::json& j, FailureEventInfo& o) {
  j.at("event").get_to(o.m_Event);
  j.at("failureCode").get_to(o.m_FailureCode);
}

oai::_3gpp::model::NwdafEvent FailureEventInfo::getEvent() const {
  return m_Event;
}
void FailureEventInfo::setEvent(oai::_3gpp::model::NwdafEvent const& value) {
  m_Event = value;
}
oai::_3gpp::model::NwdafFailureCode FailureEventInfo::getFailureCode() const {
  return m_FailureCode;
}
void FailureEventInfo::setFailureCode(
    oai::_3gpp::model::NwdafFailureCode const& value) {
  m_FailureCode = value;
}

}  // namespace oai::_3gpp::model
