/**
 * Nudm_UEAU
 * UDM UE Authentication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * HssAvType.h
 *
 *
 */

#ifndef HssAvType_H_
#define HssAvType_H_

#include "HssAvType_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class HssAvType {
 public:
  HssAvType();
  virtual ~HssAvType() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const HssAvType& rhs) const;
  bool operator!=(const HssAvType& rhs) const;

  /////////////////////////////////////////////
  /// HssAvType members

  HssAvType_anyOf getValue() const;
  void setValue(HssAvType_anyOf value);
  HssAvType_anyOf::eHssAvType_anyOf getEnumValue() const;
  void setEnumValue(HssAvType_anyOf::eHssAvType_anyOf value);
  friend void to_json(nlohmann::json& j, const HssAvType& o);
  friend void from_json(const nlohmann::json& j, HssAvType& o);
  friend void to_json(nlohmann::json& j, const HssAvType_anyOf& o);
  friend void from_json(const nlohmann::json& j, HssAvType_anyOf& o);

 protected:
  HssAvType_anyOf m_value;
};

}  // namespace oai::_3gpp::model

#endif /* HssAvType_H_ */
