/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * HssSubscriptionInfo.h
 *
 * Information related to active subscriptions at the HSS(s)
 */

#ifndef HssSubscriptionInfo_H_
#define HssSubscriptionInfo_H_

#include "HssSubscriptionItem.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Information related to active subscriptions at the HSS(s)
/// </summary>
class HssSubscriptionInfo {
 public:
  HssSubscriptionInfo();
  virtual ~HssSubscriptionInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const HssSubscriptionInfo& rhs) const;
  bool operator!=(const HssSubscriptionInfo& rhs) const;

  /////////////////////////////////////////////
  /// HssSubscriptionInfo members

  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::HssSubscriptionItem> getHssSubscriptionList()
      const;
  void setHssSubscriptionList(
      std::vector<oai::_3gpp::model::HssSubscriptionItem> const& value);

  friend void to_json(nlohmann::json& j, const HssSubscriptionInfo& o);
  friend void from_json(const nlohmann::json& j, HssSubscriptionInfo& o);

 protected:
  std::vector<oai::_3gpp::model::HssSubscriptionItem> m_HssSubscriptionList;
};

}  // namespace oai::_3gpp::model

#endif /* HssSubscriptionInfo_H_ */
