/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * KeyAmfType_anyOf.h
 *
 *
 */

#ifndef KeyAmfType_anyOf_H_
#define KeyAmfType_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class KeyAmfType_anyOf {
 public:
  KeyAmfType_anyOf();
  virtual ~KeyAmfType_anyOf() = default;

  enum class eKeyAmfType_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    KAMF,
    KPRIMEAMF
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const KeyAmfType_anyOf& rhs) const;
  bool operator!=(const KeyAmfType_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// KeyAmfType_anyOf members

  KeyAmfType_anyOf::eKeyAmfType_anyOf getValue() const;
  void setValue(KeyAmfType_anyOf::eKeyAmfType_anyOf value);

  friend void to_json(nlohmann::json& j, const KeyAmfType_anyOf& o);
  friend void from_json(const nlohmann::json& j, KeyAmfType_anyOf& o);

 protected:
  KeyAmfType_anyOf::eKeyAmfType_anyOf m_value =
      KeyAmfType_anyOf::eKeyAmfType_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::_3gpp::model

#endif /* KeyAmfType_anyOf_H_ */
