/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "LcsPrivacyData.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

LcsPrivacyData::LcsPrivacyData() {
  m_LpiIsSet                 = false;
  m_UnrelatedClassIsSet      = false;
  m_PlmnOperatorClassesIsSet = false;
}

void LcsPrivacyData::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool LcsPrivacyData::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool LcsPrivacyData::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "LcsPrivacyData" : pathPrefix;

  if (plmnOperatorClassesIsSet()) {
    const std::vector<oai::_3gpp::model::PlmnOperatorClass>& value =
        m_PlmnOperatorClasses;
    const std::string currentValuePath = _pathPrefix + ".plmnOperatorClasses";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::PlmnOperatorClass& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".plmnOperatorClasses") &&
            success;

        i++;
      }
    }
  }

  return success;
}

bool LcsPrivacyData::operator==(const LcsPrivacyData& rhs) const {
  return

      ((!lpiIsSet() && !rhs.lpiIsSet()) ||
       (lpiIsSet() && rhs.lpiIsSet() && getLpi() == rhs.getLpi())) &&

      ((!unrelatedClassIsSet() && !rhs.unrelatedClassIsSet()) ||
       (unrelatedClassIsSet() && rhs.unrelatedClassIsSet() &&
        getUnrelatedClass() == rhs.getUnrelatedClass())) &&

      ((!plmnOperatorClassesIsSet() && !rhs.plmnOperatorClassesIsSet()) ||
       (plmnOperatorClassesIsSet() && rhs.plmnOperatorClassesIsSet() &&
        getPlmnOperatorClasses() == rhs.getPlmnOperatorClasses()))

          ;
}

bool LcsPrivacyData::operator!=(const LcsPrivacyData& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const LcsPrivacyData& o) {
  j = nlohmann::json();
  if (o.lpiIsSet()) j["lpi"] = o.m_Lpi;
  if (o.unrelatedClassIsSet()) j["unrelatedClass"] = o.m_UnrelatedClass;
  if (o.plmnOperatorClassesIsSet() || !o.m_PlmnOperatorClasses.empty())
    j["plmnOperatorClasses"] = o.m_PlmnOperatorClasses;
}

void from_json(const nlohmann::json& j, LcsPrivacyData& o) {
  if (j.find("lpi") != j.end()) {
    j.at("lpi").get_to(o.m_Lpi);
    o.m_LpiIsSet = true;
  }
  if (j.find("unrelatedClass") != j.end()) {
    j.at("unrelatedClass").get_to(o.m_UnrelatedClass);
    o.m_UnrelatedClassIsSet = true;
  }
  if (j.find("plmnOperatorClasses") != j.end()) {
    j.at("plmnOperatorClasses").get_to(o.m_PlmnOperatorClasses);
    o.m_PlmnOperatorClassesIsSet = true;
  }
}

oai::_3gpp::model::Lpi LcsPrivacyData::getLpi() const {
  return m_Lpi;
}
void LcsPrivacyData::setLpi(oai::_3gpp::model::Lpi const& value) {
  m_Lpi      = value;
  m_LpiIsSet = true;
}
bool LcsPrivacyData::lpiIsSet() const {
  return m_LpiIsSet;
}
void LcsPrivacyData::unsetLpi() {
  m_LpiIsSet = false;
}
oai::_3gpp::model::UnrelatedClass LcsPrivacyData::getUnrelatedClass() const {
  return m_UnrelatedClass;
}
void LcsPrivacyData::setUnrelatedClass(
    oai::_3gpp::model::UnrelatedClass const& value) {
  m_UnrelatedClass      = value;
  m_UnrelatedClassIsSet = true;
}
bool LcsPrivacyData::unrelatedClassIsSet() const {
  return m_UnrelatedClassIsSet;
}
void LcsPrivacyData::unsetUnrelatedClass() {
  m_UnrelatedClassIsSet = false;
}
std::vector<oai::_3gpp::model::PlmnOperatorClass>
LcsPrivacyData::getPlmnOperatorClasses() const {
  return m_PlmnOperatorClasses;
}
void LcsPrivacyData::setPlmnOperatorClasses(
    std::vector<oai::_3gpp::model::PlmnOperatorClass> const& value) {
  m_PlmnOperatorClasses      = value;
  m_PlmnOperatorClassesIsSet = true;
}
bool LcsPrivacyData::plmnOperatorClassesIsSet() const {
  return m_PlmnOperatorClassesIsSet;
}
void LcsPrivacyData::unsetPlmnOperatorClasses() {
  m_PlmnOperatorClassesIsSet = false;
}

}  // namespace oai::_3gpp::model
