/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Local3dPointUncertaintyEllipsoid.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

Local3dPointUncertaintyEllipsoid::Local3dPointUncertaintyEllipsoid() {
  m_Confidence       = 0;
  m_VConfidence      = 0;
  m_VConfidenceIsSet = false;
}

void Local3dPointUncertaintyEllipsoid::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool Local3dPointUncertaintyEllipsoid::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool Local3dPointUncertaintyEllipsoid::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "Local3dPointUncertaintyEllipsoid" : pathPrefix;

  /* Confidence */ {
    const int32_t& value               = m_Confidence;
    const std::string currentValuePath = _pathPrefix + ".confidence";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
    if (value > 100) {
      success = false;
      msg << currentValuePath << ": must be less than or equal to 100;";
    }
  }

  if (vConfidenceIsSet()) {
    const int32_t& value               = m_VConfidence;
    const std::string currentValuePath = _pathPrefix + ".vConfidence";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
    if (value > 100) {
      success = false;
      msg << currentValuePath << ": must be less than or equal to 100;";
    }
  }

  return success;
}

bool Local3dPointUncertaintyEllipsoid::operator==(
    const Local3dPointUncertaintyEllipsoid& rhs) const {
  return

      (getShape() == rhs.getShape()) &&

      (getLocalOrigin() == rhs.getLocalOrigin()) &&

      (getPoint() == rhs.getPoint()) &&

      (getUncertaintyEllipsoid() == rhs.getUncertaintyEllipsoid()) &&

      (getConfidence() == rhs.getConfidence()) &&

      ((!vConfidenceIsSet() && !rhs.vConfidenceIsSet()) ||
       (vConfidenceIsSet() && rhs.vConfidenceIsSet() &&
        getVConfidence() == rhs.getVConfidence()))

          ;
}

bool Local3dPointUncertaintyEllipsoid::operator!=(
    const Local3dPointUncertaintyEllipsoid& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Local3dPointUncertaintyEllipsoid& o) {
  j                         = nlohmann::json();
  j["shape"]                = o.m_Shape;
  j["localOrigin"]          = o.m_LocalOrigin;
  j["point"]                = o.m_Point;
  j["uncertaintyEllipsoid"] = o.m_UncertaintyEllipsoid;
  j["confidence"]           = o.m_Confidence;
  if (o.vConfidenceIsSet()) j["vConfidence"] = o.m_VConfidence;
}

void from_json(const nlohmann::json& j, Local3dPointUncertaintyEllipsoid& o) {
  j.at("shape").get_to(o.m_Shape);
  j.at("localOrigin").get_to(o.m_LocalOrigin);
  j.at("point").get_to(o.m_Point);
  j.at("uncertaintyEllipsoid").get_to(o.m_UncertaintyEllipsoid);
  j.at("confidence").get_to(o.m_Confidence);
  if (j.find("vConfidence") != j.end()) {
    j.at("vConfidence").get_to(o.m_VConfidence);
    o.m_VConfidenceIsSet = true;
  }
}

oai::_3gpp::model::SupportedGADShapes
Local3dPointUncertaintyEllipsoid::getShape() const {
  return m_Shape;
}
void Local3dPointUncertaintyEllipsoid::setShape(
    oai::_3gpp::model::SupportedGADShapes const& value) {
  m_Shape = value;
}
oai::_3gpp::model::LocalOrigin
Local3dPointUncertaintyEllipsoid::getLocalOrigin() const {
  return m_LocalOrigin;
}
void Local3dPointUncertaintyEllipsoid::setLocalOrigin(
    oai::_3gpp::model::LocalOrigin const& value) {
  m_LocalOrigin = value;
}
oai::_3gpp::model::RelativeCartesianLocation
Local3dPointUncertaintyEllipsoid::getPoint() const {
  return m_Point;
}
void Local3dPointUncertaintyEllipsoid::setPoint(
    oai::_3gpp::model::RelativeCartesianLocation const& value) {
  m_Point = value;
}
oai::_3gpp::model::UncertaintyEllipsoid
Local3dPointUncertaintyEllipsoid::getUncertaintyEllipsoid() const {
  return m_UncertaintyEllipsoid;
}
void Local3dPointUncertaintyEllipsoid::setUncertaintyEllipsoid(
    oai::_3gpp::model::UncertaintyEllipsoid const& value) {
  m_UncertaintyEllipsoid = value;
}
int32_t Local3dPointUncertaintyEllipsoid::getConfidence() const {
  return m_Confidence;
}
void Local3dPointUncertaintyEllipsoid::setConfidence(int32_t const value) {
  m_Confidence = value;
}
int32_t Local3dPointUncertaintyEllipsoid::getVConfidence() const {
  return m_VConfidence;
}
void Local3dPointUncertaintyEllipsoid::setVConfidence(int32_t const value) {
  m_VConfidence      = value;
  m_VConfidenceIsSet = true;
}
bool Local3dPointUncertaintyEllipsoid::vConfidenceIsSet() const {
  return m_VConfidenceIsSet;
}
void Local3dPointUncertaintyEllipsoid::unsetVConfidence() {
  m_VConfidenceIsSet = false;
}

}  // namespace oai::_3gpp::model
