/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * LocalOrigin.h
 *
 * Indicates a Local origin in a reference system
 */

#ifndef LocalOrigin_H_
#define LocalOrigin_H_

#include "GeographicalCoordinates.h"
#include <string>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Indicates a Local origin in a reference system
/// </summary>
class LocalOrigin {
 public:
  LocalOrigin();
  virtual ~LocalOrigin() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const LocalOrigin& rhs) const;
  bool operator!=(const LocalOrigin& rhs) const;

  /////////////////////////////////////////////
  /// LocalOrigin members

  /// <summary>
  ///
  /// </summary>
  std::string getCoordinateId() const;
  void setCoordinateId(std::string const& value);
  bool coordinateIdIsSet() const;
  void unsetCoordinateId();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::GeographicalCoordinates getPoint() const;
  void setPoint(oai::_3gpp::model::GeographicalCoordinates const& value);
  bool pointIsSet() const;
  void unsetPoint();

  friend void to_json(nlohmann::json& j, const LocalOrigin& o);
  friend void from_json(const nlohmann::json& j, LocalOrigin& o);

 protected:
  std::string m_CoordinateId;
  bool m_CoordinateIdIsSet;
  oai::_3gpp::model::GeographicalCoordinates m_Point;
  bool m_PointIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* LocalOrigin_H_ */
