/**
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ModifyPduSession_400_response.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

ModifyPduSession_400_response::ModifyPduSession_400_response() {
  m_JsonDataIsSet                    = false;
  m_BinaryDataN1SmInfoFromUeIsSet    = false;
  m_BinaryDataUnknownN1SmInfoIsSet   = false;
  m_BinaryDataN4InformationIsSet     = false;
  m_BinaryDataN4InformationExt1IsSet = false;
  m_BinaryDataN4InformationExt2IsSet = false;
  m_BinaryDataN4InformationExt3IsSet = false;
}

void ModifyPduSession_400_response::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool ModifyPduSession_400_response::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ModifyPduSession_400_response::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ModifyPduSession_400_response" : pathPrefix;

  return success;
}

bool ModifyPduSession_400_response::operator==(
    const ModifyPduSession_400_response& rhs) const {
  return

      ((!jsonDataIsSet() && !rhs.jsonDataIsSet()) ||
       (jsonDataIsSet() && rhs.jsonDataIsSet() &&
        getJsonData() == rhs.getJsonData())) &&

      ((!binaryDataN1SmInfoFromUeIsSet() &&
        !rhs.binaryDataN1SmInfoFromUeIsSet()) ||
       (binaryDataN1SmInfoFromUeIsSet() &&
        rhs.binaryDataN1SmInfoFromUeIsSet() &&
        getBinaryDataN1SmInfoFromUe() == rhs.getBinaryDataN1SmInfoFromUe())) &&

      ((!binaryDataUnknownN1SmInfoIsSet() &&
        !rhs.binaryDataUnknownN1SmInfoIsSet()) ||
       (binaryDataUnknownN1SmInfoIsSet() &&
        rhs.binaryDataUnknownN1SmInfoIsSet() &&
        getBinaryDataUnknownN1SmInfo() ==
            rhs.getBinaryDataUnknownN1SmInfo())) &&

      ((!binaryDataN4InformationIsSet() &&
        !rhs.binaryDataN4InformationIsSet()) ||
       (binaryDataN4InformationIsSet() && rhs.binaryDataN4InformationIsSet() &&
        getBinaryDataN4Information() == rhs.getBinaryDataN4Information())) &&

      ((!binaryDataN4InformationExt1IsSet() &&
        !rhs.binaryDataN4InformationExt1IsSet()) ||
       (binaryDataN4InformationExt1IsSet() &&
        rhs.binaryDataN4InformationExt1IsSet() &&
        getBinaryDataN4InformationExt1() ==
            rhs.getBinaryDataN4InformationExt1())) &&

      ((!binaryDataN4InformationExt2IsSet() &&
        !rhs.binaryDataN4InformationExt2IsSet()) ||
       (binaryDataN4InformationExt2IsSet() &&
        rhs.binaryDataN4InformationExt2IsSet() &&
        getBinaryDataN4InformationExt2() ==
            rhs.getBinaryDataN4InformationExt2())) &&

      ((!binaryDataN4InformationExt3IsSet() &&
        !rhs.binaryDataN4InformationExt3IsSet()) ||
       (binaryDataN4InformationExt3IsSet() &&
        rhs.binaryDataN4InformationExt3IsSet() &&
        getBinaryDataN4InformationExt3() ==
            rhs.getBinaryDataN4InformationExt3()))

          ;
}

bool ModifyPduSession_400_response::operator!=(
    const ModifyPduSession_400_response& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ModifyPduSession_400_response& o) {
  j = nlohmann::json();
  if (o.jsonDataIsSet()) j["jsonData"] = o.m_JsonData;
  if (o.binaryDataN1SmInfoFromUeIsSet())
    j["binaryDataN1SmInfoFromUe"] = o.m_BinaryDataN1SmInfoFromUe;
  if (o.binaryDataUnknownN1SmInfoIsSet())
    j["binaryDataUnknownN1SmInfo"] = o.m_BinaryDataUnknownN1SmInfo;
  if (o.binaryDataN4InformationIsSet())
    j["binaryDataN4Information"] = o.m_BinaryDataN4Information;
  if (o.binaryDataN4InformationExt1IsSet())
    j["binaryDataN4InformationExt1"] = o.m_BinaryDataN4InformationExt1;
  if (o.binaryDataN4InformationExt2IsSet())
    j["binaryDataN4InformationExt2"] = o.m_BinaryDataN4InformationExt2;
  if (o.binaryDataN4InformationExt3IsSet())
    j["binaryDataN4InformationExt3"] = o.m_BinaryDataN4InformationExt3;
}

void from_json(const nlohmann::json& j, ModifyPduSession_400_response& o) {
  if (j.find("jsonData") != j.end()) {
    j.at("jsonData").get_to(o.m_JsonData);
    o.m_JsonDataIsSet = true;
  }
  if (j.find("binaryDataN1SmInfoFromUe") != j.end()) {
    j.at("binaryDataN1SmInfoFromUe").get_to(o.m_BinaryDataN1SmInfoFromUe);
    o.m_BinaryDataN1SmInfoFromUeIsSet = true;
  }
  if (j.find("binaryDataUnknownN1SmInfo") != j.end()) {
    j.at("binaryDataUnknownN1SmInfo").get_to(o.m_BinaryDataUnknownN1SmInfo);
    o.m_BinaryDataUnknownN1SmInfoIsSet = true;
  }
  if (j.find("binaryDataN4Information") != j.end()) {
    j.at("binaryDataN4Information").get_to(o.m_BinaryDataN4Information);
    o.m_BinaryDataN4InformationIsSet = true;
  }
  if (j.find("binaryDataN4InformationExt1") != j.end()) {
    j.at("binaryDataN4InformationExt1").get_to(o.m_BinaryDataN4InformationExt1);
    o.m_BinaryDataN4InformationExt1IsSet = true;
  }
  if (j.find("binaryDataN4InformationExt2") != j.end()) {
    j.at("binaryDataN4InformationExt2").get_to(o.m_BinaryDataN4InformationExt2);
    o.m_BinaryDataN4InformationExt2IsSet = true;
  }
  if (j.find("binaryDataN4InformationExt3") != j.end()) {
    j.at("binaryDataN4InformationExt3").get_to(o.m_BinaryDataN4InformationExt3);
    o.m_BinaryDataN4InformationExt3IsSet = true;
  }
}

oai::_3gpp::model::VsmfUpdateError ModifyPduSession_400_response::getJsonData()
    const {
  return m_JsonData;
}
void ModifyPduSession_400_response::setJsonData(
    oai::_3gpp::model::VsmfUpdateError const& value) {
  m_JsonData      = value;
  m_JsonDataIsSet = true;
}
bool ModifyPduSession_400_response::jsonDataIsSet() const {
  return m_JsonDataIsSet;
}
void ModifyPduSession_400_response::unsetJsonData() {
  m_JsonDataIsSet = false;
}
std::string ModifyPduSession_400_response::getBinaryDataN1SmInfoFromUe() const {
  return m_BinaryDataN1SmInfoFromUe;
}
void ModifyPduSession_400_response::setBinaryDataN1SmInfoFromUe(
    std::string const& value) {
  m_BinaryDataN1SmInfoFromUe      = value;
  m_BinaryDataN1SmInfoFromUeIsSet = true;
}
bool ModifyPduSession_400_response::binaryDataN1SmInfoFromUeIsSet() const {
  return m_BinaryDataN1SmInfoFromUeIsSet;
}
void ModifyPduSession_400_response::unsetBinaryDataN1SmInfoFromUe() {
  m_BinaryDataN1SmInfoFromUeIsSet = false;
}
std::string ModifyPduSession_400_response::getBinaryDataUnknownN1SmInfo()
    const {
  return m_BinaryDataUnknownN1SmInfo;
}
void ModifyPduSession_400_response::setBinaryDataUnknownN1SmInfo(
    std::string const& value) {
  m_BinaryDataUnknownN1SmInfo      = value;
  m_BinaryDataUnknownN1SmInfoIsSet = true;
}
bool ModifyPduSession_400_response::binaryDataUnknownN1SmInfoIsSet() const {
  return m_BinaryDataUnknownN1SmInfoIsSet;
}
void ModifyPduSession_400_response::unsetBinaryDataUnknownN1SmInfo() {
  m_BinaryDataUnknownN1SmInfoIsSet = false;
}
std::string ModifyPduSession_400_response::getBinaryDataN4Information() const {
  return m_BinaryDataN4Information;
}
void ModifyPduSession_400_response::setBinaryDataN4Information(
    std::string const& value) {
  m_BinaryDataN4Information      = value;
  m_BinaryDataN4InformationIsSet = true;
}
bool ModifyPduSession_400_response::binaryDataN4InformationIsSet() const {
  return m_BinaryDataN4InformationIsSet;
}
void ModifyPduSession_400_response::unsetBinaryDataN4Information() {
  m_BinaryDataN4InformationIsSet = false;
}
std::string ModifyPduSession_400_response::getBinaryDataN4InformationExt1()
    const {
  return m_BinaryDataN4InformationExt1;
}
void ModifyPduSession_400_response::setBinaryDataN4InformationExt1(
    std::string const& value) {
  m_BinaryDataN4InformationExt1      = value;
  m_BinaryDataN4InformationExt1IsSet = true;
}
bool ModifyPduSession_400_response::binaryDataN4InformationExt1IsSet() const {
  return m_BinaryDataN4InformationExt1IsSet;
}
void ModifyPduSession_400_response::unsetBinaryDataN4InformationExt1() {
  m_BinaryDataN4InformationExt1IsSet = false;
}
std::string ModifyPduSession_400_response::getBinaryDataN4InformationExt2()
    const {
  return m_BinaryDataN4InformationExt2;
}
void ModifyPduSession_400_response::setBinaryDataN4InformationExt2(
    std::string const& value) {
  m_BinaryDataN4InformationExt2      = value;
  m_BinaryDataN4InformationExt2IsSet = true;
}
bool ModifyPduSession_400_response::binaryDataN4InformationExt2IsSet() const {
  return m_BinaryDataN4InformationExt2IsSet;
}
void ModifyPduSession_400_response::unsetBinaryDataN4InformationExt2() {
  m_BinaryDataN4InformationExt2IsSet = false;
}
std::string ModifyPduSession_400_response::getBinaryDataN4InformationExt3()
    const {
  return m_BinaryDataN4InformationExt3;
}
void ModifyPduSession_400_response::setBinaryDataN4InformationExt3(
    std::string const& value) {
  m_BinaryDataN4InformationExt3      = value;
  m_BinaryDataN4InformationExt3IsSet = true;
}
bool ModifyPduSession_400_response::binaryDataN4InformationExt3IsSet() const {
  return m_BinaryDataN4InformationExt3IsSet;
}
void ModifyPduSession_400_response::unsetBinaryDataN4InformationExt3() {
  m_BinaryDataN4InformationExt3IsSet = false;
}

}  // namespace oai::_3gpp::model
