/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "MpsAction_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace oai::_3gpp::model {

MpsAction_anyOf::MpsAction_anyOf() {}

void MpsAction_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool MpsAction_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool MpsAction_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "MpsAction_anyOf" : pathPrefix;

  if (m_value ==
      MpsAction_anyOf::eMpsAction_anyOf::INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool MpsAction_anyOf::operator==(const MpsAction_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool MpsAction_anyOf::operator!=(const MpsAction_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const MpsAction_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case MpsAction_anyOf::eMpsAction_anyOf::INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case MpsAction_anyOf::eMpsAction_anyOf::DISABLE_MPS_FOR_DTS:
      j = "DISABLE_MPS_FOR_DTS";
      break;
    case MpsAction_anyOf::eMpsAction_anyOf::ENABLE_MPS_FOR_DTS:
      j = "ENABLE_MPS_FOR_DTS";
      break;
    case MpsAction_anyOf::eMpsAction_anyOf::AUTHORIZE_AND_ENABLE_MPS_FOR_DTS:
      j = "AUTHORIZE_AND_ENABLE_MPS_FOR_DTS";
      break;
  }
}

void from_json(const nlohmann::json& j, MpsAction_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "DISABLE_MPS_FOR_DTS") {
    o.setValue(MpsAction_anyOf::eMpsAction_anyOf::DISABLE_MPS_FOR_DTS);
  } else if (s == "ENABLE_MPS_FOR_DTS") {
    o.setValue(MpsAction_anyOf::eMpsAction_anyOf::ENABLE_MPS_FOR_DTS);
  } else if (s == "AUTHORIZE_AND_ENABLE_MPS_FOR_DTS") {
    o.setValue(
        MpsAction_anyOf::eMpsAction_anyOf::AUTHORIZE_AND_ENABLE_MPS_FOR_DTS);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " MpsAction_anyOf::eMpsAction_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

MpsAction_anyOf::eMpsAction_anyOf MpsAction_anyOf::getValue() const {
  return m_value;
}
void MpsAction_anyOf::setValue(MpsAction_anyOf::eMpsAction_anyOf value) {
  m_value = value;
}

}  // namespace oai::_3gpp::model
