/**
 * Nnef_EventExposure
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * MsNetAssInvocationCollection.h
 *
 * Contains the Media Streaming Network Assistance invocation collected for an
 * UE Application  via AF.
 */

#ifndef MsNetAssInvocationCollection_H_
#define MsNetAssInvocationCollection_H_

#include <vector>
#include "NetworkAssistanceSession.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Contains the Media Streaming Network Assistance invocation collected for an
/// UE Application  via AF.
/// </summary>
class MsNetAssInvocationCollection {
 public:
  MsNetAssInvocationCollection();
  virtual ~MsNetAssInvocationCollection() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const MsNetAssInvocationCollection& rhs) const;
  bool operator!=(const MsNetAssInvocationCollection& rhs) const;

  /////////////////////////////////////////////
  /// MsNetAssInvocationCollection members

  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::NetworkAssistanceSession> getMsNetAssInvocs()
      const;
  void setMsNetAssInvocs(
      std::vector<oai::_3gpp::model::NetworkAssistanceSession> const& value);

  friend void to_json(nlohmann::json& j, const MsNetAssInvocationCollection& o);
  friend void from_json(
      const nlohmann::json& j, MsNetAssInvocationCollection& o);

 protected:
  std::vector<oai::_3gpp::model::NetworkAssistanceSession> m_MsNetAssInvocs;
};

}  // namespace oai::_3gpp::model

#endif /* MsNetAssInvocationCollection_H_ */
