/**
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N2SmInfoType_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace oai::_3gpp::model {

N2SmInfoType_anyOf::N2SmInfoType_anyOf() {}

void N2SmInfoType_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool N2SmInfoType_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool N2SmInfoType_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "N2SmInfoType_anyOf" : pathPrefix;

  if (m_value == N2SmInfoType_anyOf::eN2SmInfoType_anyOf::
                     INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool N2SmInfoType_anyOf::operator==(const N2SmInfoType_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool N2SmInfoType_anyOf::operator!=(const N2SmInfoType_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const N2SmInfoType_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_SETUP_REQ:
      j = "PDU_RES_SETUP_REQ";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_SETUP_RSP:
      j = "PDU_RES_SETUP_RSP";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_SETUP_FAIL:
      j = "PDU_RES_SETUP_FAIL";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_REL_CMD:
      j = "PDU_RES_REL_CMD";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_REL_RSP:
      j = "PDU_RES_REL_RSP";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_REQ:
      j = "PDU_RES_MOD_REQ";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_RSP:
      j = "PDU_RES_MOD_RSP";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_FAIL:
      j = "PDU_RES_MOD_FAIL";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_NTY:
      j = "PDU_RES_NTY";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_NTY_REL:
      j = "PDU_RES_NTY_REL";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_IND:
      j = "PDU_RES_MOD_IND";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_CFM:
      j = "PDU_RES_MOD_CFM";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PATH_SWITCH_REQ:
      j = "PATH_SWITCH_REQ";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PATH_SWITCH_SETUP_FAIL:
      j = "PATH_SWITCH_SETUP_FAIL";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PATH_SWITCH_REQ_ACK:
      j = "PATH_SWITCH_REQ_ACK";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PATH_SWITCH_REQ_FAIL:
      j = "PATH_SWITCH_REQ_FAIL";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_REQUIRED:
      j = "HANDOVER_REQUIRED";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_CMD:
      j = "HANDOVER_CMD";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_PREP_FAIL:
      j = "HANDOVER_PREP_FAIL";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_REQ_ACK:
      j = "HANDOVER_REQ_ACK";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_RES_ALLOC_FAIL:
      j = "HANDOVER_RES_ALLOC_FAIL";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::SECONDARY_RAT_USAGE:
      j = "SECONDARY_RAT_USAGE";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_IND_FAIL:
      j = "PDU_RES_MOD_IND_FAIL";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::UE_CONTEXT_RESUME_REQ:
      j = "UE_CONTEXT_RESUME_REQ";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::UE_CONTEXT_RESUME_RSP:
      j = "UE_CONTEXT_RESUME_RSP";
      break;
    case N2SmInfoType_anyOf::eN2SmInfoType_anyOf::UE_CONTEXT_SUSPEND_REQ:
      j = "UE_CONTEXT_SUSPEND_REQ";
      break;
  }
}

void from_json(const nlohmann::json& j, N2SmInfoType_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "PDU_RES_SETUP_REQ") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_SETUP_REQ);
  } else if (s == "PDU_RES_SETUP_RSP") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_SETUP_RSP);
  } else if (s == "PDU_RES_SETUP_FAIL") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_SETUP_FAIL);
  } else if (s == "PDU_RES_REL_CMD") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_REL_CMD);
  } else if (s == "PDU_RES_REL_RSP") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_REL_RSP);
  } else if (s == "PDU_RES_MOD_REQ") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_REQ);
  } else if (s == "PDU_RES_MOD_RSP") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_RSP);
  } else if (s == "PDU_RES_MOD_FAIL") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_FAIL);
  } else if (s == "PDU_RES_NTY") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_NTY);
  } else if (s == "PDU_RES_NTY_REL") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_NTY_REL);
  } else if (s == "PDU_RES_MOD_IND") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_IND);
  } else if (s == "PDU_RES_MOD_CFM") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_CFM);
  } else if (s == "PATH_SWITCH_REQ") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PATH_SWITCH_REQ);
  } else if (s == "PATH_SWITCH_SETUP_FAIL") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PATH_SWITCH_SETUP_FAIL);
  } else if (s == "PATH_SWITCH_REQ_ACK") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PATH_SWITCH_REQ_ACK);
  } else if (s == "PATH_SWITCH_REQ_FAIL") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PATH_SWITCH_REQ_FAIL);
  } else if (s == "HANDOVER_REQUIRED") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_REQUIRED);
  } else if (s == "HANDOVER_CMD") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_CMD);
  } else if (s == "HANDOVER_PREP_FAIL") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_PREP_FAIL);
  } else if (s == "HANDOVER_REQ_ACK") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_REQ_ACK);
  } else if (s == "HANDOVER_RES_ALLOC_FAIL") {
    o.setValue(
        N2SmInfoType_anyOf::eN2SmInfoType_anyOf::HANDOVER_RES_ALLOC_FAIL);
  } else if (s == "SECONDARY_RAT_USAGE") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::SECONDARY_RAT_USAGE);
  } else if (s == "PDU_RES_MOD_IND_FAIL") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::PDU_RES_MOD_IND_FAIL);
  } else if (s == "UE_CONTEXT_RESUME_REQ") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::UE_CONTEXT_RESUME_REQ);
  } else if (s == "UE_CONTEXT_RESUME_RSP") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::UE_CONTEXT_RESUME_RSP);
  } else if (s == "UE_CONTEXT_SUSPEND_REQ") {
    o.setValue(N2SmInfoType_anyOf::eN2SmInfoType_anyOf::UE_CONTEXT_SUSPEND_REQ);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " N2SmInfoType_anyOf::eN2SmInfoType_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

N2SmInfoType_anyOf::eN2SmInfoType_anyOf N2SmInfoType_anyOf::getValue() const {
  return m_value;
}
void N2SmInfoType_anyOf::setValue(
    N2SmInfoType_anyOf::eN2SmInfoType_anyOf value) {
  m_value = value;
}

}  // namespace oai::_3gpp::model
