################################################################################
#Licensed to the OpenAirInterface(OAI) Software Alliance under one or more
#contributor license agreements.See the NOTICE file distributed with
#this work for additional information regarding copyright ownership.
#The OpenAirInterface Software Alliance licenses this file to You under
#the OAI Public License, Version 1.1(the "License"); you may not use this file
#except in compliance with the License.
#You may obtain a copy of the License at
#
#http:  // www.openairinterface.org/?page_id=698
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
#For more information about the OpenAirInterface(OAI) Software Alliance:
#contact @openairinterface.org
################################################################################

include(${SRC_TOP_DIR}/${MOUNTED_COMMON}/model/common_model.cmake)

SET(NRF_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)
set(COMMON_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)

include_directories(${NRF_MODEL_DIR})

file(GLOB NRF_MODEL_SRC_FILES
        ${NRF_MODEL_DIR}/AccessTokenClaims.cpp
        ${NRF_MODEL_DIR}/AccessTokenRsp.cpp
        ${NRF_MODEL_DIR}/AmfCond.cpp
        ${NRF_MODEL_DIR}/AmfInfo.cpp
        ${NRF_MODEL_DIR}/AusfInfo.cpp
        ${NRF_MODEL_DIR}/BsfInfo.cpp
        ${NRF_MODEL_DIR}/ChfInfo.cpp
        ${NRF_MODEL_DIR}/ChfServiceInfo.cpp
        ${NRF_MODEL_DIR}/DataSetId.cpp
        ${NRF_MODEL_DIR}/DefaultNotificationSubscription.cpp
        ${NRF_MODEL_DIR}/DnnSmfInfoItem.cpp
        ${NRF_MODEL_DIR}/DnnUpfInfoItem.cpp
        ${NRF_MODEL_DIR}/EventId.cpp
        ${NRF_MODEL_DIR}/GuamiListCond.cpp
        ${NRF_MODEL_DIR}/IdentityRange.cpp
        ${NRF_MODEL_DIR}/Inline_response_200.cpp
        ${NRF_MODEL_DIR}/InterfaceUpfInfoItem.cpp
        ${NRF_MODEL_DIR}/IpEndPoint.cpp
        ${NRF_MODEL_DIR}/Ipv4AddressRange.cpp
        ${NRF_MODEL_DIR}/Ipv6PrefixRange.cpp
        ${NRF_MODEL_DIR}/N1MessageClass.cpp
        ${NRF_MODEL_DIR}/N2InformationClass.cpp
        ${NRF_MODEL_DIR}/N2InterfaceAmfInfo.cpp
        ${NRF_MODEL_DIR}/NetworkSliceCond.cpp
        ${NRF_MODEL_DIR}/NfGroupCond.cpp
        ${NRF_MODEL_DIR}/NfInstanceIdCond.cpp
        ${NRF_MODEL_DIR}/NFProfile.cpp
        ${NRF_MODEL_DIR}/NFService.cpp
        ${NRF_MODEL_DIR}/NFServiceStatus.cpp
        ${NRF_MODEL_DIR}/NFServiceVersion.cpp
        ${NRF_MODEL_DIR}/NFStatus.cpp
        ${NRF_MODEL_DIR}/NfTypeCond.cpp
        ${NRF_MODEL_DIR}/NotifCondition.cpp
        ${NRF_MODEL_DIR}/NotificationData.cpp
        ${NRF_MODEL_DIR}/NotificationEventType.cpp
        ${NRF_MODEL_DIR}/NotificationType.cpp
        ${NRF_MODEL_DIR}/NrfInfo.cpp
        ${NRF_MODEL_DIR}/NwdafEvent.cpp
        ${NRF_MODEL_DIR}/NwdafInfo.cpp
        ${NRF_MODEL_DIR}/PcfInfo.cpp
        ${NRF_MODEL_DIR}/PlmnRange.cpp
        ${NRF_MODEL_DIR}/PlmnSnssai.cpp
        ${NRF_MODEL_DIR}/SearchResult.cpp
        ${NRF_MODEL_DIR}/ServiceNameCond.cpp
        ${NRF_MODEL_DIR}/ServiceName.cpp
        ${NRF_MODEL_DIR}/SmfInfo.cpp
        ${NRF_MODEL_DIR}/SnssaiSmfInfoItem.cpp
        ${NRF_MODEL_DIR}/SnssaiUpfInfoItem.cpp
        ${NRF_MODEL_DIR}/StoredSearchResult.cpp
        ${NRF_MODEL_DIR}/SubscriptionData.cpp
        ${NRF_MODEL_DIR}/SupiRange.cpp
        ${NRF_MODEL_DIR}/TacRange.cpp
        ${NRF_MODEL_DIR}/TaiRange.cpp
        ${NRF_MODEL_DIR}/TngfInfo.cpp
        ${NRF_MODEL_DIR}/TwifInfo.cpp
        ${NRF_MODEL_DIR}/UdmInfo.cpp
        ${NRF_MODEL_DIR}/UdrInfo.cpp
        ${NRF_MODEL_DIR}/UpfInfo.cpp
        ${NRF_MODEL_DIR}/UPInterfaceType_anyOf.cpp
        ${NRF_MODEL_DIR}/UPInterfaceType.cpp
        ${NRF_MODEL_DIR}/WAgfInfo.cpp
        ${COMMON_MODEL_DIR}/ProblemDetails.cpp
        ${COMMON_MODEL_DIR}/InvalidParam.cpp
        ${COMMON_MODEL_DIR}/UriScheme.cpp
        ${COMMON_MODEL_DIR}/UriScheme_anyOf.cpp
        ${COMMON_MODEL_DIR}/ChangeItem.cpp
        ${COMMON_MODEL_DIR}/ChangeType.cpp
        ${COMMON_MODEL_DIR}/ChangeType_anyOf.cpp
        ${COMMON_MODEL_DIR}/Tai.cpp
        ${COMMON_MODEL_DIR}/Guami.cpp
        ${COMMON_MODEL_DIR}/PlmnId.cpp
        ${COMMON_MODEL_DIR}/PlmnIdNid.cpp
        ${COMMON_MODEL_DIR}/AccessType.cpp
        ${COMMON_MODEL_DIR}/RatType.cpp
        ${COMMON_MODEL_DIR}/RatType_anyOf.cpp
        ${COMMON_MODEL_DIR}/Snssai.cpp
        ${COMMON_MODEL_DIR}/Helpers.cpp
        ${COMMON_MODEL_DIR}/Ipv6Addr.cpp
        ${COMMON_MODEL_DIR}/Ipv6Prefix.cpp
        ${COMMON_MODEL_DIR}/PduSession.cpp
        ${COMMON_MODEL_DIR}/PduSessionType.cpp
        ${COMMON_MODEL_DIR}/PduSessionType_anyOf.cpp
        ${COMMON_MODEL_DIR}/AtsssCapability.cpp
        ${COMMON_MODEL_DIR}/PatchOperation.cpp
        ${COMMON_MODEL_DIR}/PatchOperation_anyOf.cpp
        ${COMMON_MODEL_DIR}/PatchItem.cpp
        ${COMMON_MODEL_DIR}/AccessTokenErr.cpp
        ${COMMON_MODEL_DIR}/AccessTokenReq.cpp
        ${COMMON_MODEL_DIR}/NFType.cpp
        ${COMMON_MODEL_DIR}/NFType_anyOf.cpp
        ${COMMON_MODEL_DIR}/TransportProtocol.cpp
        ${COMMON_MODEL_DIR}/TransportProtocol_anyOf.cpp
        # dependencies from ComplexQuery
        ${COMMON_MODEL_DIR}/ComplexQuery.cpp
        ${COMMON_MODEL_DIR}/CnfUnit.cpp
        ${COMMON_MODEL_DIR}/DnfUnit.cpp
        ${COMMON_MODEL_DIR}/Atom.cpp  
        ${COMMON_MODEL_DIR}/LinksValueSchema.cpp
        ${COMMON_MODEL_DIR}/AccessTokenClaims_aud.cpp
        ${COMMON_MODEL_DIR}/SuciInfo.cpp
        ${COMMON_MODEL_DIR}/DataSetId_anyOf.cpp
        ${COMMON_MODEL_DIR}/DefSubServiceInfo.cpp
        ${COMMON_MODEL_DIR}/DnnSmfInfoItem_dnn.cpp
        ${COMMON_MODEL_DIR}/DnnSmfInfoItem_dnaiList_inner.cpp
        ${COMMON_MODEL_DIR}/IpIndex.cpp
        ${COMMON_MODEL_DIR}/EventId_anyOf.cpp
        ${COMMON_MODEL_DIR}/TransportProtocol_1.cpp
        ${COMMON_MODEL_DIR}/N1MessageClass_anyOf.cpp
        ${COMMON_MODEL_DIR}/N2InformationClass_anyOf.cpp
        ${COMMON_MODEL_DIR}/NefInfo.cpp
        ${COMMON_MODEL_DIR}/UdsfInfo.cpp
        ${COMMON_MODEL_DIR}/LmfInfo.cpp
        ${COMMON_MODEL_DIR}/GmlcInfo.cpp
        ${COMMON_MODEL_DIR}/ScpInfo.cpp
        ${COMMON_MODEL_DIR}/SeppInfo.cpp
        ${COMMON_MODEL_DIR}/r_5GDdnmfInfo.cpp
        ${COMMON_MODEL_DIR}/MfafInfo.cpp
        ${COMMON_MODEL_DIR}/DccfInfo.cpp
        ${COMMON_MODEL_DIR}/TrustAfInfo.cpp
       ${COMMON_MODEL_DIR}/NssaafInfo.cpp
        ${COMMON_MODEL_DIR}/IwmscInfo.cpp
        ${COMMON_MODEL_DIR}/MnpfInfo.cpp
        ${COMMON_MODEL_DIR}/CollocatedNfInstance.cpp
        ${COMMON_MODEL_DIR}/ExtSnssai.cpp
        ${COMMON_MODEL_DIR}/NefInfo.cpp
        ${COMMON_MODEL_DIR}/r_5GDdnmfInfo.cpp
        ${COMMON_MODEL_DIR}/CollocatedNfType.cpp
        ${COMMON_MODEL_DIR}/SdRange.cpp
        ${COMMON_MODEL_DIR}/ExternalClientType.cpp
        ${COMMON_MODEL_DIR}/AnNodeType.cpp
        ${COMMON_MODEL_DIR}/SupportedGADShapes.cpp
        ${COMMON_MODEL_DIR}/AnNodeType.cpp
        ${COMMON_MODEL_DIR}/HssInfo.cpp
        ${COMMON_MODEL_DIR}/PcscfInfo.cpp
        ${COMMON_MODEL_DIR}/AanfInfo.cpp
        ${COMMON_MODEL_DIR}/EasdfInfo.cpp
        ${COMMON_MODEL_DIR}/NsacfInfo.cpp
        ${COMMON_MODEL_DIR}/MbSmfInfo.cpp
        ${COMMON_MODEL_DIR}/TsctsfInfo.cpp
        ${COMMON_MODEL_DIR}/MbUpfInfo.cpp
        ${COMMON_MODEL_DIR}/PcscfInfo.cpp
        ${COMMON_MODEL_DIR}/HssInfo.cpp
        ${COMMON_MODEL_DIR}/VendorSpecificFeature.cpp
        ${COMMON_MODEL_DIR}/NFStatus_anyOf.cpp
        ${COMMON_MODEL_DIR}/AfEventExposureData.cpp
        ${COMMON_MODEL_DIR}/UnTrustAfInfo.cpp
        ${COMMON_MODEL_DIR}/ConditionEventType.cpp
        ${COMMON_MODEL_DIR}/NotificationEventType_anyOf.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUdrInfo_value.cpp
        ${COMMON_MODEL_DIR}/NfInfo.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUdsfInfo_value.cpp
        ${COMMON_MODEL_DIR}/AfEvent.cpp
        ${COMMON_MODEL_DIR}/AnNodeType_anyOf.cpp
        ${COMMON_MODEL_DIR}/CollocatedNfType_anyOf.cpp
        ${COMMON_MODEL_DIR}/ConditionEventType.cpp
        ${COMMON_MODEL_DIR}/ConditionEventType_anyOf.cpp
        ${COMMON_MODEL_DIR}/SnssaiEasdfInfoItem.cpp
        ${COMMON_MODEL_DIR}/IpAddr.cpp
        ${COMMON_MODEL_DIR}/ExternalClientType_anyOf.cpp
        ${COMMON_MODEL_DIR}/ImsiRange.cpp
        ${COMMON_MODEL_DIR}/TmgiRange.cpp
        ${COMMON_MODEL_DIR}/SnssaiMbSmfInfoItem.cpp
        ${COMMON_MODEL_DIR}/MbSmfInfo.cpp
        ${COMMON_MODEL_DIR}/MbsSession.cpp
        ${COMMON_MODEL_DIR}/PlmnOauth2.cpp
        ${COMMON_MODEL_DIR}/PfdData.cpp
        ${COMMON_MODEL_DIR}/SubscriptionContext.cpp
        ${COMMON_MODEL_DIR}/NotificationType_anyOf.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUdmInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedAusfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedAmfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedSmfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUpfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedPcfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedBsfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedChfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedNefInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedNwdafInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedGmlcInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedLmfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedScpInfoList_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedSeppInfoList_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUdmInfo_value.cpp
        ${COMMON_MODEL_DIR}/AfEvent_anyOf.cpp
        ${COMMON_MODEL_DIR}/MbsSessionId.cpp
        ${COMMON_MODEL_DIR}/Tmgi.cpp
        ${COMMON_MODEL_DIR}/Ssm.cpp
        ${COMMON_MODEL_DIR}/MbsServiceType.cpp
        ${COMMON_MODEL_DIR}/MbsServiceArea.cpp
        ${COMMON_MODEL_DIR}/ExternalMbsServiceArea.cpp
        ${COMMON_MODEL_DIR}/MbsSessionSubscription.cpp
        ${COMMON_MODEL_DIR}/TunnelAddress.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedPcscfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedHssInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedAanfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedMbSmfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedPcscfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedHssInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedAanfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedMbSmfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NwdafCapability.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedNwdafInfo_value.cpp
        ${COMMON_MODEL_DIR}/MlAnalyticsInfo.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedPcfInfo_value.cpp
        ${COMMON_MODEL_DIR}/V2xCapability.cpp
        ${COMMON_MODEL_DIR}/ProSeCapability.cpp
        ${COMMON_MODEL_DIR}/ScpCapability.cpp
        ${COMMON_MODEL_DIR}/IpReachability.cpp
        ${COMMON_MODEL_DIR}/ScpDomainInfo.cpp
        ${COMMON_MODEL_DIR}/InternalGroupIdRange.cpp
        ${COMMON_MODEL_DIR}/SharedDataIdRange.cpp
        ${COMMON_MODEL_DIR}/NsacfCapability.cpp
        ${COMMON_MODEL_DIR}/NwdafEvent_anyOf.cpp
        ${COMMON_MODEL_DIR}/GeographicArea.cpp
        ${COMMON_MODEL_DIR}/CivicAddress.cpp
        ${COMMON_MODEL_DIR}/IpReachability_anyOf.cpp
        ${COMMON_MODEL_DIR}/NcgiTai.cpp
        ${COMMON_MODEL_DIR}/MbsServiceType_anyOf.cpp
        ${COMMON_MODEL_DIR}/MbsServiceInfo.cpp
        ${COMMON_MODEL_DIR}/MbsSessionActivityStatus.cpp
        ${COMMON_MODEL_DIR}/MbsSessionEvent.cpp
        ${COMMON_MODEL_DIR}/ScpCapability_anyOf.cpp
        ${COMMON_MODEL_DIR}/PreferredSearch.cpp
        ${COMMON_MODEL_DIR}/NfInstanceInfo.cpp
        ${COMMON_MODEL_DIR}/ServiceName_anyOf.cpp
        ${COMMON_MODEL_DIR}/DnnEasdfInfoItem.cpp
        ${COMMON_MODEL_DIR}/DnnMbSmfInfoItem.cpp
        ${COMMON_MODEL_DIR}/SupportedGADShapes_anyOf.cpp
        ${COMMON_MODEL_DIR}/TransportProtocol_anyOf.cpp
        ${COMMON_MODEL_DIR}/SnssaiInfoItem.cpp
        ${COMMON_MODEL_DIR}/SnssaiTsctsfInfoItem.cpp
        ${COMMON_MODEL_DIR}/MdtUserConsent.cpp
        ${COMMON_MODEL_DIR}/MdtConfiguration.cpp
        ${COMMON_MODEL_DIR}/EcRestrictionDataWb.cpp
        ${COMMON_MODEL_DIR}/ExpectedUeBehaviourData.cpp
        ${COMMON_MODEL_DIR}/WirelineServiceAreaRestriction.cpp
        ${COMMON_MODEL_DIR}/AerialUeSubscriptionInfo.cpp
        ${COMMON_MODEL_DIR}/RoamingRestrictions.cpp
        ${COMMON_MODEL_DIR}/SorUpdateIndicator.cpp
        ${COMMON_MODEL_DIR}/AccessAndMobilitySubscriptionData_subscribedDnnList_inner.cpp
        ${COMMON_MODEL_DIR}/PtwParameters.cpp
        ${COMMON_MODEL_DIR}/WirelineArea.cpp
        ${COMMON_MODEL_DIR}/MdtUserConsent.cpp
        ${COMMON_MODEL_DIR}/TraceData_1.cpp
        ${COMMON_MODEL_DIR}/CagData.cpp
        ${COMMON_MODEL_DIR}/WirelineServiceAreaRestriction.cpp
        ${COMMON_MODEL_DIR}/AerialUeIndication.cpp
        ${COMMON_MODEL_DIR}/CagInfo.cpp
        ${COMMON_MODEL_DIR}/StationaryIndication.cpp
        ${COMMON_MODEL_DIR}/ScheduledCommunicationTime.cpp
        ${COMMON_MODEL_DIR}/ScheduledCommunicationType.cpp
        ${COMMON_MODEL_DIR}/TrafficProfile.cpp
        ${COMMON_MODEL_DIR}/LocationArea.cpp
        ${COMMON_MODEL_DIR}/StationaryIndication.cpp
        ${COMMON_MODEL_DIR}/GeographicalCoordinates.cpp
        ${COMMON_MODEL_DIR}/ReservPriority.cpp
        ${COMMON_MODEL_DIR}/MbsMediaCompRm.cpp
        ${COMMON_MODEL_DIR}/MbsSessionActivityStatus_anyOf.cpp
        ${COMMON_MODEL_DIR}/MbsSessionEventType.cpp
        ${COMMON_MODEL_DIR}/ReportTypeMdt.cpp
        ${COMMON_MODEL_DIR}/AreaScope.cpp
        ${COMMON_MODEL_DIR}/ReportIntervalMdt.cpp
        ${COMMON_MODEL_DIR}/ReportIntervalNrMdt.cpp
        ${COMMON_MODEL_DIR}/ReportAmountMdt.cpp
        ${COMMON_MODEL_DIR}/LoggingIntervalMdt.cpp
        ${COMMON_MODEL_DIR}/LoggingIntervalNrMdt.cpp
        ${COMMON_MODEL_DIR}/LoggingDurationMdt.cpp
        ${COMMON_MODEL_DIR}/LoggingDurationNrMdt.cpp
        ${COMMON_MODEL_DIR}/PositioningMethodMdt.cpp
        ${COMMON_MODEL_DIR}/CollectionPeriodRmmLteMdt.cpp
        ${COMMON_MODEL_DIR}/CollectionPeriodRmmNrMdt.cpp
        ${COMMON_MODEL_DIR}/MeasurementPeriodLteMdt.cpp
        ${COMMON_MODEL_DIR}/SensorMeasurement.cpp
        ${COMMON_MODEL_DIR}/MeasurementLteForMdt.cpp
        ${COMMON_MODEL_DIR}/ReportingTrigger.cpp
        ${COMMON_MODEL_DIR}/EventForMdt.cpp
        ${COMMON_MODEL_DIR}/PositioningMethodMdt.cpp
        ${COMMON_MODEL_DIR}/MbsfnArea.cpp
        ${COMMON_MODEL_DIR}/JobType.cpp
        ${COMMON_MODEL_DIR}/AerialUeIndication_anyOf.cpp
        ${COMMON_MODEL_DIR}/TacInfo.cpp
        ${COMMON_MODEL_DIR}/CollectionPeriodRmmLteMdt_anyOf.cpp
        ${COMMON_MODEL_DIR}/CollectionPeriodRmmNrMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/UncertaintyEllipse.cpp
	${COMMON_MODEL_DIR}/JobType_anyOf.cpp
	${COMMON_MODEL_DIR}/NetworkAreaInfo_1.cpp
	${COMMON_MODEL_DIR}/UmtTime.cpp
	${COMMON_MODEL_DIR}/LoggingDurationMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/LoggingIntervalMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/LoggingIntervalNrMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/MbsMediaInfo.cpp
	${COMMON_MODEL_DIR}/MbsQoSReq.cpp
	${COMMON_MODEL_DIR}/MbsSessionEventType_anyOf.cpp
	${COMMON_MODEL_DIR}/MeasurementNrForMdt.cpp
	${COMMON_MODEL_DIR}/InterFreqTargetInfo.cpp
	${COMMON_MODEL_DIR}/MdtUserConsent_anyOf.cpp
	${COMMON_MODEL_DIR}/MeasurementLteForMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/MeasurementPeriodLteMdt.cpp
	${COMMON_MODEL_DIR}/CollectionPeriodRmmLteMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/Ncgi.cpp
	${COMMON_MODEL_DIR}/PositioningMethodMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/OperationMode.cpp
	${COMMON_MODEL_DIR}/ReportAmountMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/ReportIntervalMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/ReservPriority_anyOf.cpp
	${COMMON_MODEL_DIR}/NrppaInformation.cpp
	${COMMON_MODEL_DIR}/RefToBinaryData.cpp
	${COMMON_MODEL_DIR}/N2InformationTransferReqData.cpp
	${COMMON_MODEL_DIR}/N1N2MessageTransferReqData.cpp
	${COMMON_MODEL_DIR}/N2InfoContent.cpp
	${COMMON_MODEL_DIR}/EventForMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/BatteryIndication.cpp
	${COMMON_MODEL_DIR}/MediaType.cpp
	${COMMON_MODEL_DIR}/N1MessageContainer.cpp
	${COMMON_MODEL_DIR}/AreaOfValidity.cpp
	${COMMON_MODEL_DIR}/NgapIeType.cpp
	${COMMON_MODEL_DIR}/RatSelector.cpp
	${COMMON_MODEL_DIR}/OperationMode_anyOf.cpp
	${COMMON_MODEL_DIR}/ReportingTrigger_anyOf.cpp
	${COMMON_MODEL_DIR}/ScheduledCommunicationType_anyOf.cpp
	${COMMON_MODEL_DIR}/NoProfileMatchInfo.cpp
	${COMMON_MODEL_DIR}/SensorMeasurement_anyOf.cpp
	${COMMON_MODEL_DIR}/DnnInfoItem.cpp
	${COMMON_MODEL_DIR}/DnnTsctsfInfoItem.cpp
	${COMMON_MODEL_DIR}/SorUpdateIndicator_anyOf.cpp
	${COMMON_MODEL_DIR}/StationaryIndication_anyOf.cpp
	${COMMON_MODEL_DIR}/SubscrCond.cpp
	${COMMON_MODEL_DIR}/TrafficProfile_anyOf.cpp
	${COMMON_MODEL_DIR}/ServiceAreaRestriction.cpp
	${COMMON_MODEL_DIR}/PcfSelectionAssistanceInfo.cpp
	${COMMON_MODEL_DIR}/PlmnRestriction.cpp
	${COMMON_MODEL_DIR}/EdrxParameters.cpp
	${COMMON_MODEL_DIR}/PcfSelectionAssistanceInfo.cpp
	${COMMON_MODEL_DIR}/AccessNetworkId_anyOf.cpp
	${COMMON_MODEL_DIR}/AccessTech_anyOf.cpp
	${COMMON_MODEL_DIR}/UeReachableInd.cpp
	${COMMON_MODEL_DIR}/AuthType_anyOf.cpp
	${COMMON_MODEL_DIR}/ServerAddressingInfo.cpp
	${COMMON_MODEL_DIR}/AvType_anyOf.cpp
	${COMMON_MODEL_DIR}/CmInfo.cpp
	${COMMON_MODEL_DIR}/FailedMonitoringConfiguration.cpp
	${COMMON_MODEL_DIR}/DataSetName_anyOf.cpp
	${COMMON_MODEL_DIR}/DeregistrationReason_anyOf.cpp
	${COMMON_MODEL_DIR}/FrameRouteInfo.cpp
	${COMMON_MODEL_DIR}/AcsInfo.cpp
	${COMMON_MODEL_DIR}/EcsAddrConfigInfo.cpp
	${COMMON_MODEL_DIR}/UeId.cpp
	${COMMON_MODEL_DIR}/HssAuthType_anyOf.cpp
	${COMMON_MODEL_DIR}/HssAuthTypeInUri_anyOf.cpp
	${COMMON_MODEL_DIR}/HssAvType_anyOf.cpp
	${COMMON_MODEL_DIR}/HssAvType.cpp
	${COMMON_MODEL_DIR}/HssAvType_anyOf.cpp
	${COMMON_MODEL_DIR}/ImsVoPs_anyOf.cpp
	${COMMON_MODEL_DIR}/NodeType_anyOf.cpp
	${COMMON_MODEL_DIR}/AdditionalSnssaiData.cpp
	${COMMON_MODEL_DIR}/SliceMbrRm.cpp
	${COMMON_MODEL_DIR}/CmState.cpp
	${COMMON_MODEL_DIR}/EcsServerAddr.cpp
	${COMMON_MODEL_DIR}/FailedCause.cpp
	${COMMON_MODEL_DIR}/MediaType_anyOf.cpp
	${COMMON_MODEL_DIR}/N2InfoContainer.cpp
	${COMMON_MODEL_DIR}/GlobalRanNodeId.cpp
	${COMMON_MODEL_DIR}/Ecgi.cpp
	${COMMON_MODEL_DIR}/NgapIeType_anyOf.cpp
	${COMMON_MODEL_DIR}/NoProfileMatchReason.cpp
	${COMMON_MODEL_DIR}/QueryParamCombination.cpp
	${COMMON_MODEL_DIR}/RatSelector_anyOf.cpp
	${COMMON_MODEL_DIR}/ReportIntervalNrMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/ReportTypeMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/UeReachableInd_anyOf.cpp
	${COMMON_MODEL_DIR}/UserLocation.cpp
	${COMMON_MODEL_DIR}/PcscfAddress.cpp
	${COMMON_MODEL_DIR}/PduSessionContinuityInd_anyOf.cpp
	${COMMON_MODEL_DIR}/UeReachability.cpp
	${COMMON_MODEL_DIR}/RegistrationDataSetName_anyOf.cpp
	${COMMON_MODEL_DIR}/RegistrationReason_anyOf.cpp
	${COMMON_MODEL_DIR}/UserLocation.cpp
	${COMMON_MODEL_DIR}/LossOfConnectivityReason.cpp
	${COMMON_MODEL_DIR}/PdnConnectivityStatus.cpp
	${COMMON_MODEL_DIR}/AuthResult.cpp
	${COMMON_MODEL_DIR}/ImmediateReport.cpp
	${COMMON_MODEL_DIR}/SuggestedPacketNumDl.cpp
	${COMMON_MODEL_DIR}/AccessAndMobilitySubscriptionData_1.cpp
	${COMMON_MODEL_DIR}/SmsSubscriptionData_1.cpp
	${COMMON_MODEL_DIR}/SmsManagementSubscriptionData_1.cpp
	${COMMON_MODEL_DIR}/SessionManagementSubscriptionData_1.cpp
	${COMMON_MODEL_DIR}/EcsAddrConfigInfo_1.cpp
	${COMMON_MODEL_DIR}/EcsAddrConfigInfo_1.cpp
	${COMMON_MODEL_DIR}/SqnScheme_anyOf.cpp
	${COMMON_MODEL_DIR}/UeContextInAmfData.cpp
	${COMMON_MODEL_DIR}/SmSubsData.cpp
	${COMMON_MODEL_DIR}/LcsPrivacyData.cpp
	${COMMON_MODEL_DIR}/V2xSubscriptionData.cpp
	${COMMON_MODEL_DIR}/LcsBroadcastAssistanceTypesData.cpp
	${COMMON_MODEL_DIR}/ProseSubscriptionData.cpp
	${COMMON_MODEL_DIR}/MbsSubscriptionData.cpp
	${COMMON_MODEL_DIR}/UcSubscriptionData.cpp
	${COMMON_MODEL_DIR}/UeContextInAmfData.cpp
	${COMMON_MODEL_DIR}/GNbId.cpp
	${COMMON_MODEL_DIR}/UeContext.cpp
	${COMMON_MODEL_DIR}/RegistrationContextContainer.cpp
	${COMMON_MODEL_DIR}/GlobalRanNodeId.cpp
	${COMMON_MODEL_DIR}/UeN1N2InfoSubscriptionCreatedData.cpp
	${COMMON_MODEL_DIR}/NonUeN2InfoSubscriptionCreatedData.cpp
	${COMMON_MODEL_DIR}/UeN1N2InfoSubscriptionCreateData.cpp
	${COMMON_MODEL_DIR}/UEAuthenticationCtx.cpp
	${COMMON_MODEL_DIR}/AuthenticationInfo.cpp
	${COMMON_MODEL_DIR}/ConfirmationDataResponse.cpp
	${COMMON_MODEL_DIR}/AmfEventState.cpp
	${COMMON_MODEL_DIR}/AmfEventReport.cpp
	${COMMON_MODEL_DIR}/AmfEventType.cpp
	${COMMON_MODEL_DIR}/LossOfConnectivityReason.cpp
	${COMMON_MODEL_DIR}/AuthorizedNetworkSliceInfo.cpp
	${COMMON_MODEL_DIR}/CommunicationFailure.cpp
	${COMMON_MODEL_DIR}/IdleStatusIndication.cpp
	${COMMON_MODEL_DIR}/AmfEventArea.cpp
	${COMMON_MODEL_DIR}/RmInfo.cpp
	${COMMON_MODEL_DIR}/UEIdExt.cpp
	${COMMON_MODEL_DIR}/UeAccessBehaviorReportItem.cpp
	${COMMON_MODEL_DIR}/MmTransactionLocationReportItem.cpp
	${COMMON_MODEL_DIR}/MmTransactionSliceReportItem.cpp
	${COMMON_MODEL_DIR}/AmfEventType_anyOf.cpp
	${COMMON_MODEL_DIR}/NsiInformation.cpp
	${COMMON_MODEL_DIR}/MappingOfSnssai.cpp
	${COMMON_MODEL_DIR}/CmState_anyOf.cpp
	${COMMON_MODEL_DIR}/FailedCause_anyOf.cpp
	${COMMON_MODEL_DIR}/NetworkAreaInfo.cpp
	${COMMON_MODEL_DIR}/LossOfConnectivityReason_anyOf.cpp
	${COMMON_MODEL_DIR}/N2SmInformation.cpp
	${COMMON_MODEL_DIR}/N2RanInformation.cpp
	${COMMON_MODEL_DIR}/V2xInformation.cpp
	${COMMON_MODEL_DIR}/ProSeInformation.cpp
	${COMMON_MODEL_DIR}/PwsInformation.cpp
	${COMMON_MODEL_DIR}/NoProfileMatchReason_anyOf.cpp
	${COMMON_MODEL_DIR}/PdnConnectivityStatus_anyOf.cpp
	${COMMON_MODEL_DIR}/ProseServiceAuth.cpp
	${COMMON_MODEL_DIR}/AllowedNssai.cpp
	${COMMON_MODEL_DIR}/CeModeBInd.cpp
	${COMMON_MODEL_DIR}/NpnAccessInfo.cpp
	${COMMON_MODEL_DIR}/AllowedNssai.cpp
	${COMMON_MODEL_DIR}/LteMInd.cpp
	${COMMON_MODEL_DIR}/NpnAccessInfo.cpp
	${COMMON_MODEL_DIR}/UserConsent.cpp
	${COMMON_MODEL_DIR}/SbiBindingLevel.cpp
	${COMMON_MODEL_DIR}/V2xContext.cpp
	${COMMON_MODEL_DIR}/MoExpDataCounter.cpp
	${COMMON_MODEL_DIR}/ProseContext.cpp
	${COMMON_MODEL_DIR}/PcfUeCallbackInfo.cpp
	${COMMON_MODEL_DIR}/AsTimeDistributionParam.cpp
	${COMMON_MODEL_DIR}/SmallDataRateStatusInfo.cpp
	${COMMON_MODEL_DIR}/SeafData.cpp
	${COMMON_MODEL_DIR}/SbiBindingLevel.cpp
	${COMMON_MODEL_DIR}/MoExpDataCounter.cpp
	${COMMON_MODEL_DIR}/SmfSelectionData.cpp
	${COMMON_MODEL_DIR}/AsTimeDistributionParam.cpp
	${COMMON_MODEL_DIR}/MmContext.cpp
	${COMMON_MODEL_DIR}/SmallDataRateStatusInfo.cpp
	${COMMON_MODEL_DIR}/PduSessionInfo.cpp
	${COMMON_MODEL_DIR}/PresenceInfo.cpp
	${COMMON_MODEL_DIR}/PolicyReqTrigger.cpp
	${COMMON_MODEL_DIR}/ExtAmfEventSubscription.cpp
	${COMMON_MODEL_DIR}/MmContext.cpp
	${COMMON_MODEL_DIR}/PduSessionContext.cpp
	${COMMON_MODEL_DIR}/AnalyticsSubscription.cpp
	${COMMON_MODEL_DIR}/NrLocation.cpp
	${COMMON_MODEL_DIR}/EutraLocation.cpp
	${COMMON_MODEL_DIR}/N3gaLocation.cpp
	${COMMON_MODEL_DIR}/GeraLocation.cpp
	${COMMON_MODEL_DIR}/NwdafRegistrationInfo.cpp
	${COMMON_MODEL_DIR}/UeContextInSmfData.cpp	
	${COMMON_MODEL_DIR}/UeContextInSmfDataSubFilter.cpp
	${COMMON_MODEL_DIR}/VnGroupData.cpp
	${COMMON_MODEL_DIR}/SharedDataTreatmentInstruction.cpp
	${COMMON_MODEL_DIR}/SmContextStatus.cpp
	${COMMON_MODEL_DIR}/NonUeN2InfoSubscriptionCreateData.cpp
	${COMMON_MODEL_DIR}/AllowedSnssai.cpp
	${COMMON_MODEL_DIR}/LadnInfo.cpp
	${COMMON_MODEL_DIR}/r_5GsUserStateInfo.cpp
	${COMMON_MODEL_DIR}/SnssaiTaiMapping.cpp
	${COMMON_MODEL_DIR}/UeLocationTrendsReportItem.cpp
	${COMMON_MODEL_DIR}/NwdafSubscription.cpp
	${COMMON_MODEL_DIR}/ConfiguredSnssai.cpp
	${COMMON_MODEL_DIR}/NsagInfo.cpp
	${COMMON_MODEL_DIR}/NgApCause.cpp
	${COMMON_MODEL_DIR}/SpatialValidityCond.cpp
	${COMMON_MODEL_DIR}/AmfEventMode.cpp
	${COMMON_MODEL_DIR}/AmfEvent.cpp
	${COMMON_MODEL_DIR}/CellGlobalId.cpp
	${COMMON_MODEL_DIR}/ServiceAreaId.cpp
	${COMMON_MODEL_DIR}/LocationAreaId.cpp
	${COMMON_MODEL_DIR}/RoutingAreaId.cpp
	${COMMON_MODEL_DIR}/LcsMoData.cpp
	${COMMON_MODEL_DIR}/Lpi.cpp
	${COMMON_MODEL_DIR}/UnrelatedClass.cpp
	${COMMON_MODEL_DIR}/PlmnOperatorClass.cpp
	${COMMON_MODEL_DIR}/NasSecurityMode.cpp
	${COMMON_MODEL_DIR}/EpsNasSecurityMode.cpp
	${COMMON_MODEL_DIR}/ExpectedUeBehavior.cpp
	${COMMON_MODEL_DIR}/UeDifferentiationInfo.cpp
	${COMMON_MODEL_DIR}/UuaaMmStatus.cpp
	${COMMON_MODEL_DIR}/NssaiMapping.cpp
	${COMMON_MODEL_DIR}/TwapId.cpp
	${COMMON_MODEL_DIR}/HfcNodeId.cpp
	${COMMON_MODEL_DIR}/LineType.cpp
	${COMMON_MODEL_DIR}/TnapId.cpp
	${COMMON_MODEL_DIR}/CnAssistedRanPara.cpp
	${COMMON_MODEL_DIR}/PolicyReqTrigger_anyOf.cpp
	${COMMON_MODEL_DIR}/PolicyAssociation.cpp
	${COMMON_MODEL_DIR}/PolicyAssociationRequest.cpp 
	${COMMON_MODEL_DIR}/PolicyAssociationUpdateRequest.cpp
	${COMMON_MODEL_DIR}/PolicyUpdate.cpp
	${COMMON_MODEL_DIR}/PresenceInfoRm.cpp
	${COMMON_MODEL_DIR}/TerminationNotification.cpp
	${COMMON_MODEL_DIR}/SmPolicyAssociationReleaseCause.cpp
	${COMMON_MODEL_DIR}/SmPolicyAssociationReleaseCause_anyOf.cpp	
	${COMMON_MODEL_DIR}/AmRequestedValueRep.cpp
	${COMMON_MODEL_DIR}/RequestTrigger.cpp
	${COMMON_MODEL_DIR}/UeSliceMbr.cpp
	${COMMON_MODEL_DIR}/NwdafData.cpp
	${COMMON_MODEL_DIR}/RequestTrigger_anyOf.cpp                
	${COMMON_MODEL_DIR}/PresenceState.cpp
	${COMMON_MODEL_DIR}/UeAuth.cpp
	${COMMON_MODEL_DIR}/RmState.cpp
	${COMMON_MODEL_DIR}/NgKsi.cpp
	${COMMON_MODEL_DIR}/RestrictionType.cpp
	${COMMON_MODEL_DIR}/SharedDataTreatmentInstruction_anyOf.cpp
	${COMMON_MODEL_DIR}/SmContextStatus_anyOf.cpp
	${COMMON_MODEL_DIR}/UEAuthenticationCtx_5gAuthData.cpp
	${COMMON_MODEL_DIR}/AccessStateTransitionType.cpp
	${COMMON_MODEL_DIR}/ImmediateMdtConf.cpp
	${COMMON_MODEL_DIR}/UeReachability_anyOf.cpp
	${COMMON_MODEL_DIR}/UtraLocation.cpp
	${COMMON_MODEL_DIR}/LteV2xAuth.cpp
	${COMMON_MODEL_DIR}/Pc5QoSPara.cpp
	${COMMON_MODEL_DIR}/NrV2xAuth.cpp.cpp
	${COMMON_MODEL_DIR}/ReachabilityFilter.cpp
	${COMMON_MODEL_DIR}/TargetArea.cpp
	${COMMON_MODEL_DIR}/UeInAreaFilter.cpp
	${COMMON_MODEL_DIR}/DispersionArea.cpp
	${COMMON_MODEL_DIR}/LocationFilter.cpp
	${COMMON_MODEL_DIR}/TrafficDescriptor.cpp
	${COMMON_MODEL_DIR}/ReachabilityFilter.cpp
	${COMMON_MODEL_DIR}/AmfEventTrigger.cpp
	${COMMON_MODEL_DIR}/EpsNasIntegrityAlgorithm.cpp
	${COMMON_MODEL_DIR}/LineType_anyOf.cpp
	${COMMON_MODEL_DIR}/ValidTimePeriod.cpp
	${COMMON_MODEL_DIR}/LocationPrivacyInd.cpp
	${COMMON_MODEL_DIR}/NssaaStatus.cpp
	${COMMON_MODEL_DIR}/IntegrityAlgorithm.cpp
	${COMMON_MODEL_DIR}/CipheringAlgorithm.cpp
	${COMMON_MODEL_DIR}/ScType.cpp
	${COMMON_MODEL_DIR}/NwdafRegistration.cpp
	${COMMON_MODEL_DIR}/NnwdafEventsSubscription.cpp
	${COMMON_MODEL_DIR}/Pc5QosFlowItem.cpp
	${COMMON_MODEL_DIR}/EbiArpMapping.cpp
	${COMMON_MODEL_DIR}/LcsClientClass.cpp
	${COMMON_MODEL_DIR}/PresenceState_anyOf.cpp
	${COMMON_MODEL_DIR}/QueryParameter.cpp
	${COMMON_MODEL_DIR}/RestrictionType_anyOf.cpp
	${COMMON_MODEL_DIR}/RmState_anyOf.cpp
	${COMMON_MODEL_DIR}/KeyAmf.cpp
	${COMMON_MODEL_DIR}/SmallDataRateStatus.cpp
	${COMMON_MODEL_DIR}/TargetArea.cpp
	${COMMON_MODEL_DIR}/SupportedSnssai.cpp
	${COMMON_MODEL_DIR}/GeoServiceArea.cpp
	${COMMON_MODEL_DIR}/UeAuth_anyOf.cpp
	${COMMON_MODEL_DIR}/UpdpSubscriptionData.cpp
	${COMMON_MODEL_DIR}/PeriodicCommunicationIndicator.cpp
	${COMMON_MODEL_DIR}/DefaultUnrelatedClass.cpp
	${COMMON_MODEL_DIR}/UuaaMmStatus_anyOf.cpp
	${COMMON_MODEL_DIR}/r_5GsUserState.cpp
	${COMMON_MODEL_DIR}/SmContextStatusNotification.cpp
	${COMMON_MODEL_DIR}/SliceInfoForRegistration.cpp
	${COMMON_MODEL_DIR}/SubscribedSnssai.cpp
	${COMMON_MODEL_DIR}/AmfEventSubscription.cpp
	${COMMON_MODEL_DIR}/AmfCreateEventSubscription.cpp
	${COMMON_MODEL_DIR}/N1MessageNotification.cpp
	${COMMON_MODEL_DIR}/SmContextStatusNotification.cpp
	${COMMON_MODEL_DIR}/Inline_object.cpp
	${COMMON_MODEL_DIR}/UeRegStatusUpdateReqData.cpp
	${COMMON_MODEL_DIR}/UeContextTransferReqData.cpp
	${COMMON_MODEL_DIR}/AccessStateTransitionType_anyOf.cpp
	${COMMON_MODEL_DIR}/PartitioningCriteria.cpp
	${COMMON_MODEL_DIR}/AmfEventTrigger_anyOf.cpp
	${COMMON_MODEL_DIR}/CipheringAlgorithm_anyOf.cpp
	${COMMON_MODEL_DIR}/PrivacyCheckRelatedAction.cpp
	${COMMON_MODEL_DIR}/CodeWordInd.cpp
	${COMMON_MODEL_DIR}/EpsNasIntegrityAlgorithm_anyOf.cpp
	${COMMON_MODEL_DIR}/EpsNasCipheringAlgorithm.cpp
	${COMMON_MODEL_DIR}/AreaOfInterestEventState.cpp
	${COMMON_MODEL_DIR}/UeContextCreateData.cpp
	${COMMON_MODEL_DIR}/IntegrityAlgorithm_anyOf.cpp
	${COMMON_MODEL_DIR}/KeyAmfType.cpp
	${COMMON_MODEL_DIR}/LcsClientClass_anyOf.cpp
	${COMMON_MODEL_DIR}/LcsMoServiceClass.cpp
	${COMMON_MODEL_DIR}/LocationFilter_anyOf.cpp
	${COMMON_MODEL_DIR}/ReportingInformation.cpp
	${COMMON_MODEL_DIR}/PrevSubInfo.cpp
	${COMMON_MODEL_DIR}/EventSubscription.cpp
	${COMMON_MODEL_DIR}/FailureEventInfo.cpp
	${COMMON_MODEL_DIR}/EventNotification.cpp
	${COMMON_MODEL_DIR}/AuthStatus.cpp
	${COMMON_MODEL_DIR}/Pc5FlowBitRates.cpp
	${COMMON_MODEL_DIR}/PeriodicCommunicationIndicator_anyOf.cpp
	${COMMON_MODEL_DIR}/ReachabilityFilter_anyOf.cpp
	${COMMON_MODEL_DIR}/SbiBindingLevel_anyOf.cpp
	${COMMON_MODEL_DIR}/ScType_anyOf.cpp
	${COMMON_MODEL_DIR}/ReleaseCause.cpp
	${COMMON_MODEL_DIR}/ApnRateStatus.cpp
	${COMMON_MODEL_DIR}/CandidateForReplacement.cpp
	${COMMON_MODEL_DIR}/TransferReason.cpp
	${COMMON_MODEL_DIR}/UeType.cpp
	${COMMON_MODEL_DIR}/UeContextTransferStatus.cpp
	${COMMON_MODEL_DIR}/ReleaseSessionInfo.cpp
	${COMMON_MODEL_DIR}/ExternalUnrelatedClass.cpp
	${COMMON_MODEL_DIR}/NrV2xAuth.cpp
	${COMMON_MODEL_DIR}/_5GsUserState_anyOf.cpp
	${COMMON_MODEL_DIR}/N2InformationNotification.cpp
	${COMMON_MODEL_DIR}/AssignEbiData.cpp
	${COMMON_MODEL_DIR}/UEContextRelease.cpp
	${COMMON_MODEL_DIR}/AuthStatus_anyOf.cpp
	${COMMON_MODEL_DIR}/CodeWordInd_anyOf.cpp
	${COMMON_MODEL_DIR}/EpsNasCipheringAlgorithm_anyOf.cpp
	${COMMON_MODEL_DIR}/NwdafFailureCode.cpp
	${COMMON_MODEL_DIR}/AnalyticsMetadataInfo.cpp
	${COMMON_MODEL_DIR}/SliceLoadLevelInformation.cpp
	${COMMON_MODEL_DIR}/NfLoadLevelInformation.cpp
	${COMMON_MODEL_DIR}/NsiLoadLevelInfo.cpp
	${COMMON_MODEL_DIR}/ServiceExperienceInfo.cpp
	${COMMON_MODEL_DIR}/QosSustainabilityInfo.cpp
	${COMMON_MODEL_DIR}/UeCommunication.cpp
	${COMMON_MODEL_DIR}/UeMobility.cpp
	${COMMON_MODEL_DIR}/UserDataCongestionInfo.cpp
	${COMMON_MODEL_DIR}/AbnormalBehaviour.cpp
	${COMMON_MODEL_DIR}/NetworkPerfInfo.cpp
	${COMMON_MODEL_DIR}/DnPerfInfo.cpp
	${COMMON_MODEL_DIR}/DispersionInfo.cpp
	${COMMON_MODEL_DIR}/RedundantTransmissionExpInfo.cpp
	${COMMON_MODEL_DIR}/WlanPerformanceInfo.cpp
	${COMMON_MODEL_DIR}/SmcceInfo.cpp
	${COMMON_MODEL_DIR}/NwdafFailureCode.cpp
	${COMMON_MODEL_DIR}/AnalyticsMetadataInfo.cpp
	${COMMON_MODEL_DIR}/SliceLoadLevelInformation.cpp
	${COMMON_MODEL_DIR}/EventReportingRequirement.cpp
	${COMMON_MODEL_DIR}/NotificationMethod.cpp
	${COMMON_MODEL_DIR}/MatchingDirection.cpp
	${COMMON_MODEL_DIR}/QosRequirement.cpp
	${COMMON_MODEL_DIR}/TargetUeInformation.cpp
	${COMMON_MODEL_DIR}/ExpectedAnalyticsType.cpp
	${COMMON_MODEL_DIR}/UpfInformation.cpp
	${COMMON_MODEL_DIR}/ThresholdLevel.cpp
	${COMMON_MODEL_DIR}/NsiIdInfo.cpp
	${COMMON_MODEL_DIR}/RetainabilityThreshold.cpp
	${COMMON_MODEL_DIR}/ThresholdLevel.cpp
	${COMMON_MODEL_DIR}/NetworkPerfRequirement.cpp
	${COMMON_MODEL_DIR}/BwRequirement.cpp
	${COMMON_MODEL_DIR}/Exception.cpp
	${COMMON_MODEL_DIR}/RatFreqInformation.cpp
	${COMMON_MODEL_DIR}/AnalyticsSubset.cpp
	${COMMON_MODEL_DIR}/DispersionRequirement.cpp
	${COMMON_MODEL_DIR}/RedundantTransmissionExpReq.cpp
	${COMMON_MODEL_DIR}/WlanPerformanceReq.cpp
	${COMMON_MODEL_DIR}/AddrFqdn.cpp
	${COMMON_MODEL_DIR}/DnPerformanceReq.cpp
	${COMMON_MODEL_DIR}/EventSubscription.cpp
	${COMMON_MODEL_DIR}/EventReportingRequirement.cpp
	${COMMON_MODEL_DIR}/NotificationMethod.cpp
	${COMMON_MODEL_DIR}/AdditionalMeasurement.cpp
	${COMMON_MODEL_DIR}/TimeWindow.cpp
	${COMMON_MODEL_DIR}/OutputStrategy.cpp
	${COMMON_MODEL_DIR}/Accuracy.cpp
	${COMMON_MODEL_DIR}/DatasetStatisticalProperty.cpp
	${COMMON_MODEL_DIR}/TimeWindow.cpp
	${COMMON_MODEL_DIR}/AnalyticsSubset_anyOf.cpp
	${COMMON_MODEL_DIR}/DispersionCollection.cpp
	${COMMON_MODEL_DIR}/DispersionType.cpp
	${COMMON_MODEL_DIR}/DispersionOrderingCriterion.cpp
	${COMMON_MODEL_DIR}/ClassCriterion.cpp
	${COMMON_MODEL_DIR}/RankingCriterion.cpp
	${COMMON_MODEL_DIR}/DnPerf.cpp
	${COMMON_MODEL_DIR}/DnPerfOrderingCriterion.cpp
	${COMMON_MODEL_DIR}/Accuracy_anyOf.cpp
	${COMMON_MODEL_DIR}/AddressList.cpp
	${COMMON_MODEL_DIR}/IpEthFlowDescription.cpp
	${COMMON_MODEL_DIR}/CircumstanceDescription.cpp
	${COMMON_MODEL_DIR}/DispersionClass.cpp
	${COMMON_MODEL_DIR}/DatasetStatisticalProperty_anyOf.cpp
	${COMMON_MODEL_DIR}/ApplicationVolume.cpp
	${COMMON_MODEL_DIR}/DispersionOrderingCriterion_anyOf.cpp
	${COMMON_MODEL_DIR}/PerfData.cpp
	${COMMON_MODEL_DIR}/DnPerfOrderingCriterion_anyOf.cpp
	${COMMON_MODEL_DIR}/AnalyticsMetadata.cpp
	${COMMON_MODEL_DIR}/ExceptionTrend.cpp
	${COMMON_MODEL_DIR}/ExceptionId.cpp
	${COMMON_MODEL_DIR}/ExpectedAnalyticsType_anyOf.cpp
	${COMMON_MODEL_DIR}/LcsClientExternal.cpp
	${COMMON_MODEL_DIR}/LcsClientGroupExternal.cpp
	${COMMON_MODEL_DIR}/KeyAmfType_anyOf.cpp
	${COMMON_MODEL_DIR}/LcsMoServiceClass_anyOf.cpp
	${COMMON_MODEL_DIR}/N2InfoNotifyReason.cpp
	${COMMON_MODEL_DIR}/NetworkPerfType.cpp
	${COMMON_MODEL_DIR}/NfStatus.cpp
	${COMMON_MODEL_DIR}/ConsumerNfInformation.cpp
	${COMMON_MODEL_DIR}/NotificationMethod_anyOf.cpp
	${COMMON_MODEL_DIR}/ResourceUsage.cpp
	${COMMON_MODEL_DIR}/NwdafFailureCode_anyOf.cpp
	${COMMON_MODEL_DIR}/OutputStrategy_anyOf.cpp
	${COMMON_MODEL_DIR}/UeAnalyticsContextDescriptor.cpp
	${COMMON_MODEL_DIR}/PrivacyCheckRelatedAction_anyOf.cpp
	${COMMON_MODEL_DIR}/QosResourceType.cpp
	${COMMON_MODEL_DIR}/RedTransExpOrderingCriterion.cpp
	${COMMON_MODEL_DIR}/ReleaseCause_anyOf.cpp
	${COMMON_MODEL_DIR}/TimeUnit.cpp
	${COMMON_MODEL_DIR}/ServiceExperienceType.cpp
	${COMMON_MODEL_DIR}/SmcceUeList.cpp
	${COMMON_MODEL_DIR}/TransferReason_anyOf.cpp
	${COMMON_MODEL_DIR}/TrafficCharacterization.cpp
	${COMMON_MODEL_DIR}/AppListForUeComm.cpp
	${COMMON_MODEL_DIR}/SessInactTimerForUeComm.cpp
	${COMMON_MODEL_DIR}/NgRanTargetId.cpp
	${COMMON_MODEL_DIR}/UeContextTransferStatus_anyOf.cpp
	${COMMON_MODEL_DIR}/UeType_anyOf.cpp
	${COMMON_MODEL_DIR}/UeRegStatusUpdateReqData.cpp
	${COMMON_MODEL_DIR}/AppDescriptor.cpp
	${COMMON_MODEL_DIR}/WlanOrderingCriterion.cpp
	${COMMON_MODEL_DIR}/AnalyticsMetadata_anyOf.cpp
	${COMMON_MODEL_DIR}/AnalyticsMetadataIndication.cpp
	${COMMON_MODEL_DIR}/ExceptionId_anyOf.cpp
	${COMMON_MODEL_DIR}/AfExternal.cpp
	${COMMON_MODEL_DIR}/EthFlowDescription.cpp
	${COMMON_MODEL_DIR}/LocationPrivacyInd_anyOf.cpp
	${COMMON_MODEL_DIR}/MatchingDirection_anyOf.cpp
	${COMMON_MODEL_DIR}/MatchingDirection.cpp
	${COMMON_MODEL_DIR}/N2InfoNotifyReason_anyOf.cpp
	${COMMON_MODEL_DIR}/SmfChangeInfo.cpp
	${COMMON_MODEL_DIR}/NetworkPerfType_anyOf.cpp
	${COMMON_MODEL_DIR}/NumberAverage.cpp
	${COMMON_MODEL_DIR}/PartitioningCriteria_anyOf.cpp
	${COMMON_MODEL_DIR}/QosResourceType_anyOf.cpp
	${COMMON_MODEL_DIR}/RedTransExpOrderingCriterion_anyOf.cpp
	${COMMON_MODEL_DIR}/RedundantTransmissionExpPerTS.cpp
	${COMMON_MODEL_DIR}/SvcExperience.cpp
	${COMMON_MODEL_DIR}/ServiceExperienceType_anyOf.cpp
	${COMMON_MODEL_DIR}/TimeUnit_anyOf.cpp
	${COMMON_MODEL_DIR}/SliceMbr.cpp
	${COMMON_MODEL_DIR}/ServiceTypeUnrelatedClass.cpp
	${COMMON_MODEL_DIR}/CongestionInfo.cpp
	${COMMON_MODEL_DIR}/WlanOrderingCriterion_anyOf.cpp
	${COMMON_MODEL_DIR}/WlanPerSsIdPerformanceInfo.cpp
	${COMMON_MODEL_DIR}/ConfirmationData.cpp
	${COMMON_MODEL_DIR}/AmfUpdateEventOptionItem.cpp
	${COMMON_MODEL_DIR}/CongestionType.cpp
	${COMMON_MODEL_DIR}/TopApplication.cpp
	${COMMON_MODEL_DIR}/FlowDirection.cpp
	${COMMON_MODEL_DIR}/ExceptionTrend_anyOf.cpp
	${COMMON_MODEL_DIR}/ProSeAllowedPlmn.cpp
	${COMMON_MODEL_DIR}/ObservedRedundantTransExp.cpp
	${COMMON_MODEL_DIR}/SmfChangeIndication.cpp
	${COMMON_MODEL_DIR}/WlanPerTsPerformanceInfo.cpp
	${COMMON_MODEL_DIR}/CongestionType_anyOf.cpp
	${COMMON_MODEL_DIR}/FlowDirection_anyOf.cpp
	${COMMON_MODEL_DIR}/ProseDirectAllowed.cpp
	${COMMON_MODEL_DIR}/SmfChangeIndication_anyOf.cpp
	${COMMON_MODEL_DIR}/FlowInfo.cpp
	${COMMON_MODEL_DIR}/TrafficInformation.cpp
	${COMMON_MODEL_DIR}/ProseDirectAllowed_anyOf.cpp
        ${COMMON_MODEL_DIR}/PgwInfo.cpp
        ${COMMON_MODEL_DIR}/EmergencyInfo.cpp	
        )
        

## CONFIG used in NF_TARGET (main)
if (TARGET ${NF_TARGET})
    target_include_directories(${NF_TARGET} PUBLIC ${NRF_MODEL_DIR})
    target_sources(${NF_TARGET} PRIVATE
            ${NRF_MODEL_SRC_FILES}
            )
endif()
