/**
 * NRF NFManagement Service
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NsacfInfo.h
 *
 * Information of a NSACF NF Instance
 */

#ifndef NsacfInfo_H_
#define NsacfInfo_H_

#include "NsacfCapability.h"
#include "Tai.h"
#include <string>
#include "TaiRange.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Information of a NSACF NF Instance
/// </summary>
class NsacfInfo {
 public:
  NsacfInfo();
  virtual ~NsacfInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const NsacfInfo& rhs) const;
  bool operator!=(const NsacfInfo& rhs) const;

  /////////////////////////////////////////////
  /// NsacfInfo members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::NsacfCapability getNsacfCapability() const;
  void setNsacfCapability(oai::_3gpp::model::NsacfCapability const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::Tai> getTaiList() const;
  void setTaiList(std::vector<oai::_3gpp::model::Tai> const& value);
  bool taiListIsSet() const;
  void unsetTaiList();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::TaiRange> getTaiRangeList() const;
  void setTaiRangeList(std::vector<oai::_3gpp::model::TaiRange> const& value);
  bool taiRangeListIsSet() const;
  void unsetTaiRangeList();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getNsacSaiList() const;
  void setNsacSaiList(std::vector<std::string> const& value);
  bool nsacSaiListIsSet() const;
  void unsetNsacSaiList();

  friend void to_json(nlohmann::json& j, const NsacfInfo& o);
  friend void from_json(const nlohmann::json& j, NsacfInfo& o);

 protected:
  oai::_3gpp::model::NsacfCapability m_NsacfCapability;

  std::vector<oai::_3gpp::model::Tai> m_TaiList;
  bool m_TaiListIsSet;
  std::vector<oai::_3gpp::model::TaiRange> m_TaiRangeList;
  bool m_TaiRangeListIsSet;
  std::vector<std::string> m_NsacSaiList;
  bool m_NsacSaiListIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* NsacfInfo_H_ */
