/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PduSessionStatusCfg.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

PduSessionStatusCfg::PduSessionStatusCfg() {
  m_Dnn      = "";
  m_DnnIsSet = false;
}

void PduSessionStatusCfg::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool PduSessionStatusCfg::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool PduSessionStatusCfg::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "PduSessionStatusCfg" : pathPrefix;

  return success;
}

bool PduSessionStatusCfg::operator==(const PduSessionStatusCfg& rhs) const {
  return

      ((!dnnIsSet() && !rhs.dnnIsSet()) ||
       (dnnIsSet() && rhs.dnnIsSet() && getDnn() == rhs.getDnn()))

          ;
}

bool PduSessionStatusCfg::operator!=(const PduSessionStatusCfg& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PduSessionStatusCfg& o) {
  j = nlohmann::json();
  if (o.dnnIsSet()) j["dnn"] = o.m_Dnn;
}

void from_json(const nlohmann::json& j, PduSessionStatusCfg& o) {
  if (j.find("dnn") != j.end()) {
    j.at("dnn").get_to(o.m_Dnn);
    o.m_DnnIsSet = true;
  }
}

std::string PduSessionStatusCfg::getDnn() const {
  return m_Dnn;
}
void PduSessionStatusCfg::setDnn(std::string const& value) {
  m_Dnn      = value;
  m_DnnIsSet = true;
}
bool PduSessionStatusCfg::dnnIsSet() const {
  return m_DnnIsSet;
}
void PduSessionStatusCfg::unsetDnn() {
  m_DnnIsSet = false;
}

}  // namespace oai::_3gpp::model
