/**
 * Nnef_PFDmanagement Service API
 * Packet Flow Description Management Service.   © 2024, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PfdDataForApp.h
 *
 * Represents the PFDs for an application identifier.
 */

#ifndef PfdDataForApp_H_
#define PfdDataForApp_H_

#include <string>
#include "PfdContent.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Represents the PFDs for an application identifier.
/// </summary>
class PfdDataForApp {
 public:
  PfdDataForApp();
  virtual ~PfdDataForApp() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const PfdDataForApp& rhs) const;
  bool operator!=(const PfdDataForApp& rhs) const;

  /////////////////////////////////////////////
  /// PfdDataForApp members

  /// <summary>
  /// String providing an application identifier.
  /// </summary>
  std::string getApplicationId() const;
  void setApplicationId(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::PfdContent> getPfds() const;
  void setPfds(std::vector<oai::_3gpp::model::PfdContent> const& value);
  bool pfdsIsSet() const;
  void unsetPfds();
  /// <summary>
  /// string with format &#39;date-time&#39; as defined in OpenAPI.
  /// </summary>
  std::string getCachingTime() const;
  void setCachingTime(std::string const& value);
  bool cachingTimeIsSet() const;
  void unsetCachingTime();
  /// <summary>
  /// indicating a time in seconds.
  /// </summary>
  int32_t getCachingTimer() const;
  void setCachingTimer(int32_t const value);
  bool cachingTimerIsSet() const;
  void unsetCachingTimer();
  /// <summary>
  /// string with format &#39;date-time&#39; as defined in OpenAPI.
  /// </summary>
  std::string getPfdTimestamp() const;
  void setPfdTimestamp(std::string const& value);
  bool pfdTimestampIsSet() const;
  void unsetPfdTimestamp();
  /// <summary>
  /// Indication of partial update of PFDs for an existing application
  /// identifier if it is  included and set to true. Otherwise set to false
  /// indicates not supporting partial  update of PFDs for an existing
  /// application identifier. The default value false  applies if the attribute
  /// is not present.
  /// </summary>
  bool isPartialFlag() const;
  void setPartialFlag(bool const value);
  bool partialFlagIsSet() const;
  void unsetPartialFlag();
  /// <summary>
  /// A string used to indicate the features supported by an API that is used as
  /// defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a
  /// bitmask indicating supported features in  hexadecimal representation Each
  /// character in the string shall take a value of \&quot;0\&quot; to
  /// \&quot;9\&quot;,  \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to
  /// \&quot;F\&quot; and shall represent the support of 4 features as described
  /// in  table 5.2.2-3. The most significant character representing the
  /// highest-numbered features shall  appear first in the string, and the
  /// character representing features 1 to 4 shall appear last  in the string.
  /// The list of features and their numbering (starting with 1) are defined
  /// separately for each API. If the string contains a lower number of
  /// characters than there are  defined features for an API, all features that
  /// would be represented by characters that are not  present in the string are
  /// not supported.
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const& value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();

  friend void to_json(nlohmann::json& j, const PfdDataForApp& o);
  friend void from_json(const nlohmann::json& j, PfdDataForApp& o);

 protected:
  std::string m_ApplicationId;

  std::vector<oai::_3gpp::model::PfdContent> m_Pfds;
  bool m_PfdsIsSet;
  std::string m_CachingTime;
  bool m_CachingTimeIsSet;
  int32_t m_CachingTimer;
  bool m_CachingTimerIsSet;
  std::string m_PfdTimestamp;
  bool m_PfdTimestampIsSet;
  bool m_PartialFlag;
  bool m_PartialFlagIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* PfdDataForApp_H_ */
