/**
 * Nnef_PFDmanagement Service API
 * Packet Flow Description Management Service.   © 2024, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PfdOperation.h
 *
 * Indicates the operation to be applied on PFD(s).
 */

#ifndef PfdOperation_H_
#define PfdOperation_H_

#include "PfdOperation_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Indicates the operation to be applied on PFD(s).
/// </summary>
class PfdOperation {
 public:
  PfdOperation();
  virtual ~PfdOperation() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const PfdOperation& rhs) const;
  bool operator!=(const PfdOperation& rhs) const;

  /////////////////////////////////////////////
  /// PfdOperation members

  PfdOperation_anyOf getValue() const;
  void setValue(PfdOperation_anyOf value);
  PfdOperation_anyOf::ePfdOperation_anyOf getEnumValue() const;
  void setEnumValue(PfdOperation_anyOf::ePfdOperation_anyOf value);
  friend void to_json(nlohmann::json& j, const PfdOperation& o);
  friend void from_json(const nlohmann::json& j, PfdOperation& o);
  friend void to_json(nlohmann::json& j, const PfdOperation_anyOf& o);
  friend void from_json(const nlohmann::json& j, PfdOperation_anyOf& o);

 protected:
  PfdOperation_anyOf m_value;
};

}  // namespace oai::_3gpp::model

#endif /* PfdOperation_H_ */
