/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PlmnEcInfo.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

PlmnEcInfo::PlmnEcInfo() {
  m_EcRestrictionDataWbIsSet = false;
  m_EcRestrictionDataNb      = false;
  m_EcRestrictionDataNbIsSet = false;
}

void PlmnEcInfo::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool PlmnEcInfo::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool PlmnEcInfo::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "PlmnEcInfo" : pathPrefix;

  return success;
}

bool PlmnEcInfo::operator==(const PlmnEcInfo& rhs) const {
  return

      (getPlmnId() == rhs.getPlmnId()) &&

      ((!ecRestrictionDataWbIsSet() && !rhs.ecRestrictionDataWbIsSet()) ||
       (ecRestrictionDataWbIsSet() && rhs.ecRestrictionDataWbIsSet() &&
        getEcRestrictionDataWb() == rhs.getEcRestrictionDataWb())) &&

      ((!ecRestrictionDataNbIsSet() && !rhs.ecRestrictionDataNbIsSet()) ||
       (ecRestrictionDataNbIsSet() && rhs.ecRestrictionDataNbIsSet() &&
        isEcRestrictionDataNb() == rhs.isEcRestrictionDataNb()))

          ;
}

bool PlmnEcInfo::operator!=(const PlmnEcInfo& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PlmnEcInfo& o) {
  j           = nlohmann::json();
  j["plmnId"] = o.m_PlmnId;
  if (o.ecRestrictionDataWbIsSet())
    j["ecRestrictionDataWb"] = o.m_EcRestrictionDataWb;
  if (o.ecRestrictionDataNbIsSet())
    j["ecRestrictionDataNb"] = o.m_EcRestrictionDataNb;
}

void from_json(const nlohmann::json& j, PlmnEcInfo& o) {
  j.at("plmnId").get_to(o.m_PlmnId);
  if (j.find("ecRestrictionDataWb") != j.end()) {
    j.at("ecRestrictionDataWb").get_to(o.m_EcRestrictionDataWb);
    o.m_EcRestrictionDataWbIsSet = true;
  }
  if (j.find("ecRestrictionDataNb") != j.end()) {
    j.at("ecRestrictionDataNb").get_to(o.m_EcRestrictionDataNb);
    o.m_EcRestrictionDataNbIsSet = true;
  }
}

oai::_3gpp::model::PlmnId PlmnEcInfo::getPlmnId() const {
  return m_PlmnId;
}
void PlmnEcInfo::setPlmnId(oai::_3gpp::model::PlmnId const& value) {
  m_PlmnId = value;
}
oai::_3gpp::model::EcRestrictionDataWb PlmnEcInfo::getEcRestrictionDataWb()
    const {
  return m_EcRestrictionDataWb;
}
void PlmnEcInfo::setEcRestrictionDataWb(
    oai::_3gpp::model::EcRestrictionDataWb const& value) {
  m_EcRestrictionDataWb      = value;
  m_EcRestrictionDataWbIsSet = true;
}
bool PlmnEcInfo::ecRestrictionDataWbIsSet() const {
  return m_EcRestrictionDataWbIsSet;
}
void PlmnEcInfo::unsetEcRestrictionDataWb() {
  m_EcRestrictionDataWbIsSet = false;
}
bool PlmnEcInfo::isEcRestrictionDataNb() const {
  return m_EcRestrictionDataNb;
}
void PlmnEcInfo::setEcRestrictionDataNb(bool const value) {
  m_EcRestrictionDataNb      = value;
  m_EcRestrictionDataNbIsSet = true;
}
bool PlmnEcInfo::ecRestrictionDataNbIsSet() const {
  return m_EcRestrictionDataNbIsSet;
}
void PlmnEcInfo::unsetEcRestrictionDataNb() {
  m_EcRestrictionDataNbIsSet = false;
}

}  // namespace oai::_3gpp::model
