/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Point_allOf.h
 *
 *
 */

#ifndef Point_allOf_H_
#define Point_allOf_H_

#include "GeographicalCoordinates.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class Point_allOf {
 public:
  Point_allOf();
  virtual ~Point_allOf() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const Point_allOf& rhs) const;
  bool operator!=(const Point_allOf& rhs) const;

  /////////////////////////////////////////////
  /// Point_allOf members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::GeographicalCoordinates getPoint() const;
  void setPoint(oai::_3gpp::model::GeographicalCoordinates const& value);

  friend void to_json(nlohmann::json& j, const Point_allOf& o);
  friend void from_json(const nlohmann::json& j, Point_allOf& o);

 protected:
  oai::_3gpp::model::GeographicalCoordinates m_Point;
};

}  // namespace oai::_3gpp::model

#endif /* Point_allOf_H_ */
