/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PositioningMethodMdt.h
 *
 * The enumeration LoggingDurationMdt defines Logging Duration for MDT in the
 * trace. See 3GPP TS 32.422 for further description of the values. It shall
 * comply with the provisions defined in table 5.6.3.13-1.
 */

#ifndef PositioningMethodMdt_H_
#define PositioningMethodMdt_H_

#include "PositioningMethodMdt_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// The enumeration LoggingDurationMdt defines Logging Duration for MDT in the
/// trace. See 3GPP TS 32.422 for further description of the values. It shall
/// comply with the provisions defined in table 5.6.3.13-1.
/// </summary>
class PositioningMethodMdt {
 public:
  PositioningMethodMdt();
  virtual ~PositioningMethodMdt() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const PositioningMethodMdt& rhs) const;
  bool operator!=(const PositioningMethodMdt& rhs) const;

  /////////////////////////////////////////////
  /// PositioningMethodMdt members

  PositioningMethodMdt_anyOf getValue() const;
  void setValue(PositioningMethodMdt_anyOf value);
  PositioningMethodMdt_anyOf::ePositioningMethodMdt_anyOf getEnumValue() const;
  void setEnumValue(
      PositioningMethodMdt_anyOf::ePositioningMethodMdt_anyOf value);
  friend void to_json(nlohmann::json& j, const PositioningMethodMdt& o);
  friend void from_json(const nlohmann::json& j, PositioningMethodMdt& o);
  friend void to_json(nlohmann::json& j, const PositioningMethodMdt_anyOf& o);
  friend void from_json(const nlohmann::json& j, PositioningMethodMdt_anyOf& o);

 protected:
  PositioningMethodMdt_anyOf m_value;
};

}  // namespace oai::_3gpp::model

#endif /* PositioningMethodMdt_H_ */
