/**
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "QosFlowSetupItem.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

QosFlowSetupItem::QosFlowSetupItem() {
  m_Qfi                     = 0;
  m_Ebi                     = 0;
  m_EbiIsSet                = false;
  m_QosFlowDescriptionIsSet = false;
  m_QosFlowProfileIsSet     = false;
  m_AssociatedAnTypeIsSet   = false;
  m_DefaultQosRuleInd       = false;
  m_DefaultQosRuleIndIsSet  = false;
}

void QosFlowSetupItem::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool QosFlowSetupItem::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool QosFlowSetupItem::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "QosFlowSetupItem" : pathPrefix;

  /* Qfi */ {
    const int32_t& value               = m_Qfi;
    const std::string currentValuePath = _pathPrefix + ".qfi";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
    if (value > 63) {
      success = false;
      msg << currentValuePath << ": must be less than or equal to 63;";
    }
  }

  if (ebiIsSet()) {
    const int32_t& value               = m_Ebi;
    const std::string currentValuePath = _pathPrefix + ".ebi";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
    if (value > 15) {
      success = false;
      msg << currentValuePath << ": must be less than or equal to 15;";
    }
  }

  return success;
}

bool QosFlowSetupItem::operator==(const QosFlowSetupItem& rhs) const {
  return

      (getQfi() == rhs.getQfi()) &&

      (getQosRules() == rhs.getQosRules()) &&

      ((!ebiIsSet() && !rhs.ebiIsSet()) ||
       (ebiIsSet() && rhs.ebiIsSet() && getEbi() == rhs.getEbi())) &&

      ((!qosFlowDescriptionIsSet() && !rhs.qosFlowDescriptionIsSet()) ||
       (qosFlowDescriptionIsSet() && rhs.qosFlowDescriptionIsSet() &&
        getQosFlowDescription() == rhs.getQosFlowDescription())) &&

      ((!qosFlowProfileIsSet() && !rhs.qosFlowProfileIsSet()) ||
       (qosFlowProfileIsSet() && rhs.qosFlowProfileIsSet() &&
        getQosFlowProfile() == rhs.getQosFlowProfile())) &&

      ((!associatedAnTypeIsSet() && !rhs.associatedAnTypeIsSet()) ||
       (associatedAnTypeIsSet() && rhs.associatedAnTypeIsSet() &&
        getAssociatedAnType() == rhs.getAssociatedAnType())) &&

      ((!defaultQosRuleIndIsSet() && !rhs.defaultQosRuleIndIsSet()) ||
       (defaultQosRuleIndIsSet() && rhs.defaultQosRuleIndIsSet() &&
        isDefaultQosRuleInd() == rhs.isDefaultQosRuleInd()))

          ;
}

bool QosFlowSetupItem::operator!=(const QosFlowSetupItem& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const QosFlowSetupItem& o) {
  j             = nlohmann::json();
  j["qfi"]      = o.m_Qfi;
  j["qosRules"] = o.m_QosRules;
  if (o.ebiIsSet()) j["ebi"] = o.m_Ebi;
  if (o.qosFlowDescriptionIsSet())
    j["qosFlowDescription"] = o.m_QosFlowDescription;
  if (o.qosFlowProfileIsSet()) j["qosFlowProfile"] = o.m_QosFlowProfile;
  if (o.associatedAnTypeIsSet()) j["associatedAnType"] = o.m_AssociatedAnType;
  if (o.defaultQosRuleIndIsSet())
    j["defaultQosRuleInd"] = o.m_DefaultQosRuleInd;
}

void from_json(const nlohmann::json& j, QosFlowSetupItem& o) {
  j.at("qfi").get_to(o.m_Qfi);
  j.at("qosRules").get_to(o.m_QosRules);
  if (j.find("ebi") != j.end()) {
    j.at("ebi").get_to(o.m_Ebi);
    o.m_EbiIsSet = true;
  }
  if (j.find("qosFlowDescription") != j.end()) {
    j.at("qosFlowDescription").get_to(o.m_QosFlowDescription);
    o.m_QosFlowDescriptionIsSet = true;
  }
  if (j.find("qosFlowProfile") != j.end()) {
    j.at("qosFlowProfile").get_to(o.m_QosFlowProfile);
    o.m_QosFlowProfileIsSet = true;
  }
  if (j.find("associatedAnType") != j.end()) {
    j.at("associatedAnType").get_to(o.m_AssociatedAnType);
    o.m_AssociatedAnTypeIsSet = true;
  }
  if (j.find("defaultQosRuleInd") != j.end()) {
    j.at("defaultQosRuleInd").get_to(o.m_DefaultQosRuleInd);
    o.m_DefaultQosRuleIndIsSet = true;
  }
}

int32_t QosFlowSetupItem::getQfi() const {
  return m_Qfi;
}
void QosFlowSetupItem::setQfi(int32_t const value) {
  m_Qfi = value;
}
std::string QosFlowSetupItem::getQosRules() const {
  return m_QosRules;
}
void QosFlowSetupItem::setQosRules(std::string const& value) {
  m_QosRules = value;
}
int32_t QosFlowSetupItem::getEbi() const {
  return m_Ebi;
}
void QosFlowSetupItem::setEbi(int32_t const value) {
  m_Ebi      = value;
  m_EbiIsSet = true;
}
bool QosFlowSetupItem::ebiIsSet() const {
  return m_EbiIsSet;
}
void QosFlowSetupItem::unsetEbi() {
  m_EbiIsSet = false;
}
std::string QosFlowSetupItem::getQosFlowDescription() const {
  return m_QosFlowDescription;
}
void QosFlowSetupItem::setQosFlowDescription(std::string const& value) {
  m_QosFlowDescription      = value;
  m_QosFlowDescriptionIsSet = true;
}
bool QosFlowSetupItem::qosFlowDescriptionIsSet() const {
  return m_QosFlowDescriptionIsSet;
}
void QosFlowSetupItem::unsetQosFlowDescription() {
  m_QosFlowDescriptionIsSet = false;
}
oai::_3gpp::model::QosFlowProfile QosFlowSetupItem::getQosFlowProfile() const {
  return m_QosFlowProfile;
}
void QosFlowSetupItem::setQosFlowProfile(
    oai::_3gpp::model::QosFlowProfile const& value) {
  m_QosFlowProfile      = value;
  m_QosFlowProfileIsSet = true;
}
bool QosFlowSetupItem::qosFlowProfileIsSet() const {
  return m_QosFlowProfileIsSet;
}
void QosFlowSetupItem::unsetQosFlowProfile() {
  m_QosFlowProfileIsSet = false;
}
oai::_3gpp::model::QosFlowAccessType QosFlowSetupItem::getAssociatedAnType()
    const {
  return m_AssociatedAnType;
}
void QosFlowSetupItem::setAssociatedAnType(
    oai::_3gpp::model::QosFlowAccessType const& value) {
  m_AssociatedAnType      = value;
  m_AssociatedAnTypeIsSet = true;
}
bool QosFlowSetupItem::associatedAnTypeIsSet() const {
  return m_AssociatedAnTypeIsSet;
}
void QosFlowSetupItem::unsetAssociatedAnType() {
  m_AssociatedAnTypeIsSet = false;
}
bool QosFlowSetupItem::isDefaultQosRuleInd() const {
  return m_DefaultQosRuleInd;
}
void QosFlowSetupItem::setDefaultQosRuleInd(bool const value) {
  m_DefaultQosRuleInd      = value;
  m_DefaultQosRuleIndIsSet = true;
}
bool QosFlowSetupItem::defaultQosRuleIndIsSet() const {
  return m_DefaultQosRuleIndIsSet;
}
void QosFlowSetupItem::unsetDefaultQosRuleInd() {
  m_DefaultQosRuleIndIsSet = false;
}

}  // namespace oai::_3gpp::model
