/**
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ResourceStatus.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

ResourceStatus::ResourceStatus() {}

void ResourceStatus::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool ResourceStatus::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ResourceStatus::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ResourceStatus" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool ResourceStatus::operator==(const ResourceStatus& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool ResourceStatus::operator!=(const ResourceStatus& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ResourceStatus& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, ResourceStatus& o) {
  from_json(j, o.m_value);
}

ResourceStatus_anyOf ResourceStatus::getValue() const {
  return m_value;
}

void ResourceStatus::setValue(ResourceStatus_anyOf value) {
  m_value = value;
}

ResourceStatus_anyOf::eResourceStatus_anyOf ResourceStatus::getEnumValue()
    const {
  return m_value.getValue();
}

void ResourceStatus::setEnumValue(
    ResourceStatus_anyOf::eResourceStatus_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::_3gpp::model
