/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces.   © 2024, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SecondaryRatUsageInfo.h
 *
 * Secondary RAT Usage Information to report usage data for a secondary RAT for
 * QoS flows and/or the whole PDU session.
 */

#ifndef SecondaryRatUsageInfo_H_
#define SecondaryRatUsageInfo_H_

#include "VolumeTimedReport.h"
#include "QosFlowUsageReport.h"
#include "RatType.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Secondary RAT Usage Information to report usage data for a secondary RAT for
/// QoS flows and/or the whole PDU session.
/// </summary>
class SecondaryRatUsageInfo {
 public:
  SecondaryRatUsageInfo();
  virtual ~SecondaryRatUsageInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SecondaryRatUsageInfo& rhs) const;
  bool operator!=(const SecondaryRatUsageInfo& rhs) const;

  /////////////////////////////////////////////
  /// SecondaryRatUsageInfo members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::RatType getSecondaryRatType() const;
  void setSecondaryRatType(oai::_3gpp::model::RatType const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::QosFlowUsageReport> getQosFlowsUsageData()
      const;
  void setQosFlowsUsageData(
      std::vector<oai::_3gpp::model::QosFlowUsageReport> const& value);
  bool qosFlowsUsageDataIsSet() const;
  void unsetQosFlowsUsageData();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::VolumeTimedReport> getPduSessionUsageData()
      const;
  void setPduSessionUsageData(
      std::vector<oai::_3gpp::model::VolumeTimedReport> const& value);
  bool pduSessionUsageDataIsSet() const;
  void unsetPduSessionUsageData();

  friend void to_json(nlohmann::json& j, const SecondaryRatUsageInfo& o);
  friend void from_json(const nlohmann::json& j, SecondaryRatUsageInfo& o);

 protected:
  oai::_3gpp::model::RatType m_SecondaryRatType;

  std::vector<oai::_3gpp::model::QosFlowUsageReport> m_QosFlowsUsageData;
  bool m_QosFlowsUsageDataIsSet;
  std::vector<oai::_3gpp::model::VolumeTimedReport> m_PduSessionUsageData;
  bool m_PduSessionUsageDataIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* SecondaryRatUsageInfo_H_ */
