/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SipForkingIndication.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

SipForkingIndication::SipForkingIndication() {}

void SipForkingIndication::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool SipForkingIndication::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SipForkingIndication::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SipForkingIndication" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool SipForkingIndication::operator==(const SipForkingIndication& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool SipForkingIndication::operator!=(const SipForkingIndication& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SipForkingIndication& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, SipForkingIndication& o) {
  from_json(j, o.m_value);
}

SipForkingIndication_anyOf SipForkingIndication::getValue() const {
  return m_value;
}

void SipForkingIndication::setValue(SipForkingIndication_anyOf value) {
  m_value = value;
}

SipForkingIndication_anyOf::eSipForkingIndication_anyOf
SipForkingIndication::getEnumValue() const {
  return m_value.getValue();
}

void SipForkingIndication::setEnumValue(
    SipForkingIndication_anyOf::eSipForkingIndication_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::_3gpp::model
