/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SmcceInfo.h
 *
 * Represents the Session Management congestion control experience information.
 */

#ifndef SmcceInfo_H_
#define SmcceInfo_H_

#include "SmcceUeList.h"
#include <string>
#include "Snssai.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Represents the Session Management congestion control experience information.
/// </summary>
class SmcceInfo {
 public:
  SmcceInfo();
  virtual ~SmcceInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SmcceInfo& rhs) const;
  bool operator!=(const SmcceInfo& rhs) const;

  /////////////////////////////////////////////
  /// SmcceInfo members

  /// <summary>
  /// String representing a Data Network as defined in clause 9A of 3GPP
  /// TS 23.003;  it shall contain either a DNN Network Identifier, or a full
  /// DNN with both the Network  Identifier and Operator Identifier, as
  /// specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as
  /// string in which the labels are separated by dots  (e.g.
  /// \&quot;Label1.Label2.Label3\&quot;).
  /// </summary>
  std::string getDnn() const;
  void setDnn(std::string const& value);
  bool dnnIsSet() const;
  void unsetDnn();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::Snssai getSnssai() const;
  void setSnssai(oai::_3gpp::model::Snssai const& value);
  bool snssaiIsSet() const;
  void unsetSnssai();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::SmcceUeList getSmcceUeList() const;
  void setSmcceUeList(oai::_3gpp::model::SmcceUeList const& value);

  friend void to_json(nlohmann::json& j, const SmcceInfo& o);
  friend void from_json(const nlohmann::json& j, SmcceInfo& o);

 protected:
  std::string m_Dnn;
  bool m_DnnIsSet;
  oai::_3gpp::model::Snssai m_Snssai;
  bool m_SnssaiIsSet;
  oai::_3gpp::model::SmcceUeList m_SmcceUeList;
};

}  // namespace oai::_3gpp::model

#endif /* SmcceInfo_H_ */
