/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SmcceUeList.h
 *
 * Represents the List of UEs classified based on experience level of Session
 * Management  congestion control.
 */

#ifndef SmcceUeList_H_
#define SmcceUeList_H_

#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Represents the List of UEs classified based on experience level of Session
/// Management  congestion control.
/// </summary>
class SmcceUeList {
 public:
  SmcceUeList();
  virtual ~SmcceUeList() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SmcceUeList& rhs) const;
  bool operator!=(const SmcceUeList& rhs) const;

  /////////////////////////////////////////////
  /// SmcceUeList members

  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getHighLevel() const;
  void setHighLevel(std::vector<std::string> const& value);
  bool highLevelIsSet() const;
  void unsetHighLevel();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getMediumLevel() const;
  void setMediumLevel(std::vector<std::string> const& value);
  bool mediumLevelIsSet() const;
  void unsetMediumLevel();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getLowLevel() const;
  void setLowLevel(std::vector<std::string> const& value);
  bool lowLevelIsSet() const;
  void unsetLowLevel();

  friend void to_json(nlohmann::json& j, const SmcceUeList& o);
  friend void from_json(const nlohmann::json& j, SmcceUeList& o);

 protected:
  std::vector<std::string> m_HighLevel;
  bool m_HighLevelIsSet;
  std::vector<std::string> m_MediumLevel;
  bool m_MediumLevelIsSet;
  std::vector<std::string> m_LowLevel;
  bool m_LowLevelIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* SmcceUeList_H_ */
