/**
 * Nsmf_EventExposure
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SmNasFromSmf.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

SmNasFromSmf::SmNasFromSmf() {
  m_SmNasType    = "";
  m_TimeStamp    = "";
  m_BackoffTimer = 0;
}

void SmNasFromSmf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool SmNasFromSmf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SmNasFromSmf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SmNasFromSmf" : pathPrefix;

  return success;
}

bool SmNasFromSmf::operator==(const SmNasFromSmf& rhs) const {
  return

      (getSmNasType() == rhs.getSmNasType()) &&

      (getTimeStamp() == rhs.getTimeStamp()) &&

      (getBackoffTimer() == rhs.getBackoffTimer()) &&

      (getAppliedSmccType() == rhs.getAppliedSmccType())

          ;
}

bool SmNasFromSmf::operator!=(const SmNasFromSmf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SmNasFromSmf& o) {
  j                    = nlohmann::json();
  j["smNasType"]       = o.m_SmNasType;
  j["timeStamp"]       = o.m_TimeStamp;
  j["backoffTimer"]    = o.m_BackoffTimer;
  j["appliedSmccType"] = o.m_AppliedSmccType;
}

void from_json(const nlohmann::json& j, SmNasFromSmf& o) {
  j.at("smNasType").get_to(o.m_SmNasType);
  j.at("timeStamp").get_to(o.m_TimeStamp);
  j.at("backoffTimer").get_to(o.m_BackoffTimer);
  j.at("appliedSmccType").get_to(o.m_AppliedSmccType);
}

std::string SmNasFromSmf::getSmNasType() const {
  return m_SmNasType;
}
void SmNasFromSmf::setSmNasType(std::string const& value) {
  m_SmNasType = value;
}
std::string SmNasFromSmf::getTimeStamp() const {
  return m_TimeStamp;
}
void SmNasFromSmf::setTimeStamp(std::string const& value) {
  m_TimeStamp = value;
}
int32_t SmNasFromSmf::getBackoffTimer() const {
  return m_BackoffTimer;
}
void SmNasFromSmf::setBackoffTimer(int32_t const value) {
  m_BackoffTimer = value;
}
oai::_3gpp::model::AppliedSmccType SmNasFromSmf::getAppliedSmccType() const {
  return m_AppliedSmccType;
}
void SmNasFromSmf::setAppliedSmccType(
    oai::_3gpp::model::AppliedSmccType const& value) {
  m_AppliedSmccType = value;
}

}  // namespace oai::_3gpp::model
