/**
 * NRF NFManagement Service
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SnssaiMbSmfInfoItem.h
 *
 * Parameters supported by an MB-SMF for a given S-NSSAI
 */

#ifndef SnssaiMbSmfInfoItem_H_
#define SnssaiMbSmfInfoItem_H_

#include "ExtSnssai.h"
#include "DnnMbSmfInfoItem.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Parameters supported by an MB-SMF for a given S-NSSAI
/// </summary>
class SnssaiMbSmfInfoItem {
 public:
  SnssaiMbSmfInfoItem();
  virtual ~SnssaiMbSmfInfoItem() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SnssaiMbSmfInfoItem& rhs) const;
  bool operator!=(const SnssaiMbSmfInfoItem& rhs) const;

  /////////////////////////////////////////////
  /// SnssaiMbSmfInfoItem members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::ExtSnssai getSNssai() const;
  void setSNssai(oai::_3gpp::model::ExtSnssai const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::DnnMbSmfInfoItem> getDnnInfoList() const;
  void setDnnInfoList(
      std::vector<oai::_3gpp::model::DnnMbSmfInfoItem> const& value);

  friend void to_json(nlohmann::json& j, const SnssaiMbSmfInfoItem& o);
  friend void from_json(const nlohmann::json& j, SnssaiMbSmfInfoItem& o);

 protected:
  oai::_3gpp::model::ExtSnssai m_SNssai;

  std::vector<oai::_3gpp::model::DnnMbSmfInfoItem> m_DnnInfoList;
};

}  // namespace oai::_3gpp::model

#endif /* SnssaiMbSmfInfoItem_H_ */
