/**
 * Nausf_SoRProtection Service
 * AUSF SoR Protection Service.   © 2022, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SteeringContainer.h
 *
 * Contains the information sent to UE.
 */

#ifndef SteeringContainer_H_
#define SteeringContainer_H_

#include "SteeringInfo.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Contains the information sent to UE.
/// </summary>
class SteeringContainer {
 public:
  SteeringContainer();
  virtual ~SteeringContainer() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SteeringContainer& rhs) const;
  bool operator!=(const SteeringContainer& rhs) const;

  /////////////////////////////////////////////
  /// SteeringContainer members

  friend void to_json(nlohmann::json& j, const SteeringContainer& o);
  friend void from_json(const nlohmann::json& j, SteeringContainer& o);

 protected:
};

}  // namespace oai::_3gpp::model

#endif /* SteeringContainer_H_ */
