/**
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TransferMtDataAddInfo.h
 *
 * Transfer MT Data Error Response Additional Information
 */

#ifndef TransferMtDataAddInfo_H_
#define TransferMtDataAddInfo_H_

#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Transfer MT Data Error Response Additional Information
/// </summary>
class TransferMtDataAddInfo {
 public:
  TransferMtDataAddInfo();
  virtual ~TransferMtDataAddInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const TransferMtDataAddInfo& rhs) const;
  bool operator!=(const TransferMtDataAddInfo& rhs) const;

  /////////////////////////////////////////////
  /// TransferMtDataAddInfo members

  /// <summary>
  /// indicating a time in seconds.
  /// </summary>
  int32_t getMaxWaitingTime() const;
  void setMaxWaitingTime(int32_t const value);
  bool maxWaitingTimeIsSet() const;
  void unsetMaxWaitingTime();

  friend void to_json(nlohmann::json& j, const TransferMtDataAddInfo& o);
  friend void from_json(const nlohmann::json& j, TransferMtDataAddInfo& o);

 protected:
  int32_t m_MaxWaitingTime;
  bool m_MaxWaitingTimeIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* TransferMtDataAddInfo_H_ */
