/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UeType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

UeType::UeType() {}

void UeType::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool UeType::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool UeType::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "UeType" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool UeType::operator==(const UeType& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool UeType::operator!=(const UeType& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UeType& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, UeType& o) {
  from_json(j, o.m_value);
}

UeType_anyOf UeType::getValue() const {
  return m_value;
}

void UeType::setValue(UeType_anyOf value) {
  m_value = value;
}

UeType_anyOf::eUeType_anyOf UeType::getEnumValue() const {
  return m_value.getValue();
}

void UeType::setEnumValue(UeType_anyOf::eUeType_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::_3gpp::model
