/**
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UpCnxState.h
 *
 * User Plane Connection State. Possible values are - ACTIVATED - DEACTIVATED -
 * ACTIVATING - SUSPENDED
 */

#ifndef UpCnxState_H_
#define UpCnxState_H_

#include "UpCnxState_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// User Plane Connection State. Possible values are - ACTIVATED - DEACTIVATED -
/// ACTIVATING - SUSPENDED
/// </summary>
class UpCnxState {
 public:
  UpCnxState();
  virtual ~UpCnxState() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const UpCnxState& rhs) const;
  bool operator!=(const UpCnxState& rhs) const;

  /////////////////////////////////////////////
  /// UpCnxState members

  UpCnxState_anyOf getValue() const;
  void setValue(UpCnxState_anyOf value);
  UpCnxState_anyOf::eUpCnxState_anyOf getEnumValue() const;
  void setEnumValue(UpCnxState_anyOf::eUpCnxState_anyOf value);
  friend void to_json(nlohmann::json& j, const UpCnxState& o);
  friend void from_json(const nlohmann::json& j, UpCnxState& o);
  friend void to_json(nlohmann::json& j, const UpCnxState_anyOf& o);
  friend void from_json(const nlohmann::json& j, UpCnxState_anyOf& o);

 protected:
  UpCnxState_anyOf m_value;
};

}  // namespace oai::_3gpp::model

#endif /* UpCnxState_H_ */
