/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UsageMonLevel.h
 *
 * Represents the usage monitoring level.
 */

#ifndef UsageMonLevel_H_
#define UsageMonLevel_H_

#include "UsageMonLevel_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Represents the usage monitoring level.
/// </summary>
class UsageMonLevel {
 public:
  UsageMonLevel();
  virtual ~UsageMonLevel() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const UsageMonLevel& rhs) const;
  bool operator!=(const UsageMonLevel& rhs) const;

  /////////////////////////////////////////////
  /// UsageMonLevel members

  UsageMonLevel_anyOf getValue() const;
  void setValue(UsageMonLevel_anyOf value);
  UsageMonLevel_anyOf::eUsageMonLevel_anyOf getEnumValue() const;
  void setEnumValue(UsageMonLevel_anyOf::eUsageMonLevel_anyOf value);
  friend void to_json(nlohmann::json& j, const UsageMonLevel& o);
  friend void from_json(const nlohmann::json& j, UsageMonLevel& o);
  friend void to_json(nlohmann::json& j, const UsageMonLevel_anyOf& o);
  friend void from_json(const nlohmann::json& j, UsageMonLevel_anyOf& o);

 protected:
  UsageMonLevel_anyOf m_value;
};

}  // namespace oai::_3gpp::model

#endif /* UsageMonLevel_H_ */
