/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * WlanPerformanceReq.h
 *
 * Represents other WLAN performance analytics requirements.
 */

#ifndef WlanPerformanceReq_H_
#define WlanPerformanceReq_H_

#include <string>
#include <vector>
#include "MatchingDirection.h"
#include "WlanOrderingCriterion.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Represents other WLAN performance analytics requirements.
/// </summary>
class WlanPerformanceReq {
 public:
  WlanPerformanceReq();
  virtual ~WlanPerformanceReq() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const WlanPerformanceReq& rhs) const;
  bool operator!=(const WlanPerformanceReq& rhs) const;

  /////////////////////////////////////////////
  /// WlanPerformanceReq members

  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getSsIds() const;
  void setSsIds(std::vector<std::string> const& value);
  bool ssIdsIsSet() const;
  void unsetSsIds();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getBssIds() const;
  void setBssIds(std::vector<std::string> const& value);
  bool bssIdsIsSet() const;
  void unsetBssIds();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::WlanOrderingCriterion getWlanOrderCriter() const;
  void setWlanOrderCriter(
      oai::_3gpp::model::WlanOrderingCriterion const& value);
  bool wlanOrderCriterIsSet() const;
  void unsetWlanOrderCriter();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::MatchingDirection getOrder() const;
  void setOrder(oai::_3gpp::model::MatchingDirection const& value);
  bool orderIsSet() const;
  void unsetOrder();

  friend void to_json(nlohmann::json& j, const WlanPerformanceReq& o);
  friend void from_json(const nlohmann::json& j, WlanPerformanceReq& o);

 protected:
  std::vector<std::string> m_SsIds;
  bool m_SsIdsIsSet;
  std::vector<std::string> m_BssIds;
  bool m_BssIdsIsSet;
  oai::_3gpp::model::WlanOrderingCriterion m_WlanOrderCriter;
  bool m_WlanOrderCriterIsSet;
  oai::_3gpp::model::MatchingDirection m_Order;
  bool m_OrderIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* WlanPerformanceReq_H_ */
