/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NonUEN2MessagesSubscriptionsCollectionDocumentApiImpl.h"

extern itti_mw* itti_inst;
namespace oai {
namespace amf {
namespace api {

using namespace oai::_3gpp::model;

NonUEN2MessagesSubscriptionsCollectionDocumentApiImpl::
    NonUEN2MessagesSubscriptionsCollectionDocumentApiImpl(
        std::shared_ptr<Pistache::Rest::Router> rtr,
        amf_application::amf_app* amf_app_inst)
    : NonUEN2MessagesSubscriptionsCollectionDocumentApi(rtr),
      m_amf_app(amf_app_inst) {}

void NonUEN2MessagesSubscriptionsCollectionDocumentApiImpl::
    non_ue_n2_info_subscribe(
        const NonUeN2InfoSubscriptionCreateData&
            nonUeN2InfoSubscriptionCreateData,
        Pistache::Http::ResponseWriter& response) {
  Logger::amf_server().debug("Receive NonUeN2InfoSubscribe, handling...");
  // Generate a promise and associate this promise to the ITTI message
  uint32_t promise_id = m_amf_app->generate_promise_id();
  Logger::amf_n1().debug("Promise ID generated %d", promise_id);

  boost::shared_ptr<boost::promise<nlohmann::json>> p =
      boost::make_shared<boost::promise<nlohmann::json>>();
  boost::shared_future<nlohmann::json> f = p->get_future();
  m_amf_app->add_promise(promise_id, p);

  // Handle the NonUeN2InfoSubscribe in amf_app
  std::shared_ptr<itti_sbi_non_ue_n2_info_subscribe> itti_msg =
      std::make_shared<itti_sbi_non_ue_n2_info_subscribe>(
          TASK_AMF_SBI, TASK_AMF_APP, promise_id);

  itti_msg->subscription_data = nonUeN2InfoSubscriptionCreateData;
  itti_msg->promise_id        = promise_id;

  int ret = itti_inst->send_msg(itti_msg);
  if (0 != ret) {
    Logger::amf_server().error(
        "Could not send ITTI message %s to task TASK_AMF_APP",
        itti_msg->get_msg_name());
  }

  // Wait for the result available and process accordingly
  std::optional<nlohmann::json> result_opt = std::nullopt;
  oai::utils::utils::wait_for_result(f, result_opt);

  if (result_opt.has_value()) {
    Logger::amf_server().debug("Got result for promise ID %d", promise_id);
    nlohmann::json result = result_opt.value();
    // process data
    std::string location        = {};
    uint32_t http_response_code = 0;
    if (result.find(kSbiResponseHeaderLocation) != result.end()) {
      location = result[kSbiResponseHeaderLocation].get<std::string>();
    }

    if (result.find(kSbiResponseHttpResponseCode) != result.end()) {
      http_response_code = result[kSbiResponseHttpResponseCode].get<int>();
    }

    // NonUeN2InfoSubscriptionCreatedData
    nlohmann::json json_data = {};
    if (result.find(kSbiResponseJsonData) != result.end()) {
      json_data = result[kSbiResponseJsonData];
    }

    if (http_response_code == oai::common::sbi::http_status_code::CREATED) {
      response.headers().add<Pistache::Http::Header::Location>(
          location);  // Location header
      response.headers().add<Pistache::Http::Header::ContentType>(
          Pistache::Http::Mime::MediaType("application/json"));
      response.send(Pistache::Http::Code::Created, json_data.dump().c_str());

    } else {
      response.send(Pistache::Http::Code(http_response_code));
    }
  } else {
    response.send(Pistache::Http::Code::Gateway_Timeout);
  }
}

}  // namespace api
}  // namespace amf
}  // namespace oai
