osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_booter1 && ./start.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper1 && ./start.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper2 && ./start.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper3 && ./start.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper4 && ./start.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper5 && ./start.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper6 && ./start.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper7 && ./start.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper8 && ./start.sh; exec bash"'
sleep 20
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper1 && ./run_contract.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper2 && ./run_contract.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper3 && ./run_contract.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper4 && ./run_contract.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper5 && ./run_contract.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper6 && ./run_contract.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper7 && ./run_contract.sh; exec bash"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper8 && ./run_contract.sh; exec bash"'
