/**
* Npcf_PolicyAuthorization Service API
* PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.3.0-alpha.6
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "MediaTransportProto.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::pcf
{

MediaTransportProto::MediaTransportProto()
{
    
}

void MediaTransportProto::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw oai::model::common::helpers::ValidationException(msg.str());
    }
}

bool MediaTransportProto::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool MediaTransportProto::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "MediaTransportProto" : pathPrefix;

    
    return success;
}

bool MediaTransportProto::operator==(const MediaTransportProto& rhs) const
{
    return
    
    
    ;
}

bool MediaTransportProto::operator!=(const MediaTransportProto& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const MediaTransportProto& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, MediaTransportProto& o)
{
    
}



} // namespace oai::model::pcf

