/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PduSessionTsnBridge.h
 *
 * Contains the new TSC user plane node information and may contain the DS-TT
 * port and/or NW-TT port management information.
 */

#ifndef PduSessionTsnBridge_H_
#define PduSessionTsnBridge_H_

#include <string>
#include "Ipv6Prefix.h"
#include "PortManagementContainer.h"
#include "TsnBridgeInfo.h"
#include "BridgeManagementContainer.h"
#include "Snssai.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::model::pcf {

/// <summary>
/// Contains the new TSC user plane node information and may contain the DS-TT
/// port and/or NW-TT port management information.
/// </summary>
class PduSessionTsnBridge {
 public:
  PduSessionTsnBridge();
  virtual ~PduSessionTsnBridge() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const PduSessionTsnBridge& rhs) const;
  bool operator!=(const PduSessionTsnBridge& rhs) const;

  /////////////////////////////////////////////
  /// PduSessionTsnBridge members

  /// <summary>
  ///
  /// </summary>
  oai::model::pcf::TsnBridgeInfo getTsnBridgeInfo() const;
  void setTsnBridgeInfo(oai::model::pcf::TsnBridgeInfo const& value);
  /// <summary>
  ///
  /// </summary>
  oai::model::pcf::BridgeManagementContainer getTsnBridgeManCont() const;
  void setTsnBridgeManCont(
      oai::model::pcf::BridgeManagementContainer const& value);
  bool tsnBridgeManContIsSet() const;
  void unsetTsnBridgeManCont();
  /// <summary>
  ///
  /// </summary>
  oai::model::pcf::PortManagementContainer getTsnPortManContDstt() const;
  void setTsnPortManContDstt(
      oai::model::pcf::PortManagementContainer const& value);
  bool tsnPortManContDsttIsSet() const;
  void unsetTsnPortManContDstt();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::model::pcf::PortManagementContainer> getTsnPortManContNwtts()
      const;
  void setTsnPortManContNwtts(
      std::vector<oai::model::pcf::PortManagementContainer> const& value);
  bool tsnPortManContNwttsIsSet() const;
  void unsetTsnPortManContNwtts();
  /// <summary>
  /// String identifying a IPv4 address formatted in the &#39;dotted
  /// decimal&#39; notation as defined in RFC 1166.
  /// </summary>
  std::string getUeIpv4Addr() const;
  void setUeIpv4Addr(std::string const& value);
  bool ueIpv4AddrIsSet() const;
  void unsetUeIpv4Addr();
  /// <summary>
  /// String representing a Data Network as defined in clause 9A of 3GPP
  /// TS 23.003;  it shall contain either a DNN Network Identifier, or a full
  /// DNN with both the Network  Identifier and Operator Identifier, as
  /// specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as
  /// string in which the labels are separated by dots  (e.g.
  /// \&quot;Label1.Label2.Label3\&quot;).
  /// </summary>
  std::string getDnn() const;
  void setDnn(std::string const& value);
  bool dnnIsSet() const;
  void unsetDnn();
  /// <summary>
  ///
  /// </summary>
  oai::model::common::Snssai getSnssai() const;
  void setSnssai(oai::model::common::Snssai const& value);
  bool snssaiIsSet() const;
  void unsetSnssai();
  /// <summary>
  /// IPv4 address domain identifier.
  /// </summary>
  std::string getIpDomain() const;
  void setIpDomain(std::string const& value);
  bool ipDomainIsSet() const;
  void unsetIpDomain();
  /// <summary>
  ///
  /// </summary>
  oai::model::pcf::Ipv6Prefix getUeIpv6AddrPrefix() const;
  void setUeIpv6AddrPrefix(oai::model::pcf::Ipv6Prefix const& value);
  bool ueIpv6AddrPrefixIsSet() const;
  void unsetUeIpv6AddrPrefix();

  friend void to_json(nlohmann::json& j, const PduSessionTsnBridge& o);
  friend void from_json(const nlohmann::json& j, PduSessionTsnBridge& o);

 protected:
  oai::model::pcf::TsnBridgeInfo m_TsnBridgeInfo;

  oai::model::pcf::BridgeManagementContainer m_TsnBridgeManCont;
  bool m_TsnBridgeManContIsSet;
  oai::model::pcf::PortManagementContainer m_TsnPortManContDstt;
  bool m_TsnPortManContDsttIsSet;
  std::vector<oai::model::pcf::PortManagementContainer> m_TsnPortManContNwtts;
  bool m_TsnPortManContNwttsIsSet;
  std::string m_UeIpv4Addr;
  bool m_UeIpv4AddrIsSet;
  std::string m_Dnn;
  bool m_DnnIsSet;
  oai::model::common::Snssai m_Snssai;
  bool m_SnssaiIsSet;
  std::string m_IpDomain;
  bool m_IpDomainIsSet;
  oai::model::pcf::Ipv6Prefix m_UeIpv6AddrPrefix;
  bool m_UeIpv6AddrPrefixIsSet;
};

}  // namespace oai::model::pcf

#endif /* PduSessionTsnBridge_H_ */
