/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ProtocolDescription.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::pcf {

ProtocolDescription::ProtocolDescription() {
  m_TransportProtoIsSet     = false;
  m_RtpHeaderExtInfoIsSet   = false;
  m_RtpPayloadInfoListIsSet = false;
}

void ProtocolDescription::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool ProtocolDescription::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ProtocolDescription::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ProtocolDescription" : pathPrefix;

  if (rtpPayloadInfoListIsSet()) {
    const std::vector<oai::model::pcf::RtpPayloadInfo>& value =
        m_RtpPayloadInfoList;
    const std::string currentValuePath = _pathPrefix + ".rtpPayloadInfoList";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::model::pcf::RtpPayloadInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".rtpPayloadInfoList") &&
            success;

        i++;
      }
    }
  }

  return success;
}

bool ProtocolDescription::operator==(const ProtocolDescription& rhs) const {
  return

      ((!transportProtoIsSet() && !rhs.transportProtoIsSet()) ||
       (transportProtoIsSet() && rhs.transportProtoIsSet() &&
        getTransportProto() == rhs.getTransportProto())) &&

      ((!rtpHeaderExtInfoIsSet() && !rhs.rtpHeaderExtInfoIsSet()) ||
       (rtpHeaderExtInfoIsSet() && rhs.rtpHeaderExtInfoIsSet() &&
        getRtpHeaderExtInfo() == rhs.getRtpHeaderExtInfo())) &&

      ((!rtpPayloadInfoListIsSet() && !rhs.rtpPayloadInfoListIsSet()) ||
       (rtpPayloadInfoListIsSet() && rhs.rtpPayloadInfoListIsSet() &&
        getRtpPayloadInfoList() == rhs.getRtpPayloadInfoList()))

          ;
}

bool ProtocolDescription::operator!=(const ProtocolDescription& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ProtocolDescription& o) {
  j = nlohmann::json::object();
  if (o.transportProtoIsSet()) j["transportProto"] = o.m_TransportProto;
  if (o.rtpHeaderExtInfoIsSet()) j["rtpHeaderExtInfo"] = o.m_RtpHeaderExtInfo;
  if (o.rtpPayloadInfoListIsSet() || !o.m_RtpPayloadInfoList.empty())
    j["rtpPayloadInfoList"] = o.m_RtpPayloadInfoList;
}

void from_json(const nlohmann::json& j, ProtocolDescription& o) {
  if (j.find("transportProto") != j.end()) {
    j.at("transportProto").get_to(o.m_TransportProto);
    o.m_TransportProtoIsSet = true;
  }
  if (j.find("rtpHeaderExtInfo") != j.end()) {
    j.at("rtpHeaderExtInfo").get_to(o.m_RtpHeaderExtInfo);
    o.m_RtpHeaderExtInfoIsSet = true;
  }
  if (j.find("rtpPayloadInfoList") != j.end()) {
    j.at("rtpPayloadInfoList").get_to(o.m_RtpPayloadInfoList);
    o.m_RtpPayloadInfoListIsSet = true;
  }
}

oai::model::pcf::MediaTransportProto ProtocolDescription::getTransportProto()
    const {
  return m_TransportProto;
}
void ProtocolDescription::setTransportProto(
    oai::model::pcf::MediaTransportProto const& value) {
  m_TransportProto      = value;
  m_TransportProtoIsSet = true;
}
bool ProtocolDescription::transportProtoIsSet() const {
  return m_TransportProtoIsSet;
}
void ProtocolDescription::unsetTransportProto() {
  m_TransportProtoIsSet = false;
}
oai::model::pcf::RtpHeaderExtInfo ProtocolDescription::getRtpHeaderExtInfo()
    const {
  return m_RtpHeaderExtInfo;
}
void ProtocolDescription::setRtpHeaderExtInfo(
    oai::model::pcf::RtpHeaderExtInfo const& value) {
  m_RtpHeaderExtInfo      = value;
  m_RtpHeaderExtInfoIsSet = true;
}
bool ProtocolDescription::rtpHeaderExtInfoIsSet() const {
  return m_RtpHeaderExtInfoIsSet;
}
void ProtocolDescription::unsetRtpHeaderExtInfo() {
  m_RtpHeaderExtInfoIsSet = false;
}
std::vector<oai::model::pcf::RtpPayloadInfo>
ProtocolDescription::getRtpPayloadInfoList() const {
  return m_RtpPayloadInfoList;
}
void ProtocolDescription::setRtpPayloadInfoList(
    std::vector<oai::model::pcf::RtpPayloadInfo> const& value) {
  m_RtpPayloadInfoList      = value;
  m_RtpPayloadInfoListIsSet = true;
}
bool ProtocolDescription::rtpPayloadInfoListIsSet() const {
  return m_RtpPayloadInfoListIsSet;
}
void ProtocolDescription::unsetRtpPayloadInfoList() {
  m_RtpPayloadInfoListIsSet = false;
}

}  // namespace oai::model::pcf
