/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SpatialValidityRm.h
 *
 * This data type is defined in the same way as the SpatialValidity data type,
 * but with the OpenAPI nullable property set to true.
 */

#ifndef SpatialValidityRm_H_
#define SpatialValidityRm_H_

#include "PresenceInfo.h"
#include <map>
#include <nlohmann/json.hpp>

namespace oai::model::pcf {

/// <summary>
/// This data type is defined in the same way as the SpatialValidity data type,
/// but with the OpenAPI nullable property set to true.
/// </summary>
class SpatialValidityRm {
 public:
  SpatialValidityRm();
  virtual ~SpatialValidityRm() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SpatialValidityRm& rhs) const;
  bool operator!=(const SpatialValidityRm& rhs) const;

  /////////////////////////////////////////////
  /// SpatialValidityRm members

  /// <summary>
  /// Defines the presence information provisioned by the AF. The praId
  /// attribute within the  PresenceInfo data type is the key of the map.
  /// </summary>
  std::map<std::string, oai::model::common::PresenceInfo> getPresenceInfoList()
      const;
  void setPresenceInfoList(
      std::map<std::string, oai::model::common::PresenceInfo> const& value);

  friend void to_json(nlohmann::json& j, const SpatialValidityRm& o);
  friend void from_json(const nlohmann::json& j, SpatialValidityRm& o);

 protected:
  std::map<std::string, oai::model::common::PresenceInfo> m_PresenceInfoList;
};

}  // namespace oai::model::pcf

#endif /* SpatialValidityRm_H_ */
