osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_booter1 && ./stop.sh &"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper1 && ./stop.sh &"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper2 && ./stop.sh &"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper3 && ./stop.sh &"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper4 && ./stop.sh &"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper5 && ./stop.sh &"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper6 && ./stop.sh &"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper7 && ./stop.sh &"'
osascript -e 'tell application "Terminal" to do script "cd /Users/dengmingtao/Documents/GitHub/P3-Chain/dper/client/auto/dper_dper8 && ./stop.sh &"'
sleep 5
