/**
 * Nausf_SoRProtection Service
 * AUSF SoR Protection Service.   © 2022, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AccessTech_anyOf.h
 *
 *
 */

#ifndef AccessTech_anyOf_H_
#define AccessTech_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class AccessTech_anyOf {
 public:
  AccessTech_anyOf();
  virtual ~AccessTech_anyOf() = default;

  enum class eAccessTech_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    NR,
    EUTRAN_IN_WBS1_MODE_AND_NBS1_MODE,
    EUTRAN_IN_NBS1_MODE_ONLY,
    EUTRAN_IN_WBS1_MODE_ONLY,
    UTRAN,
    GSM_AND_ECGSM_IOT,
    GSM_WITHOUT_ECGSM_IOT,
    ECGSM_IOT_ONLY,
    CDMA_1XRTT,
    CDMA_HRPD,
    GSM_COMPACT
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const AccessTech_anyOf& rhs) const;
  bool operator!=(const AccessTech_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// AccessTech_anyOf members

  AccessTech_anyOf::eAccessTech_anyOf getValue() const;
  void setValue(AccessTech_anyOf::eAccessTech_anyOf value);

  friend void to_json(nlohmann::json& j, const AccessTech_anyOf& o);
  friend void from_json(const nlohmann::json& j, AccessTech_anyOf& o);

 protected:
  AccessTech_anyOf::eAccessTech_anyOf m_value =
      AccessTech_anyOf::eAccessTech_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::_3gpp::model

#endif /* AccessTech_anyOf_H_ */
