/**
 * LMF Location
 * LMF Location Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AlertLimit.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

AlertLimit::AlertLimit() {
  m_HorizontalProtectionLevel    = 0;
  m_VerticalProtectionLevel      = 0;
  m_VerticalProtectionLevelIsSet = false;
}

void AlertLimit::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool AlertLimit::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool AlertLimit::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "AlertLimit" : pathPrefix;

  /* HorizontalProtectionLevel */ {
    const int32_t& value = m_HorizontalProtectionLevel;
    const std::string currentValuePath =
        _pathPrefix + ".horizontalProtectionLevel";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
    if (value > 50000) {
      success = false;
      msg << currentValuePath << ": must be less than or equal to 50000;";
    }
  }

  if (verticalProtectionLevelIsSet()) {
    const int32_t& value = m_VerticalProtectionLevel;
    const std::string currentValuePath =
        _pathPrefix + ".verticalProtectionLevel";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
    if (value > 50000) {
      success = false;
      msg << currentValuePath << ": must be less than or equal to 50000;";
    }
  }

  return success;
}

bool AlertLimit::operator==(const AlertLimit& rhs) const {
  return

      (getHorizontalProtectionLevel() == rhs.getHorizontalProtectionLevel()) &&

      ((!verticalProtectionLevelIsSet() &&
        !rhs.verticalProtectionLevelIsSet()) ||
       (verticalProtectionLevelIsSet() && rhs.verticalProtectionLevelIsSet() &&
        getVerticalProtectionLevel() == rhs.getVerticalProtectionLevel()))

          ;
}

bool AlertLimit::operator!=(const AlertLimit& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AlertLimit& o) {
  j                              = nlohmann::json();
  j["horizontalProtectionLevel"] = o.m_HorizontalProtectionLevel;
  if (o.verticalProtectionLevelIsSet())
    j["verticalProtectionLevel"] = o.m_VerticalProtectionLevel;
}

void from_json(const nlohmann::json& j, AlertLimit& o) {
  j.at("horizontalProtectionLevel").get_to(o.m_HorizontalProtectionLevel);
  if (j.find("verticalProtectionLevel") != j.end()) {
    j.at("verticalProtectionLevel").get_to(o.m_VerticalProtectionLevel);
    o.m_VerticalProtectionLevelIsSet = true;
  }
}

int32_t AlertLimit::getHorizontalProtectionLevel() const {
  return m_HorizontalProtectionLevel;
}
void AlertLimit::setHorizontalProtectionLevel(int32_t const value) {
  m_HorizontalProtectionLevel = value;
}
int32_t AlertLimit::getVerticalProtectionLevel() const {
  return m_VerticalProtectionLevel;
}
void AlertLimit::setVerticalProtectionLevel(int32_t const value) {
  m_VerticalProtectionLevel      = value;
  m_VerticalProtectionLevelIsSet = true;
}
bool AlertLimit::verticalProtectionLevelIsSet() const {
  return m_VerticalProtectionLevelIsSet;
}
void AlertLimit::unsetVerticalProtectionLevel() {
  m_VerticalProtectionLevelIsSet = false;
}

}  // namespace oai::_3gpp::model
