/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Amf3GppAccessRegistration.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

Amf3GppAccessRegistration::Amf3GppAccessRegistration() {
  m_AmfInstanceId                    = "";
  m_SupportedFeatures                = "";
  m_SupportedFeaturesIsSet           = false;
  m_PurgeFlag                        = false;
  m_PurgeFlagIsSet                   = false;
  m_Pei                              = "";
  m_PeiIsSet                         = false;
  m_ImsVoPsIsSet                     = false;
  m_DeregCallbackUri                 = "";
  m_AmfServiceNameDeregIsSet         = false;
  m_PcscfRestorationCallbackUri      = "";
  m_PcscfRestorationCallbackUriIsSet = false;
  m_AmfServiceNamePcscfRestIsSet     = false;
  m_InitialRegistrationInd           = false;
  m_InitialRegistrationIndIsSet      = false;
  m_EmergencyRegistrationInd         = false;
  m_EmergencyRegistrationIndIsSet    = false;
  m_BackupAmfInfoIsSet               = false;
  m_DrFlag                           = false;
  m_DrFlagIsSet                      = false;
  m_UrrpIndicator                    = false;
  m_UrrpIndicatorIsSet               = false;
  m_AmfEeSubscriptionId              = "";
  m_AmfEeSubscriptionIdIsSet         = false;
  m_EpsInterworkingInfoIsSet         = false;
  m_UeSrvccCapability                = false;
  m_UeSrvccCapabilityIsSet           = false;
  m_RegistrationTime                 = "";
  m_RegistrationTimeIsSet            = false;
  m_VgmlcAddressIsSet                = false;
  m_ContextInfoIsSet                 = false;
  m_NoEeSubscriptionInd              = false;
  m_NoEeSubscriptionIndIsSet         = false;
  m_Supi                             = "";
  m_SupiIsSet                        = false;
  m_UeReachableIndIsSet              = false;
  m_ReRegistrationRequired           = false;
  m_ReRegistrationRequiredIsSet      = false;
  m_AdminDeregSubWithdrawn           = false;
  m_AdminDeregSubWithdrawnIsSet      = false;
  m_DataRestorationCallbackUri       = "";
  m_DataRestorationCallbackUriIsSet  = false;
  m_ResetIdsIsSet                    = false;
  m_DisasterRoamingInd               = false;
  m_DisasterRoamingIndIsSet          = false;
  m_UeMINTCapability                 = false;
  m_UeMINTCapabilityIsSet            = false;
  m_SorSnpnSiSupported               = false;
  m_SorSnpnSiSupportedIsSet          = false;
  m_UdrRestartInd                    = false;
  m_UdrRestartIndIsSet               = false;
  m_LastSynchronizationTime          = "";
  m_LastSynchronizationTimeIsSet     = false;
}

void Amf3GppAccessRegistration::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool Amf3GppAccessRegistration::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool Amf3GppAccessRegistration::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "Amf3GppAccessRegistration" : pathPrefix;

  if (supportedFeaturesIsSet()) {
    const std::string& value           = m_SupportedFeatures;
    const std::string currentValuePath = _pathPrefix + ".supportedFeatures";
  }

  if (peiIsSet()) {
    const std::string& value           = m_Pei;
    const std::string currentValuePath = _pathPrefix + ".pei";
  }

  if (backupAmfInfoIsSet()) {
    const std::vector<oai::_3gpp::model::BackupAmfInfo>& value =
        m_BackupAmfInfo;
    const std::string currentValuePath = _pathPrefix + ".backupAmfInfo";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::BackupAmfInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".backupAmfInfo") && success;

        i++;
      }
    }
  }

  if (supiIsSet()) {
    const std::string& value           = m_Supi;
    const std::string currentValuePath = _pathPrefix + ".supi";
  }

  if (resetIdsIsSet()) {
    const std::vector<std::string>& value = m_ResetIds;
    const std::string currentValuePath    = _pathPrefix + ".resetIds";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const std::string& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        i++;
      }
    }
  }

  return success;
}

bool Amf3GppAccessRegistration::operator==(
    const Amf3GppAccessRegistration& rhs) const {
  return

      (getAmfInstanceId() == rhs.getAmfInstanceId()) &&

      ((!supportedFeaturesIsSet() && !rhs.supportedFeaturesIsSet()) ||
       (supportedFeaturesIsSet() && rhs.supportedFeaturesIsSet() &&
        getSupportedFeatures() == rhs.getSupportedFeatures())) &&

      ((!purgeFlagIsSet() && !rhs.purgeFlagIsSet()) ||
       (purgeFlagIsSet() && rhs.purgeFlagIsSet() &&
        isPurgeFlag() == rhs.isPurgeFlag())) &&

      ((!peiIsSet() && !rhs.peiIsSet()) ||
       (peiIsSet() && rhs.peiIsSet() && getPei() == rhs.getPei())) &&

      ((!imsVoPsIsSet() && !rhs.imsVoPsIsSet()) ||
       (imsVoPsIsSet() && rhs.imsVoPsIsSet() &&
        getImsVoPs() == rhs.getImsVoPs())) &&

      (getDeregCallbackUri() == rhs.getDeregCallbackUri()) &&

      ((!amfServiceNameDeregIsSet() && !rhs.amfServiceNameDeregIsSet()) ||
       (amfServiceNameDeregIsSet() && rhs.amfServiceNameDeregIsSet() &&
        getAmfServiceNameDereg() == rhs.getAmfServiceNameDereg())) &&

      ((!pcscfRestorationCallbackUriIsSet() &&
        !rhs.pcscfRestorationCallbackUriIsSet()) ||
       (pcscfRestorationCallbackUriIsSet() &&
        rhs.pcscfRestorationCallbackUriIsSet() &&
        getPcscfRestorationCallbackUri() ==
            rhs.getPcscfRestorationCallbackUri())) &&

      ((!amfServiceNamePcscfRestIsSet() &&
        !rhs.amfServiceNamePcscfRestIsSet()) ||
       (amfServiceNamePcscfRestIsSet() && rhs.amfServiceNamePcscfRestIsSet() &&
        getAmfServiceNamePcscfRest() == rhs.getAmfServiceNamePcscfRest())) &&

      ((!initialRegistrationIndIsSet() && !rhs.initialRegistrationIndIsSet()) ||
       (initialRegistrationIndIsSet() && rhs.initialRegistrationIndIsSet() &&
        isInitialRegistrationInd() == rhs.isInitialRegistrationInd())) &&

      ((!emergencyRegistrationIndIsSet() &&
        !rhs.emergencyRegistrationIndIsSet()) ||
       (emergencyRegistrationIndIsSet() &&
        rhs.emergencyRegistrationIndIsSet() &&
        isEmergencyRegistrationInd() == rhs.isEmergencyRegistrationInd())) &&

      (getGuami() == rhs.getGuami()) &&

      ((!backupAmfInfoIsSet() && !rhs.backupAmfInfoIsSet()) ||
       (backupAmfInfoIsSet() && rhs.backupAmfInfoIsSet() &&
        getBackupAmfInfo() == rhs.getBackupAmfInfo())) &&

      ((!drFlagIsSet() && !rhs.drFlagIsSet()) ||
       (drFlagIsSet() && rhs.drFlagIsSet() && isDrFlag() == rhs.isDrFlag())) &&

      (getRatType() == rhs.getRatType()) &&

      ((!urrpIndicatorIsSet() && !rhs.urrpIndicatorIsSet()) ||
       (urrpIndicatorIsSet() && rhs.urrpIndicatorIsSet() &&
        isUrrpIndicator() == rhs.isUrrpIndicator())) &&

      ((!amfEeSubscriptionIdIsSet() && !rhs.amfEeSubscriptionIdIsSet()) ||
       (amfEeSubscriptionIdIsSet() && rhs.amfEeSubscriptionIdIsSet() &&
        getAmfEeSubscriptionId() == rhs.getAmfEeSubscriptionId())) &&

      ((!epsInterworkingInfoIsSet() && !rhs.epsInterworkingInfoIsSet()) ||
       (epsInterworkingInfoIsSet() && rhs.epsInterworkingInfoIsSet() &&
        getEpsInterworkingInfo() == rhs.getEpsInterworkingInfo())) &&

      ((!ueSrvccCapabilityIsSet() && !rhs.ueSrvccCapabilityIsSet()) ||
       (ueSrvccCapabilityIsSet() && rhs.ueSrvccCapabilityIsSet() &&
        isUeSrvccCapability() == rhs.isUeSrvccCapability())) &&

      ((!registrationTimeIsSet() && !rhs.registrationTimeIsSet()) ||
       (registrationTimeIsSet() && rhs.registrationTimeIsSet() &&
        getRegistrationTime() == rhs.getRegistrationTime())) &&

      ((!vgmlcAddressIsSet() && !rhs.vgmlcAddressIsSet()) ||
       (vgmlcAddressIsSet() && rhs.vgmlcAddressIsSet() &&
        getVgmlcAddress() == rhs.getVgmlcAddress())) &&

      ((!contextInfoIsSet() && !rhs.contextInfoIsSet()) ||
       (contextInfoIsSet() && rhs.contextInfoIsSet() &&
        getContextInfo() == rhs.getContextInfo())) &&

      ((!noEeSubscriptionIndIsSet() && !rhs.noEeSubscriptionIndIsSet()) ||
       (noEeSubscriptionIndIsSet() && rhs.noEeSubscriptionIndIsSet() &&
        isNoEeSubscriptionInd() == rhs.isNoEeSubscriptionInd())) &&

      ((!supiIsSet() && !rhs.supiIsSet()) ||
       (supiIsSet() && rhs.supiIsSet() && getSupi() == rhs.getSupi())) &&

      ((!ueReachableIndIsSet() && !rhs.ueReachableIndIsSet()) ||
       (ueReachableIndIsSet() && rhs.ueReachableIndIsSet() &&
        getUeReachableInd() == rhs.getUeReachableInd())) &&

      ((!reRegistrationRequiredIsSet() && !rhs.reRegistrationRequiredIsSet()) ||
       (reRegistrationRequiredIsSet() && rhs.reRegistrationRequiredIsSet() &&
        isReRegistrationRequired() == rhs.isReRegistrationRequired())) &&

      ((!adminDeregSubWithdrawnIsSet() && !rhs.adminDeregSubWithdrawnIsSet()) ||
       (adminDeregSubWithdrawnIsSet() && rhs.adminDeregSubWithdrawnIsSet() &&
        isAdminDeregSubWithdrawn() == rhs.isAdminDeregSubWithdrawn())) &&

      ((!dataRestorationCallbackUriIsSet() &&
        !rhs.dataRestorationCallbackUriIsSet()) ||
       (dataRestorationCallbackUriIsSet() &&
        rhs.dataRestorationCallbackUriIsSet() &&
        getDataRestorationCallbackUri() ==
            rhs.getDataRestorationCallbackUri())) &&

      ((!resetIdsIsSet() && !rhs.resetIdsIsSet()) ||
       (resetIdsIsSet() && rhs.resetIdsIsSet() &&
        getResetIds() == rhs.getResetIds())) &&

      ((!disasterRoamingIndIsSet() && !rhs.disasterRoamingIndIsSet()) ||
       (disasterRoamingIndIsSet() && rhs.disasterRoamingIndIsSet() &&
        isDisasterRoamingInd() == rhs.isDisasterRoamingInd())) &&

      ((!ueMINTCapabilityIsSet() && !rhs.ueMINTCapabilityIsSet()) ||
       (ueMINTCapabilityIsSet() && rhs.ueMINTCapabilityIsSet() &&
        isUeMINTCapability() == rhs.isUeMINTCapability())) &&

      ((!sorSnpnSiSupportedIsSet() && !rhs.sorSnpnSiSupportedIsSet()) ||
       (sorSnpnSiSupportedIsSet() && rhs.sorSnpnSiSupportedIsSet() &&
        isSorSnpnSiSupported() == rhs.isSorSnpnSiSupported())) &&

      ((!udrRestartIndIsSet() && !rhs.udrRestartIndIsSet()) ||
       (udrRestartIndIsSet() && rhs.udrRestartIndIsSet() &&
        isUdrRestartInd() == rhs.isUdrRestartInd())) &&

      ((!lastSynchronizationTimeIsSet() &&
        !rhs.lastSynchronizationTimeIsSet()) ||
       (lastSynchronizationTimeIsSet() && rhs.lastSynchronizationTimeIsSet() &&
        getLastSynchronizationTime() == rhs.getLastSynchronizationTime()))

          ;
}

bool Amf3GppAccessRegistration::operator!=(
    const Amf3GppAccessRegistration& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Amf3GppAccessRegistration& o) {
  j                  = nlohmann::json();
  j["amfInstanceId"] = o.m_AmfInstanceId;
  if (o.supportedFeaturesIsSet())
    j["supportedFeatures"] = o.m_SupportedFeatures;
  if (o.purgeFlagIsSet()) j["purgeFlag"] = o.m_PurgeFlag;
  if (o.peiIsSet()) j["pei"] = o.m_Pei;
  if (o.imsVoPsIsSet()) j["imsVoPs"] = o.m_ImsVoPs;
  j["deregCallbackUri"] = o.m_DeregCallbackUri;
  if (o.amfServiceNameDeregIsSet())
    j["amfServiceNameDereg"] = o.m_AmfServiceNameDereg;
  if (o.pcscfRestorationCallbackUriIsSet())
    j["pcscfRestorationCallbackUri"] = o.m_PcscfRestorationCallbackUri;
  if (o.amfServiceNamePcscfRestIsSet())
    j["amfServiceNamePcscfRest"] = o.m_AmfServiceNamePcscfRest;
  if (o.initialRegistrationIndIsSet())
    j["initialRegistrationInd"] = o.m_InitialRegistrationInd;
  if (o.emergencyRegistrationIndIsSet())
    j["emergencyRegistrationInd"] = o.m_EmergencyRegistrationInd;
  j["guami"] = o.m_Guami;
  if (o.backupAmfInfoIsSet() || !o.m_BackupAmfInfo.empty())
    j["backupAmfInfo"] = o.m_BackupAmfInfo;
  if (o.drFlagIsSet()) j["drFlag"] = o.m_DrFlag;
  j["ratType"] = o.m_RatType;
  if (o.urrpIndicatorIsSet()) j["urrpIndicator"] = o.m_UrrpIndicator;
  if (o.amfEeSubscriptionIdIsSet())
    j["amfEeSubscriptionId"] = o.m_AmfEeSubscriptionId;
  if (o.epsInterworkingInfoIsSet())
    j["epsInterworkingInfo"] = o.m_EpsInterworkingInfo;
  if (o.ueSrvccCapabilityIsSet())
    j["ueSrvccCapability"] = o.m_UeSrvccCapability;
  if (o.registrationTimeIsSet()) j["registrationTime"] = o.m_RegistrationTime;
  if (o.vgmlcAddressIsSet()) j["vgmlcAddress"] = o.m_VgmlcAddress;
  if (o.contextInfoIsSet()) j["contextInfo"] = o.m_ContextInfo;
  if (o.noEeSubscriptionIndIsSet())
    j["noEeSubscriptionInd"] = o.m_NoEeSubscriptionInd;
  if (o.supiIsSet()) j["supi"] = o.m_Supi;
  if (o.ueReachableIndIsSet()) j["ueReachableInd"] = o.m_UeReachableInd;
  if (o.reRegistrationRequiredIsSet())
    j["reRegistrationRequired"] = o.m_ReRegistrationRequired;
  if (o.adminDeregSubWithdrawnIsSet())
    j["adminDeregSubWithdrawn"] = o.m_AdminDeregSubWithdrawn;
  if (o.dataRestorationCallbackUriIsSet())
    j["dataRestorationCallbackUri"] = o.m_DataRestorationCallbackUri;
  if (o.resetIdsIsSet() || !o.m_ResetIds.empty()) j["resetIds"] = o.m_ResetIds;
  if (o.disasterRoamingIndIsSet())
    j["disasterRoamingInd"] = o.m_DisasterRoamingInd;
  if (o.ueMINTCapabilityIsSet()) j["ueMINTCapability"] = o.m_UeMINTCapability;
  if (o.sorSnpnSiSupportedIsSet())
    j["sorSnpnSiSupported"] = o.m_SorSnpnSiSupported;
  if (o.udrRestartIndIsSet()) j["udrRestartInd"] = o.m_UdrRestartInd;
  if (o.lastSynchronizationTimeIsSet())
    j["lastSynchronizationTime"] = o.m_LastSynchronizationTime;
}

void from_json(const nlohmann::json& j, Amf3GppAccessRegistration& o) {
  j.at("amfInstanceId").get_to(o.m_AmfInstanceId);
  if (j.find("supportedFeatures") != j.end()) {
    j.at("supportedFeatures").get_to(o.m_SupportedFeatures);
    o.m_SupportedFeaturesIsSet = true;
  }
  if (j.find("purgeFlag") != j.end()) {
    j.at("purgeFlag").get_to(o.m_PurgeFlag);
    o.m_PurgeFlagIsSet = true;
  }
  if (j.find("pei") != j.end()) {
    j.at("pei").get_to(o.m_Pei);
    o.m_PeiIsSet = true;
  }
  if (j.find("imsVoPs") != j.end()) {
    j.at("imsVoPs").get_to(o.m_ImsVoPs);
    o.m_ImsVoPsIsSet = true;
  }
  j.at("deregCallbackUri").get_to(o.m_DeregCallbackUri);
  if (j.find("amfServiceNameDereg") != j.end()) {
    j.at("amfServiceNameDereg").get_to(o.m_AmfServiceNameDereg);
    o.m_AmfServiceNameDeregIsSet = true;
  }
  if (j.find("pcscfRestorationCallbackUri") != j.end()) {
    j.at("pcscfRestorationCallbackUri").get_to(o.m_PcscfRestorationCallbackUri);
    o.m_PcscfRestorationCallbackUriIsSet = true;
  }
  if (j.find("amfServiceNamePcscfRest") != j.end()) {
    j.at("amfServiceNamePcscfRest").get_to(o.m_AmfServiceNamePcscfRest);
    o.m_AmfServiceNamePcscfRestIsSet = true;
  }
  if (j.find("initialRegistrationInd") != j.end()) {
    j.at("initialRegistrationInd").get_to(o.m_InitialRegistrationInd);
    o.m_InitialRegistrationIndIsSet = true;
  }
  if (j.find("emergencyRegistrationInd") != j.end()) {
    j.at("emergencyRegistrationInd").get_to(o.m_EmergencyRegistrationInd);
    o.m_EmergencyRegistrationIndIsSet = true;
  }
  j.at("guami").get_to(o.m_Guami);
  if (j.find("backupAmfInfo") != j.end()) {
    j.at("backupAmfInfo").get_to(o.m_BackupAmfInfo);
    o.m_BackupAmfInfoIsSet = true;
  }
  if (j.find("drFlag") != j.end()) {
    j.at("drFlag").get_to(o.m_DrFlag);
    o.m_DrFlagIsSet = true;
  }
  j.at("ratType").get_to(o.m_RatType);
  if (j.find("urrpIndicator") != j.end()) {
    j.at("urrpIndicator").get_to(o.m_UrrpIndicator);
    o.m_UrrpIndicatorIsSet = true;
  }
  if (j.find("amfEeSubscriptionId") != j.end()) {
    j.at("amfEeSubscriptionId").get_to(o.m_AmfEeSubscriptionId);
    o.m_AmfEeSubscriptionIdIsSet = true;
  }
  if (j.find("epsInterworkingInfo") != j.end()) {
    j.at("epsInterworkingInfo").get_to(o.m_EpsInterworkingInfo);
    o.m_EpsInterworkingInfoIsSet = true;
  }
  if (j.find("ueSrvccCapability") != j.end()) {
    j.at("ueSrvccCapability").get_to(o.m_UeSrvccCapability);
    o.m_UeSrvccCapabilityIsSet = true;
  }
  if (j.find("registrationTime") != j.end()) {
    j.at("registrationTime").get_to(o.m_RegistrationTime);
    o.m_RegistrationTimeIsSet = true;
  }
  if (j.find("vgmlcAddress") != j.end()) {
    j.at("vgmlcAddress").get_to(o.m_VgmlcAddress);
    o.m_VgmlcAddressIsSet = true;
  }
  if (j.find("contextInfo") != j.end()) {
    j.at("contextInfo").get_to(o.m_ContextInfo);
    o.m_ContextInfoIsSet = true;
  }
  if (j.find("noEeSubscriptionInd") != j.end()) {
    j.at("noEeSubscriptionInd").get_to(o.m_NoEeSubscriptionInd);
    o.m_NoEeSubscriptionIndIsSet = true;
  }
  if (j.find("supi") != j.end()) {
    j.at("supi").get_to(o.m_Supi);
    o.m_SupiIsSet = true;
  }
  if (j.find("ueReachableInd") != j.end()) {
    j.at("ueReachableInd").get_to(o.m_UeReachableInd);
    o.m_UeReachableIndIsSet = true;
  }
  if (j.find("reRegistrationRequired") != j.end()) {
    j.at("reRegistrationRequired").get_to(o.m_ReRegistrationRequired);
    o.m_ReRegistrationRequiredIsSet = true;
  }
  if (j.find("adminDeregSubWithdrawn") != j.end()) {
    j.at("adminDeregSubWithdrawn").get_to(o.m_AdminDeregSubWithdrawn);
    o.m_AdminDeregSubWithdrawnIsSet = true;
  }
  if (j.find("dataRestorationCallbackUri") != j.end()) {
    j.at("dataRestorationCallbackUri").get_to(o.m_DataRestorationCallbackUri);
    o.m_DataRestorationCallbackUriIsSet = true;
  }
  if (j.find("resetIds") != j.end()) {
    j.at("resetIds").get_to(o.m_ResetIds);
    o.m_ResetIdsIsSet = true;
  }
  if (j.find("disasterRoamingInd") != j.end()) {
    j.at("disasterRoamingInd").get_to(o.m_DisasterRoamingInd);
    o.m_DisasterRoamingIndIsSet = true;
  }
  if (j.find("ueMINTCapability") != j.end()) {
    j.at("ueMINTCapability").get_to(o.m_UeMINTCapability);
    o.m_UeMINTCapabilityIsSet = true;
  }
  if (j.find("sorSnpnSiSupported") != j.end()) {
    j.at("sorSnpnSiSupported").get_to(o.m_SorSnpnSiSupported);
    o.m_SorSnpnSiSupportedIsSet = true;
  }
  if (j.find("udrRestartInd") != j.end()) {
    j.at("udrRestartInd").get_to(o.m_UdrRestartInd);
    o.m_UdrRestartIndIsSet = true;
  }
  if (j.find("lastSynchronizationTime") != j.end()) {
    j.at("lastSynchronizationTime").get_to(o.m_LastSynchronizationTime);
    o.m_LastSynchronizationTimeIsSet = true;
  }
}

std::string Amf3GppAccessRegistration::getAmfInstanceId() const {
  return m_AmfInstanceId;
}
void Amf3GppAccessRegistration::setAmfInstanceId(std::string const& value) {
  m_AmfInstanceId = value;
}
std::string Amf3GppAccessRegistration::getSupportedFeatures() const {
  return m_SupportedFeatures;
}
void Amf3GppAccessRegistration::setSupportedFeatures(std::string const& value) {
  m_SupportedFeatures      = value;
  m_SupportedFeaturesIsSet = true;
}
bool Amf3GppAccessRegistration::supportedFeaturesIsSet() const {
  return m_SupportedFeaturesIsSet;
}
void Amf3GppAccessRegistration::unsetSupportedFeatures() {
  m_SupportedFeaturesIsSet = false;
}
bool Amf3GppAccessRegistration::isPurgeFlag() const {
  return m_PurgeFlag;
}
void Amf3GppAccessRegistration::setPurgeFlag(bool const value) {
  m_PurgeFlag      = value;
  m_PurgeFlagIsSet = true;
}
bool Amf3GppAccessRegistration::purgeFlagIsSet() const {
  return m_PurgeFlagIsSet;
}
void Amf3GppAccessRegistration::unsetPurgeFlag() {
  m_PurgeFlagIsSet = false;
}
std::string Amf3GppAccessRegistration::getPei() const {
  return m_Pei;
}
void Amf3GppAccessRegistration::setPei(std::string const& value) {
  m_Pei      = value;
  m_PeiIsSet = true;
}
bool Amf3GppAccessRegistration::peiIsSet() const {
  return m_PeiIsSet;
}
void Amf3GppAccessRegistration::unsetPei() {
  m_PeiIsSet = false;
}
oai::_3gpp::model::ImsVoPs Amf3GppAccessRegistration::getImsVoPs() const {
  return m_ImsVoPs;
}
void Amf3GppAccessRegistration::setImsVoPs(
    oai::_3gpp::model::ImsVoPs const& value) {
  m_ImsVoPs      = value;
  m_ImsVoPsIsSet = true;
}
bool Amf3GppAccessRegistration::imsVoPsIsSet() const {
  return m_ImsVoPsIsSet;
}
void Amf3GppAccessRegistration::unsetImsVoPs() {
  m_ImsVoPsIsSet = false;
}
std::string Amf3GppAccessRegistration::getDeregCallbackUri() const {
  return m_DeregCallbackUri;
}
void Amf3GppAccessRegistration::setDeregCallbackUri(std::string const& value) {
  m_DeregCallbackUri = value;
}
oai::_3gpp::model::ServiceName
Amf3GppAccessRegistration::getAmfServiceNameDereg() const {
  return m_AmfServiceNameDereg;
}
void Amf3GppAccessRegistration::setAmfServiceNameDereg(
    oai::_3gpp::model::ServiceName const& value) {
  m_AmfServiceNameDereg      = value;
  m_AmfServiceNameDeregIsSet = true;
}
bool Amf3GppAccessRegistration::amfServiceNameDeregIsSet() const {
  return m_AmfServiceNameDeregIsSet;
}
void Amf3GppAccessRegistration::unsetAmfServiceNameDereg() {
  m_AmfServiceNameDeregIsSet = false;
}
std::string Amf3GppAccessRegistration::getPcscfRestorationCallbackUri() const {
  return m_PcscfRestorationCallbackUri;
}
void Amf3GppAccessRegistration::setPcscfRestorationCallbackUri(
    std::string const& value) {
  m_PcscfRestorationCallbackUri      = value;
  m_PcscfRestorationCallbackUriIsSet = true;
}
bool Amf3GppAccessRegistration::pcscfRestorationCallbackUriIsSet() const {
  return m_PcscfRestorationCallbackUriIsSet;
}
void Amf3GppAccessRegistration::unsetPcscfRestorationCallbackUri() {
  m_PcscfRestorationCallbackUriIsSet = false;
}
oai::_3gpp::model::ServiceName
Amf3GppAccessRegistration::getAmfServiceNamePcscfRest() const {
  return m_AmfServiceNamePcscfRest;
}
void Amf3GppAccessRegistration::setAmfServiceNamePcscfRest(
    oai::_3gpp::model::ServiceName const& value) {
  m_AmfServiceNamePcscfRest      = value;
  m_AmfServiceNamePcscfRestIsSet = true;
}
bool Amf3GppAccessRegistration::amfServiceNamePcscfRestIsSet() const {
  return m_AmfServiceNamePcscfRestIsSet;
}
void Amf3GppAccessRegistration::unsetAmfServiceNamePcscfRest() {
  m_AmfServiceNamePcscfRestIsSet = false;
}
bool Amf3GppAccessRegistration::isInitialRegistrationInd() const {
  return m_InitialRegistrationInd;
}
void Amf3GppAccessRegistration::setInitialRegistrationInd(bool const value) {
  m_InitialRegistrationInd      = value;
  m_InitialRegistrationIndIsSet = true;
}
bool Amf3GppAccessRegistration::initialRegistrationIndIsSet() const {
  return m_InitialRegistrationIndIsSet;
}
void Amf3GppAccessRegistration::unsetInitialRegistrationInd() {
  m_InitialRegistrationIndIsSet = false;
}
bool Amf3GppAccessRegistration::isEmergencyRegistrationInd() const {
  return m_EmergencyRegistrationInd;
}
void Amf3GppAccessRegistration::setEmergencyRegistrationInd(bool const value) {
  m_EmergencyRegistrationInd      = value;
  m_EmergencyRegistrationIndIsSet = true;
}
bool Amf3GppAccessRegistration::emergencyRegistrationIndIsSet() const {
  return m_EmergencyRegistrationIndIsSet;
}
void Amf3GppAccessRegistration::unsetEmergencyRegistrationInd() {
  m_EmergencyRegistrationIndIsSet = false;
}
oai::_3gpp::model::Guami Amf3GppAccessRegistration::getGuami() const {
  return m_Guami;
}
void Amf3GppAccessRegistration::setGuami(
    oai::_3gpp::model::Guami const& value) {
  m_Guami = value;
}
std::vector<oai::_3gpp::model::BackupAmfInfo>
Amf3GppAccessRegistration::getBackupAmfInfo() const {
  return m_BackupAmfInfo;
}
void Amf3GppAccessRegistration::setBackupAmfInfo(
    std::vector<oai::_3gpp::model::BackupAmfInfo> const& value) {
  m_BackupAmfInfo      = value;
  m_BackupAmfInfoIsSet = true;
}
bool Amf3GppAccessRegistration::backupAmfInfoIsSet() const {
  return m_BackupAmfInfoIsSet;
}
void Amf3GppAccessRegistration::unsetBackupAmfInfo() {
  m_BackupAmfInfoIsSet = false;
}
bool Amf3GppAccessRegistration::isDrFlag() const {
  return m_DrFlag;
}
void Amf3GppAccessRegistration::setDrFlag(bool const value) {
  m_DrFlag      = value;
  m_DrFlagIsSet = true;
}
bool Amf3GppAccessRegistration::drFlagIsSet() const {
  return m_DrFlagIsSet;
}
void Amf3GppAccessRegistration::unsetDrFlag() {
  m_DrFlagIsSet = false;
}
oai::_3gpp::model::RatType Amf3GppAccessRegistration::getRatType() const {
  return m_RatType;
}
void Amf3GppAccessRegistration::setRatType(
    oai::_3gpp::model::RatType const& value) {
  m_RatType = value;
}
bool Amf3GppAccessRegistration::isUrrpIndicator() const {
  return m_UrrpIndicator;
}
void Amf3GppAccessRegistration::setUrrpIndicator(bool const value) {
  m_UrrpIndicator      = value;
  m_UrrpIndicatorIsSet = true;
}
bool Amf3GppAccessRegistration::urrpIndicatorIsSet() const {
  return m_UrrpIndicatorIsSet;
}
void Amf3GppAccessRegistration::unsetUrrpIndicator() {
  m_UrrpIndicatorIsSet = false;
}
std::string Amf3GppAccessRegistration::getAmfEeSubscriptionId() const {
  return m_AmfEeSubscriptionId;
}
void Amf3GppAccessRegistration::setAmfEeSubscriptionId(
    std::string const& value) {
  m_AmfEeSubscriptionId      = value;
  m_AmfEeSubscriptionIdIsSet = true;
}
bool Amf3GppAccessRegistration::amfEeSubscriptionIdIsSet() const {
  return m_AmfEeSubscriptionIdIsSet;
}
void Amf3GppAccessRegistration::unsetAmfEeSubscriptionId() {
  m_AmfEeSubscriptionIdIsSet = false;
}
oai::_3gpp::model::EpsInterworkingInfo
Amf3GppAccessRegistration::getEpsInterworkingInfo() const {
  return m_EpsInterworkingInfo;
}
void Amf3GppAccessRegistration::setEpsInterworkingInfo(
    oai::_3gpp::model::EpsInterworkingInfo const& value) {
  m_EpsInterworkingInfo      = value;
  m_EpsInterworkingInfoIsSet = true;
}
bool Amf3GppAccessRegistration::epsInterworkingInfoIsSet() const {
  return m_EpsInterworkingInfoIsSet;
}
void Amf3GppAccessRegistration::unsetEpsInterworkingInfo() {
  m_EpsInterworkingInfoIsSet = false;
}
bool Amf3GppAccessRegistration::isUeSrvccCapability() const {
  return m_UeSrvccCapability;
}
void Amf3GppAccessRegistration::setUeSrvccCapability(bool const value) {
  m_UeSrvccCapability      = value;
  m_UeSrvccCapabilityIsSet = true;
}
bool Amf3GppAccessRegistration::ueSrvccCapabilityIsSet() const {
  return m_UeSrvccCapabilityIsSet;
}
void Amf3GppAccessRegistration::unsetUeSrvccCapability() {
  m_UeSrvccCapabilityIsSet = false;
}
std::string Amf3GppAccessRegistration::getRegistrationTime() const {
  return m_RegistrationTime;
}
void Amf3GppAccessRegistration::setRegistrationTime(std::string const& value) {
  m_RegistrationTime      = value;
  m_RegistrationTimeIsSet = true;
}
bool Amf3GppAccessRegistration::registrationTimeIsSet() const {
  return m_RegistrationTimeIsSet;
}
void Amf3GppAccessRegistration::unsetRegistrationTime() {
  m_RegistrationTimeIsSet = false;
}
oai::_3gpp::model::VgmlcAddress Amf3GppAccessRegistration::getVgmlcAddress()
    const {
  return m_VgmlcAddress;
}
void Amf3GppAccessRegistration::setVgmlcAddress(
    oai::_3gpp::model::VgmlcAddress const& value) {
  m_VgmlcAddress      = value;
  m_VgmlcAddressIsSet = true;
}
bool Amf3GppAccessRegistration::vgmlcAddressIsSet() const {
  return m_VgmlcAddressIsSet;
}
void Amf3GppAccessRegistration::unsetVgmlcAddress() {
  m_VgmlcAddressIsSet = false;
}
oai::_3gpp::model::ContextInfo Amf3GppAccessRegistration::getContextInfo()
    const {
  return m_ContextInfo;
}
void Amf3GppAccessRegistration::setContextInfo(
    oai::_3gpp::model::ContextInfo const& value) {
  m_ContextInfo      = value;
  m_ContextInfoIsSet = true;
}
bool Amf3GppAccessRegistration::contextInfoIsSet() const {
  return m_ContextInfoIsSet;
}
void Amf3GppAccessRegistration::unsetContextInfo() {
  m_ContextInfoIsSet = false;
}
bool Amf3GppAccessRegistration::isNoEeSubscriptionInd() const {
  return m_NoEeSubscriptionInd;
}
void Amf3GppAccessRegistration::setNoEeSubscriptionInd(bool const value) {
  m_NoEeSubscriptionInd      = value;
  m_NoEeSubscriptionIndIsSet = true;
}
bool Amf3GppAccessRegistration::noEeSubscriptionIndIsSet() const {
  return m_NoEeSubscriptionIndIsSet;
}
void Amf3GppAccessRegistration::unsetNoEeSubscriptionInd() {
  m_NoEeSubscriptionIndIsSet = false;
}
std::string Amf3GppAccessRegistration::getSupi() const {
  return m_Supi;
}
void Amf3GppAccessRegistration::setSupi(std::string const& value) {
  m_Supi      = value;
  m_SupiIsSet = true;
}
bool Amf3GppAccessRegistration::supiIsSet() const {
  return m_SupiIsSet;
}
void Amf3GppAccessRegistration::unsetSupi() {
  m_SupiIsSet = false;
}
oai::_3gpp::model::UeReachableInd Amf3GppAccessRegistration::getUeReachableInd()
    const {
  return m_UeReachableInd;
}
void Amf3GppAccessRegistration::setUeReachableInd(
    oai::_3gpp::model::UeReachableInd const& value) {
  m_UeReachableInd      = value;
  m_UeReachableIndIsSet = true;
}
bool Amf3GppAccessRegistration::ueReachableIndIsSet() const {
  return m_UeReachableIndIsSet;
}
void Amf3GppAccessRegistration::unsetUeReachableInd() {
  m_UeReachableIndIsSet = false;
}
bool Amf3GppAccessRegistration::isReRegistrationRequired() const {
  return m_ReRegistrationRequired;
}
void Amf3GppAccessRegistration::setReRegistrationRequired(bool const value) {
  m_ReRegistrationRequired      = value;
  m_ReRegistrationRequiredIsSet = true;
}
bool Amf3GppAccessRegistration::reRegistrationRequiredIsSet() const {
  return m_ReRegistrationRequiredIsSet;
}
void Amf3GppAccessRegistration::unsetReRegistrationRequired() {
  m_ReRegistrationRequiredIsSet = false;
}
bool Amf3GppAccessRegistration::isAdminDeregSubWithdrawn() const {
  return m_AdminDeregSubWithdrawn;
}
void Amf3GppAccessRegistration::setAdminDeregSubWithdrawn(bool const value) {
  m_AdminDeregSubWithdrawn      = value;
  m_AdminDeregSubWithdrawnIsSet = true;
}
bool Amf3GppAccessRegistration::adminDeregSubWithdrawnIsSet() const {
  return m_AdminDeregSubWithdrawnIsSet;
}
void Amf3GppAccessRegistration::unsetAdminDeregSubWithdrawn() {
  m_AdminDeregSubWithdrawnIsSet = false;
}
std::string Amf3GppAccessRegistration::getDataRestorationCallbackUri() const {
  return m_DataRestorationCallbackUri;
}
void Amf3GppAccessRegistration::setDataRestorationCallbackUri(
    std::string const& value) {
  m_DataRestorationCallbackUri      = value;
  m_DataRestorationCallbackUriIsSet = true;
}
bool Amf3GppAccessRegistration::dataRestorationCallbackUriIsSet() const {
  return m_DataRestorationCallbackUriIsSet;
}
void Amf3GppAccessRegistration::unsetDataRestorationCallbackUri() {
  m_DataRestorationCallbackUriIsSet = false;
}
std::vector<std::string> Amf3GppAccessRegistration::getResetIds() const {
  return m_ResetIds;
}
void Amf3GppAccessRegistration::setResetIds(
    std::vector<std::string> const& value) {
  m_ResetIds      = value;
  m_ResetIdsIsSet = true;
}
bool Amf3GppAccessRegistration::resetIdsIsSet() const {
  return m_ResetIdsIsSet;
}
void Amf3GppAccessRegistration::unsetResetIds() {
  m_ResetIdsIsSet = false;
}
bool Amf3GppAccessRegistration::isDisasterRoamingInd() const {
  return m_DisasterRoamingInd;
}
void Amf3GppAccessRegistration::setDisasterRoamingInd(bool const value) {
  m_DisasterRoamingInd      = value;
  m_DisasterRoamingIndIsSet = true;
}
bool Amf3GppAccessRegistration::disasterRoamingIndIsSet() const {
  return m_DisasterRoamingIndIsSet;
}
void Amf3GppAccessRegistration::unsetDisasterRoamingInd() {
  m_DisasterRoamingIndIsSet = false;
}
bool Amf3GppAccessRegistration::isUeMINTCapability() const {
  return m_UeMINTCapability;
}
void Amf3GppAccessRegistration::setUeMINTCapability(bool const value) {
  m_UeMINTCapability      = value;
  m_UeMINTCapabilityIsSet = true;
}
bool Amf3GppAccessRegistration::ueMINTCapabilityIsSet() const {
  return m_UeMINTCapabilityIsSet;
}
void Amf3GppAccessRegistration::unsetUeMINTCapability() {
  m_UeMINTCapabilityIsSet = false;
}
bool Amf3GppAccessRegistration::isSorSnpnSiSupported() const {
  return m_SorSnpnSiSupported;
}
void Amf3GppAccessRegistration::setSorSnpnSiSupported(bool const value) {
  m_SorSnpnSiSupported      = value;
  m_SorSnpnSiSupportedIsSet = true;
}
bool Amf3GppAccessRegistration::sorSnpnSiSupportedIsSet() const {
  return m_SorSnpnSiSupportedIsSet;
}
void Amf3GppAccessRegistration::unsetSorSnpnSiSupported() {
  m_SorSnpnSiSupportedIsSet = false;
}
bool Amf3GppAccessRegistration::isUdrRestartInd() const {
  return m_UdrRestartInd;
}
void Amf3GppAccessRegistration::setUdrRestartInd(bool const value) {
  m_UdrRestartInd      = value;
  m_UdrRestartIndIsSet = true;
}
bool Amf3GppAccessRegistration::udrRestartIndIsSet() const {
  return m_UdrRestartIndIsSet;
}
void Amf3GppAccessRegistration::unsetUdrRestartInd() {
  m_UdrRestartIndIsSet = false;
}
std::string Amf3GppAccessRegistration::getLastSynchronizationTime() const {
  return m_LastSynchronizationTime;
}
void Amf3GppAccessRegistration::setLastSynchronizationTime(
    std::string const& value) {
  m_LastSynchronizationTime      = value;
  m_LastSynchronizationTimeIsSet = true;
}
bool Amf3GppAccessRegistration::lastSynchronizationTimeIsSet() const {
  return m_LastSynchronizationTimeIsSet;
}
void Amf3GppAccessRegistration::unsetLastSynchronizationTime() {
  m_LastSynchronizationTimeIsSet = false;
}

}  // namespace oai::_3gpp::model
