/**
 * Namf_EventExposure
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AmfEventSubscriptionInfo.h
 *
 * Individual AMF Event Subscription Information
 */

#ifndef AmfEventSubscriptionInfo_H_
#define AmfEventSubscriptionInfo_H_

#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Individual AMF Event Subscription Information
/// </summary>
class AmfEventSubscriptionInfo {
 public:
  AmfEventSubscriptionInfo();
  virtual ~AmfEventSubscriptionInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const AmfEventSubscriptionInfo& rhs) const;
  bool operator!=(const AmfEventSubscriptionInfo& rhs) const;

  /////////////////////////////////////////////
  /// AmfEventSubscriptionInfo members

  /// <summary>
  /// String providing an URI formatted according to RFC 3986.
  /// </summary>
  std::string getSubId() const;
  void setSubId(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getNotifyCorrelationId() const;
  void setNotifyCorrelationId(std::string const& value);
  bool notifyCorrelationIdIsSet() const;
  void unsetNotifyCorrelationId();
  /// <summary>
  ///
  /// </summary>
  std::vector<int32_t> getRefIdList() const;
  void setRefIdList(std::vector<int32_t> const value);
  /// <summary>
  /// String providing an URI formatted according to RFC 3986.
  /// </summary>
  std::string getOldSubId() const;
  void setOldSubId(std::string const& value);
  bool oldSubIdIsSet() const;
  void unsetOldSubId();

  friend void to_json(nlohmann::json& j, const AmfEventSubscriptionInfo& o);
  friend void from_json(const nlohmann::json& j, AmfEventSubscriptionInfo& o);

 protected:
  std::string m_SubId;

  std::string m_NotifyCorrelationId;
  bool m_NotifyCorrelationIdIsSet;
  std::vector<int32_t> m_RefIdList;

  std::string m_OldSubId;
  bool m_OldSubIdIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* AmfEventSubscriptionInfo_H_ */
