/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AmInfluEvent_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace oai::_3gpp::model {

AmInfluEvent_anyOf::AmInfluEvent_anyOf() {}

void AmInfluEvent_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool AmInfluEvent_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool AmInfluEvent_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "AmInfluEvent_anyOf" : pathPrefix;

  if (m_value == AmInfluEvent_anyOf::eAmInfluEvent_anyOf::
                     INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool AmInfluEvent_anyOf::operator==(const AmInfluEvent_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool AmInfluEvent_anyOf::operator!=(const AmInfluEvent_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AmInfluEvent_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case AmInfluEvent_anyOf::eAmInfluEvent_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case AmInfluEvent_anyOf::eAmInfluEvent_anyOf::SERVICE_AREA_COVRG_OUTCOME:
      j = "SERVICE_AREA_COVRG_OUTCOME";
      break;
  }
}

void from_json(const nlohmann::json& j, AmInfluEvent_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "SERVICE_AREA_COVRG_OUTCOME") {
    o.setValue(
        AmInfluEvent_anyOf::eAmInfluEvent_anyOf::SERVICE_AREA_COVRG_OUTCOME);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " AmInfluEvent_anyOf::eAmInfluEvent_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

AmInfluEvent_anyOf::eAmInfluEvent_anyOf AmInfluEvent_anyOf::getValue() const {
  return m_value;
}
void AmInfluEvent_anyOf::setValue(
    AmInfluEvent_anyOf::eAmInfluEvent_anyOf value) {
  m_value = value;
}

}  // namespace oai::_3gpp::model
