/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "BdtData.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

BdtData::BdtData() {
  m_AspId           = "";
  m_BdtRefId        = "";
  m_BdtRefIdIsSet   = false;
  m_NwAreaInfoIsSet = false;
  m_NumOfUes        = 0;
  m_NumOfUesIsSet   = false;
  m_VolPerUeIsSet   = false;
  m_Dnn             = "";
  m_DnnIsSet        = false;
  m_SnssaiIsSet     = false;
  m_TrafficDes      = "";
  m_TrafficDesIsSet = false;
  m_BdtpStatusIsSet = false;
  m_SuppFeat        = "";
  m_SuppFeatIsSet   = false;
  m_ResetIdsIsSet   = false;
}

void BdtData::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool BdtData::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool BdtData::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "BdtData" : pathPrefix;

  if (numOfUesIsSet()) {
    const int32_t& value               = m_NumOfUes;
    const std::string currentValuePath = _pathPrefix + ".numOfUes";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
  }

  if (suppFeatIsSet()) {
    const std::string& value           = m_SuppFeat;
    const std::string currentValuePath = _pathPrefix + ".suppFeat";
  }

  if (resetIdsIsSet()) {
    const std::vector<std::string>& value = m_ResetIds;
    const std::string currentValuePath    = _pathPrefix + ".resetIds";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const std::string& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        i++;
      }
    }
  }

  return success;
}

bool BdtData::operator==(const BdtData& rhs) const {
  return

      (getAspId() == rhs.getAspId()) &&

      (getTransPolicy() == rhs.getTransPolicy()) &&

      ((!bdtRefIdIsSet() && !rhs.bdtRefIdIsSet()) ||
       (bdtRefIdIsSet() && rhs.bdtRefIdIsSet() &&
        getBdtRefId() == rhs.getBdtRefId())) &&

      ((!nwAreaInfoIsSet() && !rhs.nwAreaInfoIsSet()) ||
       (nwAreaInfoIsSet() && rhs.nwAreaInfoIsSet() &&
        getNwAreaInfo() == rhs.getNwAreaInfo())) &&

      ((!numOfUesIsSet() && !rhs.numOfUesIsSet()) ||
       (numOfUesIsSet() && rhs.numOfUesIsSet() &&
        getNumOfUes() == rhs.getNumOfUes())) &&

      ((!volPerUeIsSet() && !rhs.volPerUeIsSet()) ||
       (volPerUeIsSet() && rhs.volPerUeIsSet() &&
        getVolPerUe() == rhs.getVolPerUe())) &&

      ((!dnnIsSet() && !rhs.dnnIsSet()) ||
       (dnnIsSet() && rhs.dnnIsSet() && getDnn() == rhs.getDnn())) &&

      ((!snssaiIsSet() && !rhs.snssaiIsSet()) ||
       (snssaiIsSet() && rhs.snssaiIsSet() &&
        getSnssai() == rhs.getSnssai())) &&

      ((!trafficDesIsSet() && !rhs.trafficDesIsSet()) ||
       (trafficDesIsSet() && rhs.trafficDesIsSet() &&
        getTrafficDes() == rhs.getTrafficDes())) &&

      ((!bdtpStatusIsSet() && !rhs.bdtpStatusIsSet()) ||
       (bdtpStatusIsSet() && rhs.bdtpStatusIsSet() &&
        getBdtpStatus() == rhs.getBdtpStatus())) &&

      ((!suppFeatIsSet() && !rhs.suppFeatIsSet()) ||
       (suppFeatIsSet() && rhs.suppFeatIsSet() &&
        getSuppFeat() == rhs.getSuppFeat())) &&

      ((!resetIdsIsSet() && !rhs.resetIdsIsSet()) ||
       (resetIdsIsSet() && rhs.resetIdsIsSet() &&
        getResetIds() == rhs.getResetIds()))

          ;
}

bool BdtData::operator!=(const BdtData& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const BdtData& o) {
  j                = nlohmann::json();
  j["aspId"]       = o.m_AspId;
  j["transPolicy"] = o.m_TransPolicy;
  if (o.bdtRefIdIsSet()) j["bdtRefId"] = o.m_BdtRefId;
  if (o.nwAreaInfoIsSet()) j["nwAreaInfo"] = o.m_NwAreaInfo;
  if (o.numOfUesIsSet()) j["numOfUes"] = o.m_NumOfUes;
  if (o.volPerUeIsSet()) j["volPerUe"] = o.m_VolPerUe;
  if (o.dnnIsSet()) j["dnn"] = o.m_Dnn;
  if (o.snssaiIsSet()) j["snssai"] = o.m_Snssai;
  if (o.trafficDesIsSet()) j["trafficDes"] = o.m_TrafficDes;
  if (o.bdtpStatusIsSet()) j["bdtpStatus"] = o.m_BdtpStatus;
  if (o.suppFeatIsSet()) j["suppFeat"] = o.m_SuppFeat;
  if (o.resetIdsIsSet() || !o.m_ResetIds.empty()) j["resetIds"] = o.m_ResetIds;
}

void from_json(const nlohmann::json& j, BdtData& o) {
  j.at("aspId").get_to(o.m_AspId);
  j.at("transPolicy").get_to(o.m_TransPolicy);
  if (j.find("bdtRefId") != j.end()) {
    j.at("bdtRefId").get_to(o.m_BdtRefId);
    o.m_BdtRefIdIsSet = true;
  }
  if (j.find("nwAreaInfo") != j.end()) {
    j.at("nwAreaInfo").get_to(o.m_NwAreaInfo);
    o.m_NwAreaInfoIsSet = true;
  }
  if (j.find("numOfUes") != j.end()) {
    j.at("numOfUes").get_to(o.m_NumOfUes);
    o.m_NumOfUesIsSet = true;
  }
  if (j.find("volPerUe") != j.end()) {
    j.at("volPerUe").get_to(o.m_VolPerUe);
    o.m_VolPerUeIsSet = true;
  }
  if (j.find("dnn") != j.end()) {
    j.at("dnn").get_to(o.m_Dnn);
    o.m_DnnIsSet = true;
  }
  if (j.find("snssai") != j.end()) {
    j.at("snssai").get_to(o.m_Snssai);
    o.m_SnssaiIsSet = true;
  }
  if (j.find("trafficDes") != j.end()) {
    j.at("trafficDes").get_to(o.m_TrafficDes);
    o.m_TrafficDesIsSet = true;
  }
  if (j.find("bdtpStatus") != j.end()) {
    j.at("bdtpStatus").get_to(o.m_BdtpStatus);
    o.m_BdtpStatusIsSet = true;
  }
  if (j.find("suppFeat") != j.end()) {
    j.at("suppFeat").get_to(o.m_SuppFeat);
    o.m_SuppFeatIsSet = true;
  }
  if (j.find("resetIds") != j.end()) {
    j.at("resetIds").get_to(o.m_ResetIds);
    o.m_ResetIdsIsSet = true;
  }
}

std::string BdtData::getAspId() const {
  return m_AspId;
}
void BdtData::setAspId(std::string const& value) {
  m_AspId = value;
}
oai::_3gpp::model::TransferPolicy BdtData::getTransPolicy() const {
  return m_TransPolicy;
}
void BdtData::setTransPolicy(oai::_3gpp::model::TransferPolicy const& value) {
  m_TransPolicy = value;
}
std::string BdtData::getBdtRefId() const {
  return m_BdtRefId;
}
void BdtData::setBdtRefId(std::string const& value) {
  m_BdtRefId      = value;
  m_BdtRefIdIsSet = true;
}
bool BdtData::bdtRefIdIsSet() const {
  return m_BdtRefIdIsSet;
}
void BdtData::unsetBdtRefId() {
  m_BdtRefIdIsSet = false;
}
oai::_3gpp::model::NetworkAreaInfo_2 BdtData::getNwAreaInfo() const {
  return m_NwAreaInfo;
}
void BdtData::setNwAreaInfo(oai::_3gpp::model::NetworkAreaInfo_2 const& value) {
  m_NwAreaInfo      = value;
  m_NwAreaInfoIsSet = true;
}
bool BdtData::nwAreaInfoIsSet() const {
  return m_NwAreaInfoIsSet;
}
void BdtData::unsetNwAreaInfo() {
  m_NwAreaInfoIsSet = false;
}
int32_t BdtData::getNumOfUes() const {
  return m_NumOfUes;
}
void BdtData::setNumOfUes(int32_t const value) {
  m_NumOfUes      = value;
  m_NumOfUesIsSet = true;
}
bool BdtData::numOfUesIsSet() const {
  return m_NumOfUesIsSet;
}
void BdtData::unsetNumOfUes() {
  m_NumOfUesIsSet = false;
}
oai::_3gpp::model::UsageThreshold BdtData::getVolPerUe() const {
  return m_VolPerUe;
}
void BdtData::setVolPerUe(oai::_3gpp::model::UsageThreshold const& value) {
  m_VolPerUe      = value;
  m_VolPerUeIsSet = true;
}
bool BdtData::volPerUeIsSet() const {
  return m_VolPerUeIsSet;
}
void BdtData::unsetVolPerUe() {
  m_VolPerUeIsSet = false;
}
std::string BdtData::getDnn() const {
  return m_Dnn;
}
void BdtData::setDnn(std::string const& value) {
  m_Dnn      = value;
  m_DnnIsSet = true;
}
bool BdtData::dnnIsSet() const {
  return m_DnnIsSet;
}
void BdtData::unsetDnn() {
  m_DnnIsSet = false;
}
oai::_3gpp::model::Snssai BdtData::getSnssai() const {
  return m_Snssai;
}
void BdtData::setSnssai(oai::_3gpp::model::Snssai const& value) {
  m_Snssai      = value;
  m_SnssaiIsSet = true;
}
bool BdtData::snssaiIsSet() const {
  return m_SnssaiIsSet;
}
void BdtData::unsetSnssai() {
  m_SnssaiIsSet = false;
}
std::string BdtData::getTrafficDes() const {
  return m_TrafficDes;
}
void BdtData::setTrafficDes(std::string const& value) {
  m_TrafficDes      = value;
  m_TrafficDesIsSet = true;
}
bool BdtData::trafficDesIsSet() const {
  return m_TrafficDesIsSet;
}
void BdtData::unsetTrafficDes() {
  m_TrafficDesIsSet = false;
}
oai::_3gpp::model::BdtPolicyStatus BdtData::getBdtpStatus() const {
  return m_BdtpStatus;
}
void BdtData::setBdtpStatus(oai::_3gpp::model::BdtPolicyStatus const& value) {
  m_BdtpStatus      = value;
  m_BdtpStatusIsSet = true;
}
bool BdtData::bdtpStatusIsSet() const {
  return m_BdtpStatusIsSet;
}
void BdtData::unsetBdtpStatus() {
  m_BdtpStatusIsSet = false;
}
std::string BdtData::getSuppFeat() const {
  return m_SuppFeat;
}
void BdtData::setSuppFeat(std::string const& value) {
  m_SuppFeat      = value;
  m_SuppFeatIsSet = true;
}
bool BdtData::suppFeatIsSet() const {
  return m_SuppFeatIsSet;
}
void BdtData::unsetSuppFeat() {
  m_SuppFeatIsSet = false;
}
std::vector<std::string> BdtData::getResetIds() const {
  return m_ResetIds;
}
void BdtData::setResetIds(std::vector<std::string> const& value) {
  m_ResetIds      = value;
  m_ResetIdsIsSet = true;
}
bool BdtData::resetIdsIsSet() const {
  return m_ResetIdsIsSet;
}
void BdtData::unsetResetIds() {
  m_ResetIdsIsSet = false;
}

}  // namespace oai::_3gpp::model
