/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DispersionRequirement.h
 *
 * Represents the dispersion analytics requirements.
 */

#ifndef DispersionRequirement_H_
#define DispersionRequirement_H_

#include "DispersionType.h"
#include "DispersionOrderingCriterion.h"
#include "RankingCriterion.h"
#include "ClassCriterion.h"
#include <vector>
#include "MatchingDirection.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Represents the dispersion analytics requirements.
/// </summary>
class DispersionRequirement {
 public:
  DispersionRequirement();
  virtual ~DispersionRequirement() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const DispersionRequirement& rhs) const;
  bool operator!=(const DispersionRequirement& rhs) const;

  /////////////////////////////////////////////
  /// DispersionRequirement members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::DispersionType getDisperType() const;
  void setDisperType(oai::_3gpp::model::DispersionType const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::ClassCriterion> getClassCriters() const;
  void setClassCriters(
      std::vector<oai::_3gpp::model::ClassCriterion> const& value);
  bool classCritersIsSet() const;
  void unsetClassCriters();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::RankingCriterion> getRankCriters() const;
  void setRankCriters(
      std::vector<oai::_3gpp::model::RankingCriterion> const& value);
  bool rankCritersIsSet() const;
  void unsetRankCriters();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::DispersionOrderingCriterion getDispOrderCriter() const;
  void setDispOrderCriter(
      oai::_3gpp::model::DispersionOrderingCriterion const& value);
  bool dispOrderCriterIsSet() const;
  void unsetDispOrderCriter();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::MatchingDirection getOrder() const;
  void setOrder(oai::_3gpp::model::MatchingDirection const& value);
  bool orderIsSet() const;
  void unsetOrder();

  friend void to_json(nlohmann::json& j, const DispersionRequirement& o);
  friend void from_json(const nlohmann::json& j, DispersionRequirement& o);

 protected:
  oai::_3gpp::model::DispersionType m_DisperType;

  std::vector<oai::_3gpp::model::ClassCriterion> m_ClassCriters;
  bool m_ClassCritersIsSet;
  std::vector<oai::_3gpp::model::RankingCriterion> m_RankCriters;
  bool m_RankCritersIsSet;
  oai::_3gpp::model::DispersionOrderingCriterion m_DispOrderCriter;
  bool m_DispOrderCriterIsSet;
  oai::_3gpp::model::MatchingDirection m_Order;
  bool m_OrderIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* DispersionRequirement_H_ */
