/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces.   © 2024, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DnaiChangeTypeRm.h
 *
 * It can take the values  as specified for DnaiChangeType but with the OpenAPI
 * &#39;nullable: true&#39; property.
 */

#ifndef DnaiChangeTypeRm_H_
#define DnaiChangeTypeRm_H_

#include "DnaiChangeType.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// It can take the values  as specified for DnaiChangeType but with the OpenAPI
/// &#39;nullable: true&#39; property.
/// </summary>
class DnaiChangeTypeRm {
 public:
  DnaiChangeTypeRm();
  virtual ~DnaiChangeTypeRm() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const DnaiChangeTypeRm& rhs) const;
  bool operator!=(const DnaiChangeTypeRm& rhs) const;

  /////////////////////////////////////////////
  /// DnaiChangeTypeRm members

  friend void to_json(nlohmann::json& j, const DnaiChangeTypeRm& o);
  friend void from_json(const nlohmann::json& j, DnaiChangeTypeRm& o);

 protected:
};

}  // namespace oai::_3gpp::model

#endif /* DnaiChangeTypeRm_H_ */
