/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EdrxParameters.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

EdrxParameters::EdrxParameters() {
  m_EdrxValue = "";
}

void EdrxParameters::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool EdrxParameters::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool EdrxParameters::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "EdrxParameters" : pathPrefix;

  /* EdrxValue */ {
    const std::string& value           = m_EdrxValue;
    const std::string currentValuePath = _pathPrefix + ".edrxValue";
  }

  return success;
}

bool EdrxParameters::operator==(const EdrxParameters& rhs) const {
  return

      (getRatType() == rhs.getRatType()) &&

      (getEdrxValue() == rhs.getEdrxValue())

          ;
}

bool EdrxParameters::operator!=(const EdrxParameters& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const EdrxParameters& o) {
  j              = nlohmann::json();
  j["ratType"]   = o.m_RatType;
  j["edrxValue"] = o.m_EdrxValue;
}

void from_json(const nlohmann::json& j, EdrxParameters& o) {
  j.at("ratType").get_to(o.m_RatType);
  j.at("edrxValue").get_to(o.m_EdrxValue);
}

oai::_3gpp::model::RatType EdrxParameters::getRatType() const {
  return m_RatType;
}
void EdrxParameters::setRatType(oai::_3gpp::model::RatType const& value) {
  m_RatType = value;
}
std::string EdrxParameters::getEdrxValue() const {
  return m_EdrxValue;
}
void EdrxParameters::setEdrxValue(std::string const& value) {
  m_EdrxValue = value;
}

}  // namespace oai::_3gpp::model
