/**
 * Namf_MT
 * AMF Mobile Terminated Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EnableGroupReachabilityRspData.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

EnableGroupReachabilityRspData::EnableGroupReachabilityRspData() {
  m_UeConnectedListIsSet   = false;
  m_SupportedFeatures      = "";
  m_SupportedFeaturesIsSet = false;
}

void EnableGroupReachabilityRspData::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool EnableGroupReachabilityRspData::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool EnableGroupReachabilityRspData::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "EnableGroupReachabilityRspData" : pathPrefix;

  if (ueConnectedListIsSet()) {
    const std::vector<std::string>& value = m_UeConnectedList;
    const std::string currentValuePath    = _pathPrefix + ".ueConnectedList";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const std::string& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        i++;
      }
    }
  }

  if (supportedFeaturesIsSet()) {
    const std::string& value           = m_SupportedFeatures;
    const std::string currentValuePath = _pathPrefix + ".supportedFeatures";
  }

  return success;
}

bool EnableGroupReachabilityRspData::operator==(
    const EnableGroupReachabilityRspData& rhs) const {
  return

      ((!ueConnectedListIsSet() && !rhs.ueConnectedListIsSet()) ||
       (ueConnectedListIsSet() && rhs.ueConnectedListIsSet() &&
        getUeConnectedList() == rhs.getUeConnectedList())) &&

      ((!supportedFeaturesIsSet() && !rhs.supportedFeaturesIsSet()) ||
       (supportedFeaturesIsSet() && rhs.supportedFeaturesIsSet() &&
        getSupportedFeatures() == rhs.getSupportedFeatures()))

          ;
}

bool EnableGroupReachabilityRspData::operator!=(
    const EnableGroupReachabilityRspData& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const EnableGroupReachabilityRspData& o) {
  j = nlohmann::json();
  if (o.ueConnectedListIsSet() || !o.m_UeConnectedList.empty())
    j["ueConnectedList"] = o.m_UeConnectedList;
  if (o.supportedFeaturesIsSet())
    j["supportedFeatures"] = o.m_SupportedFeatures;
}

void from_json(const nlohmann::json& j, EnableGroupReachabilityRspData& o) {
  if (j.find("ueConnectedList") != j.end()) {
    j.at("ueConnectedList").get_to(o.m_UeConnectedList);
    o.m_UeConnectedListIsSet = true;
  }
  if (j.find("supportedFeatures") != j.end()) {
    j.at("supportedFeatures").get_to(o.m_SupportedFeatures);
    o.m_SupportedFeaturesIsSet = true;
  }
}

std::vector<std::string> EnableGroupReachabilityRspData::getUeConnectedList()
    const {
  return m_UeConnectedList;
}
void EnableGroupReachabilityRspData::setUeConnectedList(
    std::vector<std::string> const& value) {
  m_UeConnectedList      = value;
  m_UeConnectedListIsSet = true;
}
bool EnableGroupReachabilityRspData::ueConnectedListIsSet() const {
  return m_UeConnectedListIsSet;
}
void EnableGroupReachabilityRspData::unsetUeConnectedList() {
  m_UeConnectedListIsSet = false;
}
std::string EnableGroupReachabilityRspData::getSupportedFeatures() const {
  return m_SupportedFeatures;
}
void EnableGroupReachabilityRspData::setSupportedFeatures(
    std::string const& value) {
  m_SupportedFeatures      = value;
  m_SupportedFeaturesIsSet = true;
}
bool EnableGroupReachabilityRspData::supportedFeaturesIsSet() const {
  return m_SupportedFeaturesIsSet;
}
void EnableGroupReachabilityRspData::unsetSupportedFeatures() {
  m_SupportedFeaturesIsSet = false;
}

}  // namespace oai::_3gpp::model
