/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EventNotification.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

EventNotification::EventNotification() {
  m_Start                   = "";
  m_StartIsSet              = false;
  m_Expiry                  = "";
  m_ExpiryIsSet             = false;
  m_TimeStampGen            = "";
  m_TimeStampGenIsSet       = false;
  m_FailNotifyCodeIsSet     = false;
  m_RvWaitTime              = 0;
  m_RvWaitTimeIsSet         = false;
  m_AnaMetaInfoIsSet        = false;
  m_NfLoadLevelInfosIsSet   = false;
  m_NsiLoadLevelInfosIsSet  = false;
  m_SliceLoadLevelInfoIsSet = false;
  m_SvcExpsIsSet            = false;
  m_QosSustainInfosIsSet    = false;
  m_UeCommsIsSet            = false;
  m_UeMobsIsSet             = false;
  m_UserDataCongInfosIsSet  = false;
  m_AbnorBehavrsIsSet       = false;
  m_NwPerfsIsSet            = false;
  m_DnPerfInfosIsSet        = false;
  m_DisperInfosIsSet        = false;
  m_RedTransInfosIsSet      = false;
  m_WlanInfosIsSet          = false;
  m_SmccExpsIsSet           = false;
}

void EventNotification::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool EventNotification::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool EventNotification::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "EventNotification" : pathPrefix;

  if (nfLoadLevelInfosIsSet()) {
    const std::vector<oai::_3gpp::model::NfLoadLevelInformation>& value =
        m_NfLoadLevelInfos;
    const std::string currentValuePath = _pathPrefix + ".nfLoadLevelInfos";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::NfLoadLevelInformation& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success = value.validate(msg, currentValuePath + ".nfLoadLevelInfos") &&
                  success;

        i++;
      }
    }
  }

  if (nsiLoadLevelInfosIsSet()) {
    const std::vector<oai::_3gpp::model::NsiLoadLevelInfo>& value =
        m_NsiLoadLevelInfos;
    const std::string currentValuePath = _pathPrefix + ".nsiLoadLevelInfos";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::NsiLoadLevelInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".nsiLoadLevelInfos") &&
            success;

        i++;
      }
    }
  }

  if (svcExpsIsSet()) {
    const std::vector<oai::_3gpp::model::ServiceExperienceInfo>& value =
        m_SvcExps;
    const std::string currentValuePath = _pathPrefix + ".svcExps";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::ServiceExperienceInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success = value.validate(msg, currentValuePath + ".svcExps") && success;

        i++;
      }
    }
  }

  if (qosSustainInfosIsSet()) {
    const std::vector<oai::_3gpp::model::QosSustainabilityInfo>& value =
        m_QosSustainInfos;
    const std::string currentValuePath = _pathPrefix + ".qosSustainInfos";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::QosSustainabilityInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success = value.validate(msg, currentValuePath + ".qosSustainInfos") &&
                  success;

        i++;
      }
    }
  }

  if (ueCommsIsSet()) {
    const std::vector<oai::_3gpp::model::UeCommunication>& value = m_UeComms;
    const std::string currentValuePath = _pathPrefix + ".ueComms";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::UeCommunication& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success = value.validate(msg, currentValuePath + ".ueComms") && success;

        i++;
      }
    }
  }

  if (ueMobsIsSet()) {
    const std::vector<oai::_3gpp::model::UeMobility>& value = m_UeMobs;
    const std::string currentValuePath = _pathPrefix + ".ueMobs";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::UeMobility& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success = value.validate(msg, currentValuePath + ".ueMobs") && success;

        i++;
      }
    }
  }

  if (userDataCongInfosIsSet()) {
    const std::vector<oai::_3gpp::model::UserDataCongestionInfo>& value =
        m_UserDataCongInfos;
    const std::string currentValuePath = _pathPrefix + ".userDataCongInfos";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::UserDataCongestionInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".userDataCongInfos") &&
            success;

        i++;
      }
    }
  }

  if (abnorBehavrsIsSet()) {
    const std::vector<oai::_3gpp::model::AbnormalBehaviour>& value =
        m_AbnorBehavrs;
    const std::string currentValuePath = _pathPrefix + ".abnorBehavrs";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::AbnormalBehaviour& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".abnorBehavrs") && success;

        i++;
      }
    }
  }

  if (nwPerfsIsSet()) {
    const std::vector<oai::_3gpp::model::NetworkPerfInfo>& value = m_NwPerfs;
    const std::string currentValuePath = _pathPrefix + ".nwPerfs";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::NetworkPerfInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success = value.validate(msg, currentValuePath + ".nwPerfs") && success;

        i++;
      }
    }
  }

  if (dnPerfInfosIsSet()) {
    const std::vector<oai::_3gpp::model::DnPerfInfo>& value = m_DnPerfInfos;
    const std::string currentValuePath = _pathPrefix + ".dnPerfInfos";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::DnPerfInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".dnPerfInfos") && success;

        i++;
      }
    }
  }

  if (disperInfosIsSet()) {
    const std::vector<oai::_3gpp::model::DispersionInfo>& value = m_DisperInfos;
    const std::string currentValuePath = _pathPrefix + ".disperInfos";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::DispersionInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".disperInfos") && success;

        i++;
      }
    }
  }

  if (redTransInfosIsSet()) {
    const std::vector<oai::_3gpp::model::RedundantTransmissionExpInfo>& value =
        m_RedTransInfos;
    const std::string currentValuePath = _pathPrefix + ".redTransInfos";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::RedundantTransmissionExpInfo& value :
           value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".redTransInfos") && success;

        i++;
      }
    }
  }

  if (wlanInfosIsSet()) {
    const std::vector<oai::_3gpp::model::WlanPerformanceInfo>& value =
        m_WlanInfos;
    const std::string currentValuePath = _pathPrefix + ".wlanInfos";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::WlanPerformanceInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".wlanInfos") && success;

        i++;
      }
    }
  }

  if (smccExpsIsSet()) {
    const std::vector<oai::_3gpp::model::SmcceInfo>& value = m_SmccExps;
    const std::string currentValuePath = _pathPrefix + ".smccExps";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::SmcceInfo& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".smccExps") && success;

        i++;
      }
    }
  }

  return success;
}

bool EventNotification::operator==(const EventNotification& rhs) const {
  return

      (getEvent() == rhs.getEvent()) &&

      ((!startIsSet() && !rhs.startIsSet()) ||
       (startIsSet() && rhs.startIsSet() && getStart() == rhs.getStart())) &&

      ((!expiryIsSet() && !rhs.expiryIsSet()) ||
       (expiryIsSet() && rhs.expiryIsSet() &&
        getExpiry() == rhs.getExpiry())) &&

      ((!timeStampGenIsSet() && !rhs.timeStampGenIsSet()) ||
       (timeStampGenIsSet() && rhs.timeStampGenIsSet() &&
        getTimeStampGen() == rhs.getTimeStampGen())) &&

      ((!failNotifyCodeIsSet() && !rhs.failNotifyCodeIsSet()) ||
       (failNotifyCodeIsSet() && rhs.failNotifyCodeIsSet() &&
        getFailNotifyCode() == rhs.getFailNotifyCode())) &&

      ((!rvWaitTimeIsSet() && !rhs.rvWaitTimeIsSet()) ||
       (rvWaitTimeIsSet() && rhs.rvWaitTimeIsSet() &&
        getRvWaitTime() == rhs.getRvWaitTime())) &&

      ((!anaMetaInfoIsSet() && !rhs.anaMetaInfoIsSet()) ||
       (anaMetaInfoIsSet() && rhs.anaMetaInfoIsSet() &&
        getAnaMetaInfo() == rhs.getAnaMetaInfo())) &&

      ((!nfLoadLevelInfosIsSet() && !rhs.nfLoadLevelInfosIsSet()) ||
       (nfLoadLevelInfosIsSet() && rhs.nfLoadLevelInfosIsSet() &&
        getNfLoadLevelInfos() == rhs.getNfLoadLevelInfos())) &&

      ((!nsiLoadLevelInfosIsSet() && !rhs.nsiLoadLevelInfosIsSet()) ||
       (nsiLoadLevelInfosIsSet() && rhs.nsiLoadLevelInfosIsSet() &&
        getNsiLoadLevelInfos() == rhs.getNsiLoadLevelInfos())) &&

      ((!sliceLoadLevelInfoIsSet() && !rhs.sliceLoadLevelInfoIsSet()) ||
       (sliceLoadLevelInfoIsSet() && rhs.sliceLoadLevelInfoIsSet() &&
        getSliceLoadLevelInfo() == rhs.getSliceLoadLevelInfo())) &&

      ((!svcExpsIsSet() && !rhs.svcExpsIsSet()) ||
       (svcExpsIsSet() && rhs.svcExpsIsSet() &&
        getSvcExps() == rhs.getSvcExps())) &&

      ((!qosSustainInfosIsSet() && !rhs.qosSustainInfosIsSet()) ||
       (qosSustainInfosIsSet() && rhs.qosSustainInfosIsSet() &&
        getQosSustainInfos() == rhs.getQosSustainInfos())) &&

      ((!ueCommsIsSet() && !rhs.ueCommsIsSet()) ||
       (ueCommsIsSet() && rhs.ueCommsIsSet() &&
        getUeComms() == rhs.getUeComms())) &&

      ((!ueMobsIsSet() && !rhs.ueMobsIsSet()) ||
       (ueMobsIsSet() && rhs.ueMobsIsSet() &&
        getUeMobs() == rhs.getUeMobs())) &&

      ((!userDataCongInfosIsSet() && !rhs.userDataCongInfosIsSet()) ||
       (userDataCongInfosIsSet() && rhs.userDataCongInfosIsSet() &&
        getUserDataCongInfos() == rhs.getUserDataCongInfos())) &&

      ((!abnorBehavrsIsSet() && !rhs.abnorBehavrsIsSet()) ||
       (abnorBehavrsIsSet() && rhs.abnorBehavrsIsSet() &&
        getAbnorBehavrs() == rhs.getAbnorBehavrs())) &&

      ((!nwPerfsIsSet() && !rhs.nwPerfsIsSet()) ||
       (nwPerfsIsSet() && rhs.nwPerfsIsSet() &&
        getNwPerfs() == rhs.getNwPerfs())) &&

      ((!dnPerfInfosIsSet() && !rhs.dnPerfInfosIsSet()) ||
       (dnPerfInfosIsSet() && rhs.dnPerfInfosIsSet() &&
        getDnPerfInfos() == rhs.getDnPerfInfos())) &&

      ((!disperInfosIsSet() && !rhs.disperInfosIsSet()) ||
       (disperInfosIsSet() && rhs.disperInfosIsSet() &&
        getDisperInfos() == rhs.getDisperInfos())) &&

      ((!redTransInfosIsSet() && !rhs.redTransInfosIsSet()) ||
       (redTransInfosIsSet() && rhs.redTransInfosIsSet() &&
        getRedTransInfos() == rhs.getRedTransInfos())) &&

      ((!wlanInfosIsSet() && !rhs.wlanInfosIsSet()) ||
       (wlanInfosIsSet() && rhs.wlanInfosIsSet() &&
        getWlanInfos() == rhs.getWlanInfos())) &&

      ((!smccExpsIsSet() && !rhs.smccExpsIsSet()) ||
       (smccExpsIsSet() && rhs.smccExpsIsSet() &&
        getSmccExps() == rhs.getSmccExps()))

          ;
}

bool EventNotification::operator!=(const EventNotification& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const EventNotification& o) {
  j          = nlohmann::json();
  j["event"] = o.m_Event;
  if (o.startIsSet()) j["start"] = o.m_Start;
  if (o.expiryIsSet()) j["expiry"] = o.m_Expiry;
  if (o.timeStampGenIsSet()) j["timeStampGen"] = o.m_TimeStampGen;
  if (o.failNotifyCodeIsSet()) j["failNotifyCode"] = o.m_FailNotifyCode;
  if (o.rvWaitTimeIsSet()) j["rvWaitTime"] = o.m_RvWaitTime;
  if (o.anaMetaInfoIsSet()) j["anaMetaInfo"] = o.m_AnaMetaInfo;
  if (o.nfLoadLevelInfosIsSet() || !o.m_NfLoadLevelInfos.empty())
    j["nfLoadLevelInfos"] = o.m_NfLoadLevelInfos;
  if (o.nsiLoadLevelInfosIsSet() || !o.m_NsiLoadLevelInfos.empty())
    j["nsiLoadLevelInfos"] = o.m_NsiLoadLevelInfos;
  if (o.sliceLoadLevelInfoIsSet())
    j["sliceLoadLevelInfo"] = o.m_SliceLoadLevelInfo;
  if (o.svcExpsIsSet() || !o.m_SvcExps.empty()) j["svcExps"] = o.m_SvcExps;
  if (o.qosSustainInfosIsSet() || !o.m_QosSustainInfos.empty())
    j["qosSustainInfos"] = o.m_QosSustainInfos;
  if (o.ueCommsIsSet() || !o.m_UeComms.empty()) j["ueComms"] = o.m_UeComms;
  if (o.ueMobsIsSet() || !o.m_UeMobs.empty()) j["ueMobs"] = o.m_UeMobs;
  if (o.userDataCongInfosIsSet() || !o.m_UserDataCongInfos.empty())
    j["userDataCongInfos"] = o.m_UserDataCongInfos;
  if (o.abnorBehavrsIsSet() || !o.m_AbnorBehavrs.empty())
    j["abnorBehavrs"] = o.m_AbnorBehavrs;
  if (o.nwPerfsIsSet() || !o.m_NwPerfs.empty()) j["nwPerfs"] = o.m_NwPerfs;
  if (o.dnPerfInfosIsSet() || !o.m_DnPerfInfos.empty())
    j["dnPerfInfos"] = o.m_DnPerfInfos;
  if (o.disperInfosIsSet() || !o.m_DisperInfos.empty())
    j["disperInfos"] = o.m_DisperInfos;
  if (o.redTransInfosIsSet() || !o.m_RedTransInfos.empty())
    j["redTransInfos"] = o.m_RedTransInfos;
  if (o.wlanInfosIsSet() || !o.m_WlanInfos.empty())
    j["wlanInfos"] = o.m_WlanInfos;
  if (o.smccExpsIsSet() || !o.m_SmccExps.empty()) j["smccExps"] = o.m_SmccExps;
}

void from_json(const nlohmann::json& j, EventNotification& o) {
  j.at("event").get_to(o.m_Event);
  if (j.find("start") != j.end()) {
    j.at("start").get_to(o.m_Start);
    o.m_StartIsSet = true;
  }
  if (j.find("expiry") != j.end()) {
    j.at("expiry").get_to(o.m_Expiry);
    o.m_ExpiryIsSet = true;
  }
  if (j.find("timeStampGen") != j.end()) {
    j.at("timeStampGen").get_to(o.m_TimeStampGen);
    o.m_TimeStampGenIsSet = true;
  }
  if (j.find("failNotifyCode") != j.end()) {
    j.at("failNotifyCode").get_to(o.m_FailNotifyCode);
    o.m_FailNotifyCodeIsSet = true;
  }
  if (j.find("rvWaitTime") != j.end()) {
    j.at("rvWaitTime").get_to(o.m_RvWaitTime);
    o.m_RvWaitTimeIsSet = true;
  }
  if (j.find("anaMetaInfo") != j.end()) {
    j.at("anaMetaInfo").get_to(o.m_AnaMetaInfo);
    o.m_AnaMetaInfoIsSet = true;
  }
  if (j.find("nfLoadLevelInfos") != j.end()) {
    j.at("nfLoadLevelInfos").get_to(o.m_NfLoadLevelInfos);
    o.m_NfLoadLevelInfosIsSet = true;
  }
  if (j.find("nsiLoadLevelInfos") != j.end()) {
    j.at("nsiLoadLevelInfos").get_to(o.m_NsiLoadLevelInfos);
    o.m_NsiLoadLevelInfosIsSet = true;
  }
  if (j.find("sliceLoadLevelInfo") != j.end()) {
    j.at("sliceLoadLevelInfo").get_to(o.m_SliceLoadLevelInfo);
    o.m_SliceLoadLevelInfoIsSet = true;
  }
  if (j.find("svcExps") != j.end()) {
    j.at("svcExps").get_to(o.m_SvcExps);
    o.m_SvcExpsIsSet = true;
  }
  if (j.find("qosSustainInfos") != j.end()) {
    j.at("qosSustainInfos").get_to(o.m_QosSustainInfos);
    o.m_QosSustainInfosIsSet = true;
  }
  if (j.find("ueComms") != j.end()) {
    j.at("ueComms").get_to(o.m_UeComms);
    o.m_UeCommsIsSet = true;
  }
  if (j.find("ueMobs") != j.end()) {
    j.at("ueMobs").get_to(o.m_UeMobs);
    o.m_UeMobsIsSet = true;
  }
  if (j.find("userDataCongInfos") != j.end()) {
    j.at("userDataCongInfos").get_to(o.m_UserDataCongInfos);
    o.m_UserDataCongInfosIsSet = true;
  }
  if (j.find("abnorBehavrs") != j.end()) {
    j.at("abnorBehavrs").get_to(o.m_AbnorBehavrs);
    o.m_AbnorBehavrsIsSet = true;
  }
  if (j.find("nwPerfs") != j.end()) {
    j.at("nwPerfs").get_to(o.m_NwPerfs);
    o.m_NwPerfsIsSet = true;
  }
  if (j.find("dnPerfInfos") != j.end()) {
    j.at("dnPerfInfos").get_to(o.m_DnPerfInfos);
    o.m_DnPerfInfosIsSet = true;
  }
  if (j.find("disperInfos") != j.end()) {
    j.at("disperInfos").get_to(o.m_DisperInfos);
    o.m_DisperInfosIsSet = true;
  }
  if (j.find("redTransInfos") != j.end()) {
    j.at("redTransInfos").get_to(o.m_RedTransInfos);
    o.m_RedTransInfosIsSet = true;
  }
  if (j.find("wlanInfos") != j.end()) {
    j.at("wlanInfos").get_to(o.m_WlanInfos);
    o.m_WlanInfosIsSet = true;
  }
  if (j.find("smccExps") != j.end()) {
    j.at("smccExps").get_to(o.m_SmccExps);
    o.m_SmccExpsIsSet = true;
  }
}

oai::_3gpp::model::NwdafEvent EventNotification::getEvent() const {
  return m_Event;
}
void EventNotification::setEvent(oai::_3gpp::model::NwdafEvent const& value) {
  m_Event = value;
}
std::string EventNotification::getStart() const {
  return m_Start;
}
void EventNotification::setStart(std::string const& value) {
  m_Start      = value;
  m_StartIsSet = true;
}
bool EventNotification::startIsSet() const {
  return m_StartIsSet;
}
void EventNotification::unsetStart() {
  m_StartIsSet = false;
}
std::string EventNotification::getExpiry() const {
  return m_Expiry;
}
void EventNotification::setExpiry(std::string const& value) {
  m_Expiry      = value;
  m_ExpiryIsSet = true;
}
bool EventNotification::expiryIsSet() const {
  return m_ExpiryIsSet;
}
void EventNotification::unsetExpiry() {
  m_ExpiryIsSet = false;
}
std::string EventNotification::getTimeStampGen() const {
  return m_TimeStampGen;
}
void EventNotification::setTimeStampGen(std::string const& value) {
  m_TimeStampGen      = value;
  m_TimeStampGenIsSet = true;
}
bool EventNotification::timeStampGenIsSet() const {
  return m_TimeStampGenIsSet;
}
void EventNotification::unsetTimeStampGen() {
  m_TimeStampGenIsSet = false;
}
oai::_3gpp::model::NwdafFailureCode EventNotification::getFailNotifyCode()
    const {
  return m_FailNotifyCode;
}
void EventNotification::setFailNotifyCode(
    oai::_3gpp::model::NwdafFailureCode const& value) {
  m_FailNotifyCode      = value;
  m_FailNotifyCodeIsSet = true;
}
bool EventNotification::failNotifyCodeIsSet() const {
  return m_FailNotifyCodeIsSet;
}
void EventNotification::unsetFailNotifyCode() {
  m_FailNotifyCodeIsSet = false;
}
int32_t EventNotification::getRvWaitTime() const {
  return m_RvWaitTime;
}
void EventNotification::setRvWaitTime(int32_t const value) {
  m_RvWaitTime      = value;
  m_RvWaitTimeIsSet = true;
}
bool EventNotification::rvWaitTimeIsSet() const {
  return m_RvWaitTimeIsSet;
}
void EventNotification::unsetRvWaitTime() {
  m_RvWaitTimeIsSet = false;
}
oai::_3gpp::model::AnalyticsMetadataInfo EventNotification::getAnaMetaInfo()
    const {
  return m_AnaMetaInfo;
}
void EventNotification::setAnaMetaInfo(
    oai::_3gpp::model::AnalyticsMetadataInfo const& value) {
  m_AnaMetaInfo      = value;
  m_AnaMetaInfoIsSet = true;
}
bool EventNotification::anaMetaInfoIsSet() const {
  return m_AnaMetaInfoIsSet;
}
void EventNotification::unsetAnaMetaInfo() {
  m_AnaMetaInfoIsSet = false;
}
std::vector<oai::_3gpp::model::NfLoadLevelInformation>
EventNotification::getNfLoadLevelInfos() const {
  return m_NfLoadLevelInfos;
}
void EventNotification::setNfLoadLevelInfos(
    std::vector<oai::_3gpp::model::NfLoadLevelInformation> const& value) {
  m_NfLoadLevelInfos      = value;
  m_NfLoadLevelInfosIsSet = true;
}
bool EventNotification::nfLoadLevelInfosIsSet() const {
  return m_NfLoadLevelInfosIsSet;
}
void EventNotification::unsetNfLoadLevelInfos() {
  m_NfLoadLevelInfosIsSet = false;
}
std::vector<oai::_3gpp::model::NsiLoadLevelInfo>
EventNotification::getNsiLoadLevelInfos() const {
  return m_NsiLoadLevelInfos;
}
void EventNotification::setNsiLoadLevelInfos(
    std::vector<oai::_3gpp::model::NsiLoadLevelInfo> const& value) {
  m_NsiLoadLevelInfos      = value;
  m_NsiLoadLevelInfosIsSet = true;
}
bool EventNotification::nsiLoadLevelInfosIsSet() const {
  return m_NsiLoadLevelInfosIsSet;
}
void EventNotification::unsetNsiLoadLevelInfos() {
  m_NsiLoadLevelInfosIsSet = false;
}
oai::_3gpp::model::SliceLoadLevelInformation
EventNotification::getSliceLoadLevelInfo() const {
  return m_SliceLoadLevelInfo;
}
void EventNotification::setSliceLoadLevelInfo(
    oai::_3gpp::model::SliceLoadLevelInformation const& value) {
  m_SliceLoadLevelInfo      = value;
  m_SliceLoadLevelInfoIsSet = true;
}
bool EventNotification::sliceLoadLevelInfoIsSet() const {
  return m_SliceLoadLevelInfoIsSet;
}
void EventNotification::unsetSliceLoadLevelInfo() {
  m_SliceLoadLevelInfoIsSet = false;
}
std::vector<oai::_3gpp::model::ServiceExperienceInfo>
EventNotification::getSvcExps() const {
  return m_SvcExps;
}
void EventNotification::setSvcExps(
    std::vector<oai::_3gpp::model::ServiceExperienceInfo> const& value) {
  m_SvcExps      = value;
  m_SvcExpsIsSet = true;
}
bool EventNotification::svcExpsIsSet() const {
  return m_SvcExpsIsSet;
}
void EventNotification::unsetSvcExps() {
  m_SvcExpsIsSet = false;
}
std::vector<oai::_3gpp::model::QosSustainabilityInfo>
EventNotification::getQosSustainInfos() const {
  return m_QosSustainInfos;
}
void EventNotification::setQosSustainInfos(
    std::vector<oai::_3gpp::model::QosSustainabilityInfo> const& value) {
  m_QosSustainInfos      = value;
  m_QosSustainInfosIsSet = true;
}
bool EventNotification::qosSustainInfosIsSet() const {
  return m_QosSustainInfosIsSet;
}
void EventNotification::unsetQosSustainInfos() {
  m_QosSustainInfosIsSet = false;
}
std::vector<oai::_3gpp::model::UeCommunication> EventNotification::getUeComms()
    const {
  return m_UeComms;
}
void EventNotification::setUeComms(
    std::vector<oai::_3gpp::model::UeCommunication> const& value) {
  m_UeComms      = value;
  m_UeCommsIsSet = true;
}
bool EventNotification::ueCommsIsSet() const {
  return m_UeCommsIsSet;
}
void EventNotification::unsetUeComms() {
  m_UeCommsIsSet = false;
}
std::vector<oai::_3gpp::model::UeMobility> EventNotification::getUeMobs()
    const {
  return m_UeMobs;
}
void EventNotification::setUeMobs(
    std::vector<oai::_3gpp::model::UeMobility> const& value) {
  m_UeMobs      = value;
  m_UeMobsIsSet = true;
}
bool EventNotification::ueMobsIsSet() const {
  return m_UeMobsIsSet;
}
void EventNotification::unsetUeMobs() {
  m_UeMobsIsSet = false;
}
std::vector<oai::_3gpp::model::UserDataCongestionInfo>
EventNotification::getUserDataCongInfos() const {
  return m_UserDataCongInfos;
}
void EventNotification::setUserDataCongInfos(
    std::vector<oai::_3gpp::model::UserDataCongestionInfo> const& value) {
  m_UserDataCongInfos      = value;
  m_UserDataCongInfosIsSet = true;
}
bool EventNotification::userDataCongInfosIsSet() const {
  return m_UserDataCongInfosIsSet;
}
void EventNotification::unsetUserDataCongInfos() {
  m_UserDataCongInfosIsSet = false;
}
std::vector<oai::_3gpp::model::AbnormalBehaviour>
EventNotification::getAbnorBehavrs() const {
  return m_AbnorBehavrs;
}
void EventNotification::setAbnorBehavrs(
    std::vector<oai::_3gpp::model::AbnormalBehaviour> const& value) {
  m_AbnorBehavrs      = value;
  m_AbnorBehavrsIsSet = true;
}
bool EventNotification::abnorBehavrsIsSet() const {
  return m_AbnorBehavrsIsSet;
}
void EventNotification::unsetAbnorBehavrs() {
  m_AbnorBehavrsIsSet = false;
}
std::vector<oai::_3gpp::model::NetworkPerfInfo> EventNotification::getNwPerfs()
    const {
  return m_NwPerfs;
}
void EventNotification::setNwPerfs(
    std::vector<oai::_3gpp::model::NetworkPerfInfo> const& value) {
  m_NwPerfs      = value;
  m_NwPerfsIsSet = true;
}
bool EventNotification::nwPerfsIsSet() const {
  return m_NwPerfsIsSet;
}
void EventNotification::unsetNwPerfs() {
  m_NwPerfsIsSet = false;
}
std::vector<oai::_3gpp::model::DnPerfInfo> EventNotification::getDnPerfInfos()
    const {
  return m_DnPerfInfos;
}
void EventNotification::setDnPerfInfos(
    std::vector<oai::_3gpp::model::DnPerfInfo> const& value) {
  m_DnPerfInfos      = value;
  m_DnPerfInfosIsSet = true;
}
bool EventNotification::dnPerfInfosIsSet() const {
  return m_DnPerfInfosIsSet;
}
void EventNotification::unsetDnPerfInfos() {
  m_DnPerfInfosIsSet = false;
}
std::vector<oai::_3gpp::model::DispersionInfo>
EventNotification::getDisperInfos() const {
  return m_DisperInfos;
}
void EventNotification::setDisperInfos(
    std::vector<oai::_3gpp::model::DispersionInfo> const& value) {
  m_DisperInfos      = value;
  m_DisperInfosIsSet = true;
}
bool EventNotification::disperInfosIsSet() const {
  return m_DisperInfosIsSet;
}
void EventNotification::unsetDisperInfos() {
  m_DisperInfosIsSet = false;
}
std::vector<oai::_3gpp::model::RedundantTransmissionExpInfo>
EventNotification::getRedTransInfos() const {
  return m_RedTransInfos;
}
void EventNotification::setRedTransInfos(
    std::vector<oai::_3gpp::model::RedundantTransmissionExpInfo> const& value) {
  m_RedTransInfos      = value;
  m_RedTransInfosIsSet = true;
}
bool EventNotification::redTransInfosIsSet() const {
  return m_RedTransInfosIsSet;
}
void EventNotification::unsetRedTransInfos() {
  m_RedTransInfosIsSet = false;
}
std::vector<oai::_3gpp::model::WlanPerformanceInfo>
EventNotification::getWlanInfos() const {
  return m_WlanInfos;
}
void EventNotification::setWlanInfos(
    std::vector<oai::_3gpp::model::WlanPerformanceInfo> const& value) {
  m_WlanInfos      = value;
  m_WlanInfosIsSet = true;
}
bool EventNotification::wlanInfosIsSet() const {
  return m_WlanInfosIsSet;
}
void EventNotification::unsetWlanInfos() {
  m_WlanInfosIsSet = false;
}
std::vector<oai::_3gpp::model::SmcceInfo> EventNotification::getSmccExps()
    const {
  return m_SmccExps;
}
void EventNotification::setSmccExps(
    std::vector<oai::_3gpp::model::SmcceInfo> const& value) {
  m_SmccExps      = value;
  m_SmccExpsIsSet = true;
}
bool EventNotification::smccExpsIsSet() const {
  return m_SmccExpsIsSet;
}
void EventNotification::unsetSmccExps() {
  m_SmccExpsIsSet = false;
}

}  // namespace oai::_3gpp::model
