/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces.   © 2024, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "GeoServiceArea.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

GeoServiceArea::GeoServiceArea() {
  m_GeographicAreaListIsSet = false;
  m_CivicAddressListIsSet   = false;
}

void GeoServiceArea::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool GeoServiceArea::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool GeoServiceArea::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "GeoServiceArea" : pathPrefix;

  if (geographicAreaListIsSet()) {
    const std::vector<oai::_3gpp::model::GeographicArea>& value =
        m_GeographicAreaList;
    const std::string currentValuePath = _pathPrefix + ".geographicAreaList";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::GeographicArea& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".geographicAreaList") &&
            success;

        i++;
      }
    }
  }

  if (civicAddressListIsSet()) {
    const std::vector<oai::_3gpp::model::CivicAddress>& value =
        m_CivicAddressList;
    const std::string currentValuePath = _pathPrefix + ".civicAddressList";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::CivicAddress& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success = value.validate(msg, currentValuePath + ".civicAddressList") &&
                  success;

        i++;
      }
    }
  }

  return success;
}

bool GeoServiceArea::operator==(const GeoServiceArea& rhs) const {
  return

      ((!geographicAreaListIsSet() && !rhs.geographicAreaListIsSet()) ||
       (geographicAreaListIsSet() && rhs.geographicAreaListIsSet() &&
        getGeographicAreaList() == rhs.getGeographicAreaList())) &&

      ((!civicAddressListIsSet() && !rhs.civicAddressListIsSet()) ||
       (civicAddressListIsSet() && rhs.civicAddressListIsSet() &&
        getCivicAddressList() == rhs.getCivicAddressList()))

          ;
}

bool GeoServiceArea::operator!=(const GeoServiceArea& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const GeoServiceArea& o) {
  j = nlohmann::json();
  if (o.geographicAreaListIsSet() || !o.m_GeographicAreaList.empty())
    j["geographicAreaList"] = o.m_GeographicAreaList;
  if (o.civicAddressListIsSet() || !o.m_CivicAddressList.empty())
    j["civicAddressList"] = o.m_CivicAddressList;
}

void from_json(const nlohmann::json& j, GeoServiceArea& o) {
  if (j.find("geographicAreaList") != j.end()) {
    j.at("geographicAreaList").get_to(o.m_GeographicAreaList);
    o.m_GeographicAreaListIsSet = true;
  }
  if (j.find("civicAddressList") != j.end()) {
    j.at("civicAddressList").get_to(o.m_CivicAddressList);
    o.m_CivicAddressListIsSet = true;
  }
}

std::vector<oai::_3gpp::model::GeographicArea>
GeoServiceArea::getGeographicAreaList() const {
  return m_GeographicAreaList;
}
void GeoServiceArea::setGeographicAreaList(
    std::vector<oai::_3gpp::model::GeographicArea> const& value) {
  m_GeographicAreaList      = value;
  m_GeographicAreaListIsSet = true;
}
bool GeoServiceArea::geographicAreaListIsSet() const {
  return m_GeographicAreaListIsSet;
}
void GeoServiceArea::unsetGeographicAreaList() {
  m_GeographicAreaListIsSet = false;
}
std::vector<oai::_3gpp::model::CivicAddress>
GeoServiceArea::getCivicAddressList() const {
  return m_CivicAddressList;
}
void GeoServiceArea::setCivicAddressList(
    std::vector<oai::_3gpp::model::CivicAddress> const& value) {
  m_CivicAddressList      = value;
  m_CivicAddressListIsSet = true;
}
bool GeoServiceArea::civicAddressListIsSet() const {
  return m_CivicAddressListIsSet;
}
void GeoServiceArea::unsetCivicAddressList() {
  m_CivicAddressListIsSet = false;
}

}  // namespace oai::_3gpp::model
