/**
 * Nudm_UECM
 * Nudm Context Management Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * IpSmGwGuidance.h
 *
 * Contains guidance information (e.g. minimum and recommended delivery times)
 * of the IP-SM-GW
 */

#ifndef IpSmGwGuidance_H_
#define IpSmGwGuidance_H_

#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Contains guidance information (e.g. minimum and recommended delivery times)
/// of the IP-SM-GW
/// </summary>
class IpSmGwGuidance {
 public:
  IpSmGwGuidance();
  virtual ~IpSmGwGuidance() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const IpSmGwGuidance& rhs) const;
  bool operator!=(const IpSmGwGuidance& rhs) const;

  /////////////////////////////////////////////
  /// IpSmGwGuidance members

  /// <summary>
  ///
  /// </summary>
  int32_t getMinDeliveryTime() const;
  void setMinDeliveryTime(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getRecommDeliveryTime() const;
  void setRecommDeliveryTime(int32_t const value);

  friend void to_json(nlohmann::json& j, const IpSmGwGuidance& o);
  friend void from_json(const nlohmann::json& j, IpSmGwGuidance& o);

 protected:
  int32_t m_MinDeliveryTime;

  int32_t m_RecommDeliveryTime;
};

}  // namespace oai::_3gpp::model

#endif /* IpSmGwGuidance_H_ */
