/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * LadnInfo.h
 *
 * LADN Information
 */

#ifndef LadnInfo_H_
#define LadnInfo_H_

#include <string>
#include "PresenceState.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// LADN Information
/// </summary>
class LadnInfo {
 public:
  LadnInfo();
  virtual ~LadnInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const LadnInfo& rhs) const;
  bool operator!=(const LadnInfo& rhs) const;

  /////////////////////////////////////////////
  /// LadnInfo members

  /// <summary>
  ///
  /// </summary>
  std::string getLadn() const;
  void setLadn(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::PresenceState getPresence() const;
  void setPresence(oai::_3gpp::model::PresenceState const& value);
  bool presenceIsSet() const;
  void unsetPresence();

  friend void to_json(nlohmann::json& j, const LadnInfo& o);
  friend void from_json(const nlohmann::json& j, LadnInfo& o);

 protected:
  std::string m_Ladn;

  oai::_3gpp::model::PresenceState m_Presence;
  bool m_PresenceIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* LadnInfo_H_ */
