/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "MatchingDirection.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

MatchingDirection::MatchingDirection() {}

void MatchingDirection::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool MatchingDirection::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool MatchingDirection::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "MatchingDirection" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool MatchingDirection::operator==(const MatchingDirection& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool MatchingDirection::operator!=(const MatchingDirection& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const MatchingDirection& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, MatchingDirection& o) {
  from_json(j, o.m_value);
}

MatchingDirection_anyOf MatchingDirection::getValue() const {
  return m_value;
}

void MatchingDirection::setValue(MatchingDirection_anyOf value) {
  m_value = value;
}

MatchingDirection_anyOf::eMatchingDirection_anyOf
MatchingDirection::getEnumValue() const {
  return m_value.getValue();
}

void MatchingDirection::setEnumValue(
    MatchingDirection_anyOf::eMatchingDirection_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::_3gpp::model
