/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces.   © 2024, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "MbsServiceType_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace oai::_3gpp::model {

MbsServiceType_anyOf::MbsServiceType_anyOf() {}

void MbsServiceType_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool MbsServiceType_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool MbsServiceType_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "MbsServiceType_anyOf" : pathPrefix;

  if (m_value == MbsServiceType_anyOf::eMbsServiceType_anyOf::
                     INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool MbsServiceType_anyOf::operator==(const MbsServiceType_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool MbsServiceType_anyOf::operator!=(const MbsServiceType_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const MbsServiceType_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case MbsServiceType_anyOf::eMbsServiceType_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case MbsServiceType_anyOf::eMbsServiceType_anyOf::MULTICAST:
      j = "MULTICAST";
      break;
    case MbsServiceType_anyOf::eMbsServiceType_anyOf::BROADCAST:
      j = "BROADCAST";
      break;
  }
}

void from_json(const nlohmann::json& j, MbsServiceType_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "MULTICAST") {
    o.setValue(MbsServiceType_anyOf::eMbsServiceType_anyOf::MULTICAST);
  } else if (s == "BROADCAST") {
    o.setValue(MbsServiceType_anyOf::eMbsServiceType_anyOf::BROADCAST);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " MbsServiceType_anyOf::eMbsServiceType_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

MbsServiceType_anyOf::eMbsServiceType_anyOf MbsServiceType_anyOf::getValue()
    const {
  return m_value;
}
void MbsServiceType_anyOf::setValue(
    MbsServiceType_anyOf::eMbsServiceType_anyOf value) {
  m_value = value;
}

}  // namespace oai::_3gpp::model
