/**
 * Nnef_EventExposure
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "MediaStreamingAccessRecord.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

MediaStreamingAccessRecord::MediaStreamingAccessRecord() {
  m_Timestamp              = "";
  m_SessionIdentifier      = "";
  m_SessionIdentifierIsSet = false;
  m_CacheStatusIsSet       = false;
  m_ProcessingLatency      = 0.0f;
  m_ConnectionMetricsIsSet = false;
}

void MediaStreamingAccessRecord::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool MediaStreamingAccessRecord::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool MediaStreamingAccessRecord::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "MediaStreamingAccessRecord" : pathPrefix;

  return success;
}

bool MediaStreamingAccessRecord::operator==(
    const MediaStreamingAccessRecord& rhs) const {
  return

      (getTimestamp() == rhs.getTimestamp()) &&

      (getMediaStreamHandlerEndpointAddress() ==
       rhs.getMediaStreamHandlerEndpointAddress()) &&

      (getApplicationServerEndpointAddress() ==
       rhs.getApplicationServerEndpointAddress()) &&

      ((!sessionIdentifierIsSet() && !rhs.sessionIdentifierIsSet()) ||
       (sessionIdentifierIsSet() && rhs.sessionIdentifierIsSet() &&
        getSessionIdentifier() == rhs.getSessionIdentifier())) &&

      (getRequestMessage() == rhs.getRequestMessage()) &&

      ((!cacheStatusIsSet() && !rhs.cacheStatusIsSet()) ||
       (cacheStatusIsSet() && rhs.cacheStatusIsSet() &&
        getCacheStatus() == rhs.getCacheStatus())) &&

      (getResponseMessage() == rhs.getResponseMessage()) &&

      (getProcessingLatency() == rhs.getProcessingLatency()) &&

      ((!connectionMetricsIsSet() && !rhs.connectionMetricsIsSet()) ||
       (connectionMetricsIsSet() && rhs.connectionMetricsIsSet() &&
        getConnectionMetrics() == rhs.getConnectionMetrics()))

          ;
}

bool MediaStreamingAccessRecord::operator!=(
    const MediaStreamingAccessRecord& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const MediaStreamingAccessRecord& o) {
  j              = nlohmann::json();
  j["timestamp"] = o.m_Timestamp;
  j["mediaStreamHandlerEndpointAddress"] =
      o.m_MediaStreamHandlerEndpointAddress;
  j["applicationServerEndpointAddress"] = o.m_ApplicationServerEndpointAddress;
  if (o.sessionIdentifierIsSet())
    j["sessionIdentifier"] = o.m_SessionIdentifier;
  j["requestMessage"] = o.m_RequestMessage;
  if (o.cacheStatusIsSet()) j["cacheStatus"] = o.m_CacheStatus;
  j["responseMessage"]   = o.m_ResponseMessage;
  j["processingLatency"] = o.m_ProcessingLatency;
  if (o.connectionMetricsIsSet())
    j["connectionMetrics"] = o.m_ConnectionMetrics;
}

void from_json(const nlohmann::json& j, MediaStreamingAccessRecord& o) {
  j.at("timestamp").get_to(o.m_Timestamp);
  j.at("mediaStreamHandlerEndpointAddress")
      .get_to(o.m_MediaStreamHandlerEndpointAddress);
  j.at("applicationServerEndpointAddress")
      .get_to(o.m_ApplicationServerEndpointAddress);
  if (j.find("sessionIdentifier") != j.end()) {
    j.at("sessionIdentifier").get_to(o.m_SessionIdentifier);
    o.m_SessionIdentifierIsSet = true;
  }
  j.at("requestMessage").get_to(o.m_RequestMessage);
  if (j.find("cacheStatus") != j.end()) {
    j.at("cacheStatus").get_to(o.m_CacheStatus);
    o.m_CacheStatusIsSet = true;
  }
  j.at("responseMessage").get_to(o.m_ResponseMessage);
  j.at("processingLatency").get_to(o.m_ProcessingLatency);
  if (j.find("connectionMetrics") != j.end()) {
    j.at("connectionMetrics").get_to(o.m_ConnectionMetrics);
    o.m_ConnectionMetricsIsSet = true;
  }
}

std::string MediaStreamingAccessRecord::getTimestamp() const {
  return m_Timestamp;
}
void MediaStreamingAccessRecord::setTimestamp(std::string const& value) {
  m_Timestamp = value;
}
oai::_3gpp::model::EndpointAddress
MediaStreamingAccessRecord::getMediaStreamHandlerEndpointAddress() const {
  return m_MediaStreamHandlerEndpointAddress;
}
void MediaStreamingAccessRecord::setMediaStreamHandlerEndpointAddress(
    oai::_3gpp::model::EndpointAddress const& value) {
  m_MediaStreamHandlerEndpointAddress = value;
}
oai::_3gpp::model::EndpointAddress
MediaStreamingAccessRecord::getApplicationServerEndpointAddress() const {
  return m_ApplicationServerEndpointAddress;
}
void MediaStreamingAccessRecord::setApplicationServerEndpointAddress(
    oai::_3gpp::model::EndpointAddress const& value) {
  m_ApplicationServerEndpointAddress = value;
}
std::string MediaStreamingAccessRecord::getSessionIdentifier() const {
  return m_SessionIdentifier;
}
void MediaStreamingAccessRecord::setSessionIdentifier(
    std::string const& value) {
  m_SessionIdentifier      = value;
  m_SessionIdentifierIsSet = true;
}
bool MediaStreamingAccessRecord::sessionIdentifierIsSet() const {
  return m_SessionIdentifierIsSet;
}
void MediaStreamingAccessRecord::unsetSessionIdentifier() {
  m_SessionIdentifierIsSet = false;
}
oai::_3gpp::model::MediaStreamingAccessRecord_allOf_requestMessage
MediaStreamingAccessRecord::getRequestMessage() const {
  return m_RequestMessage;
}
void MediaStreamingAccessRecord::setRequestMessage(
    oai::_3gpp::model::MediaStreamingAccessRecord_allOf_requestMessage const&
        value) {
  m_RequestMessage = value;
}
oai::_3gpp::model::CacheStatus MediaStreamingAccessRecord::getCacheStatus()
    const {
  return m_CacheStatus;
}
void MediaStreamingAccessRecord::setCacheStatus(
    oai::_3gpp::model::CacheStatus const& value) {
  m_CacheStatus      = value;
  m_CacheStatusIsSet = true;
}
bool MediaStreamingAccessRecord::cacheStatusIsSet() const {
  return m_CacheStatusIsSet;
}
void MediaStreamingAccessRecord::unsetCacheStatus() {
  m_CacheStatusIsSet = false;
}
oai::_3gpp::model::MediaStreamingAccessRecord_allOf_responseMessage
MediaStreamingAccessRecord::getResponseMessage() const {
  return m_ResponseMessage;
}
void MediaStreamingAccessRecord::setResponseMessage(
    oai::_3gpp::model::MediaStreamingAccessRecord_allOf_responseMessage const&
        value) {
  m_ResponseMessage = value;
}
float MediaStreamingAccessRecord::getProcessingLatency() const {
  return m_ProcessingLatency;
}
void MediaStreamingAccessRecord::setProcessingLatency(float const value) {
  m_ProcessingLatency = value;
}
oai::_3gpp::model::MediaStreamingAccessRecord_allOf_connectionMetrics
MediaStreamingAccessRecord::getConnectionMetrics() const {
  return m_ConnectionMetrics;
}
void MediaStreamingAccessRecord::setConnectionMetrics(
    oai::_3gpp::model::MediaStreamingAccessRecord_allOf_connectionMetrics const&
        value) {
  m_ConnectionMetrics      = value;
  m_ConnectionMetricsIsSet = true;
}
bool MediaStreamingAccessRecord::connectionMetricsIsSet() const {
  return m_ConnectionMetricsIsSet;
}
void MediaStreamingAccessRecord::unsetConnectionMetrics() {
  m_ConnectionMetricsIsSet = false;
}

}  // namespace oai::_3gpp::model
