/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N2InfoNotificationRspData.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

N2InfoNotificationRspData::N2InfoNotificationRspData() {
  m_SecRatDataUsageListIsSet = false;
}

void N2InfoNotificationRspData::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool N2InfoNotificationRspData::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool N2InfoNotificationRspData::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "N2InfoNotificationRspData" : pathPrefix;

  if (secRatDataUsageListIsSet()) {
    const std::vector<oai::_3gpp::model::N2SmInformation>& value =
        m_SecRatDataUsageList;
    const std::string currentValuePath = _pathPrefix + ".secRatDataUsageList";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::N2SmInformation& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".secRatDataUsageList") &&
            success;

        i++;
      }
    }
  }

  return success;
}

bool N2InfoNotificationRspData::operator==(
    const N2InfoNotificationRspData& rhs) const {
  return

      ((!secRatDataUsageListIsSet() && !rhs.secRatDataUsageListIsSet()) ||
       (secRatDataUsageListIsSet() && rhs.secRatDataUsageListIsSet() &&
        getSecRatDataUsageList() == rhs.getSecRatDataUsageList()))

          ;
}

bool N2InfoNotificationRspData::operator!=(
    const N2InfoNotificationRspData& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const N2InfoNotificationRspData& o) {
  j = nlohmann::json();
  if (o.secRatDataUsageListIsSet() || !o.m_SecRatDataUsageList.empty())
    j["secRatDataUsageList"] = o.m_SecRatDataUsageList;
}

void from_json(const nlohmann::json& j, N2InfoNotificationRspData& o) {
  if (j.find("secRatDataUsageList") != j.end()) {
    j.at("secRatDataUsageList").get_to(o.m_SecRatDataUsageList);
    o.m_SecRatDataUsageListIsSet = true;
  }
}

std::vector<oai::_3gpp::model::N2SmInformation>
N2InfoNotificationRspData::getSecRatDataUsageList() const {
  return m_SecRatDataUsageList;
}
void N2InfoNotificationRspData::setSecRatDataUsageList(
    std::vector<oai::_3gpp::model::N2SmInformation> const& value) {
  m_SecRatDataUsageList      = value;
  m_SecRatDataUsageListIsSet = true;
}
bool N2InfoNotificationRspData::secRatDataUsageListIsSet() const {
  return m_SecRatDataUsageListIsSet;
}
void N2InfoNotificationRspData::unsetSecRatDataUsageList() {
  m_SecRatDataUsageListIsSet = false;
}

}  // namespace oai::_3gpp::model
