/**
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * N4MessageType_anyOf.h
 *
 *
 */

#ifndef N4MessageType_anyOf_H_
#define N4MessageType_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class N4MessageType_anyOf {
 public:
  N4MessageType_anyOf();
  virtual ~N4MessageType_anyOf() = default;

  enum class eN4MessageType_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    EST_REQ,
    EST_RSP,
    MOD_REQ,
    MOD_RSP,
    DEL_REQ,
    DEL_RSP,
    REP_REQ,
    REP_RSP
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const N4MessageType_anyOf& rhs) const;
  bool operator!=(const N4MessageType_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// N4MessageType_anyOf members

  N4MessageType_anyOf::eN4MessageType_anyOf getValue() const;
  void setValue(N4MessageType_anyOf::eN4MessageType_anyOf value);

  friend void to_json(nlohmann::json& j, const N4MessageType_anyOf& o);
  friend void from_json(const nlohmann::json& j, N4MessageType_anyOf& o);

 protected:
  N4MessageType_anyOf::eN4MessageType_anyOf m_value = N4MessageType_anyOf::
      eN4MessageType_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::_3gpp::model

#endif /* N4MessageType_anyOf_H_ */
