/**
 * Namf_MBSBroadcast
 * AMF MBSBroadcast Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NgranFailureIndication.h
 *
 * Indicates a NG-RAN failure event.
 */

#ifndef NgranFailureIndication_H_
#define NgranFailureIndication_H_

#include "NgranFailureIndication_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Indicates a NG-RAN failure event.
/// </summary>
class NgranFailureIndication {
 public:
  NgranFailureIndication();
  virtual ~NgranFailureIndication() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const NgranFailureIndication& rhs) const;
  bool operator!=(const NgranFailureIndication& rhs) const;

  /////////////////////////////////////////////
  /// NgranFailureIndication members

  NgranFailureIndication_anyOf getValue() const;
  void setValue(NgranFailureIndication_anyOf value);
  NgranFailureIndication_anyOf::eNgranFailureIndication_anyOf getEnumValue()
      const;
  void setEnumValue(
      NgranFailureIndication_anyOf::eNgranFailureIndication_anyOf value);
  friend void to_json(nlohmann::json& j, const NgranFailureIndication& o);
  friend void from_json(const nlohmann::json& j, NgranFailureIndication& o);
  friend void to_json(nlohmann::json& j, const NgranFailureIndication_anyOf& o);
  friend void from_json(
      const nlohmann::json& j, NgranFailureIndication_anyOf& o);

 protected:
  NgranFailureIndication_anyOf m_value;
};

}  // namespace oai::_3gpp::model

#endif /* NgranFailureIndication_H_ */
