/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NodeFunctionality_anyOf.h
 *
 *
 */

#ifndef NodeFunctionality_anyOf_H_
#define NodeFunctionality_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class NodeFunctionality_anyOf {
 public:
  NodeFunctionality_anyOf();
  virtual ~NodeFunctionality_anyOf() = default;

  enum class eNodeFunctionality_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    SMF,
    SMSF,
    I_SMF
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const NodeFunctionality_anyOf& rhs) const;
  bool operator!=(const NodeFunctionality_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// NodeFunctionality_anyOf members

  NodeFunctionality_anyOf::eNodeFunctionality_anyOf getValue() const;
  void setValue(NodeFunctionality_anyOf::eNodeFunctionality_anyOf value);

  friend void to_json(nlohmann::json& j, const NodeFunctionality_anyOf& o);
  friend void from_json(const nlohmann::json& j, NodeFunctionality_anyOf& o);

 protected:
  NodeFunctionality_anyOf::eNodeFunctionality_anyOf m_value =
      NodeFunctionality_anyOf::eNodeFunctionality_anyOf::
          INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::_3gpp::model

#endif /* NodeFunctionality_anyOf_H_ */
