/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NonUeN2InfoNotify_request.h
 *
 *
 */

#ifndef NonUeN2InfoNotify_request_H_
#define NonUeN2InfoNotify_request_H_

#include <string>
#include "N2InformationNotification.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class NonUeN2InfoNotify_request {
 public:
  NonUeN2InfoNotify_request();
  virtual ~NonUeN2InfoNotify_request() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const NonUeN2InfoNotify_request& rhs) const;
  bool operator!=(const NonUeN2InfoNotify_request& rhs) const;

  /////////////////////////////////////////////
  /// NonUeN2InfoNotify_request members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::N2InformationNotification getJsonData() const;
  void setJsonData(oai::_3gpp::model::N2InformationNotification const& value);
  bool jsonDataIsSet() const;
  void unsetJsonData();
  /// <summary>
  ///
  /// </summary>
  std::string getBinaryDataN2Information() const;
  void setBinaryDataN2Information(std::string const& value);
  bool binaryDataN2InformationIsSet() const;
  void unsetBinaryDataN2Information();

  friend void to_json(nlohmann::json& j, const NonUeN2InfoNotify_request& o);
  friend void from_json(const nlohmann::json& j, NonUeN2InfoNotify_request& o);

 protected:
  oai::_3gpp::model::N2InformationNotification m_JsonData;
  bool m_JsonDataIsSet;
  std::string m_BinaryDataN2Information;
  bool m_BinaryDataN2InformationIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* NonUeN2InfoNotify_request_H_ */
