/**
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NotificationInfo.h
 *
 * Notification Correlation ID and Notification URI provided by the NF service
 * consumer
 */

#ifndef NotificationInfo_H_
#define NotificationInfo_H_

#include <string>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Notification Correlation ID and Notification URI provided by the NF service
/// consumer
/// </summary>
class NotificationInfo {
 public:
  NotificationInfo();
  virtual ~NotificationInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const NotificationInfo& rhs) const;
  bool operator!=(const NotificationInfo& rhs) const;

  /////////////////////////////////////////////
  /// NotificationInfo members

  /// <summary>
  ///
  /// </summary>
  std::string getNotifId() const;
  void setNotifId(std::string const& value);
  /// <summary>
  /// String providing an URI formatted according to RFC 3986.
  /// </summary>
  std::string getNotifUri() const;
  void setNotifUri(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  bool isUpBufferInd() const;
  void setUpBufferInd(bool const value);
  bool upBufferIndIsSet() const;
  void unsetUpBufferInd();

  friend void to_json(nlohmann::json& j, const NotificationInfo& o);
  friend void from_json(const nlohmann::json& j, NotificationInfo& o);

 protected:
  std::string m_NotifId;

  std::string m_NotifUri;

  bool m_UpBufferInd;
  bool m_UpBufferIndIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* NotificationInfo_H_ */
