/**
 * NRF NFManagement Service
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NrfInfo_servedUdsfInfo_value.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

NrfInfo_servedUdsfInfo_value::NrfInfo_servedUdsfInfo_value() {
  m_GroupId              = "";
  m_GroupIdIsSet         = false;
  m_SupiRangesIsSet      = false;
  m_StorageIdRangesIsSet = false;
}

void NrfInfo_servedUdsfInfo_value::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool NrfInfo_servedUdsfInfo_value::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool NrfInfo_servedUdsfInfo_value::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "NrfInfo_servedUdsfInfo_value" : pathPrefix;

  if (supiRangesIsSet()) {
    const std::vector<oai::_3gpp::model::SupiRange>& value = m_SupiRanges;
    const std::string currentValuePath = _pathPrefix + ".supiRanges";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::SupiRange& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".supiRanges") && success;

        i++;
      }
    }
  }

  if (storageIdRangesIsSet()) {
    const std::map<std::string, std::vector<oai::_3gpp::model::IdentityRange>>&
        value                          = m_StorageIdRanges;
    const std::string currentValuePath = _pathPrefix + ".storageIdRanges";
  }

  return success;
}

bool NrfInfo_servedUdsfInfo_value::operator==(
    const NrfInfo_servedUdsfInfo_value& rhs) const {
  return

      ((!groupIdIsSet() && !rhs.groupIdIsSet()) ||
       (groupIdIsSet() && rhs.groupIdIsSet() &&
        getGroupId() == rhs.getGroupId())) &&

      ((!supiRangesIsSet() && !rhs.supiRangesIsSet()) ||
       (supiRangesIsSet() && rhs.supiRangesIsSet() &&
        getSupiRanges() == rhs.getSupiRanges())) &&

      ((!storageIdRangesIsSet() && !rhs.storageIdRangesIsSet()) ||
       (storageIdRangesIsSet() && rhs.storageIdRangesIsSet() &&
        getStorageIdRanges() == rhs.getStorageIdRanges()))

          ;
}

bool NrfInfo_servedUdsfInfo_value::operator!=(
    const NrfInfo_servedUdsfInfo_value& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NrfInfo_servedUdsfInfo_value& o) {
  j = nlohmann::json();
  if (o.groupIdIsSet()) j["groupId"] = o.m_GroupId;
  if (o.supiRangesIsSet() || !o.m_SupiRanges.empty())
    j["supiRanges"] = o.m_SupiRanges;
  if (o.storageIdRangesIsSet() || !o.m_StorageIdRanges.empty())
    j["storageIdRanges"] = o.m_StorageIdRanges;
}

void from_json(const nlohmann::json& j, NrfInfo_servedUdsfInfo_value& o) {
  if (j.find("groupId") != j.end()) {
    j.at("groupId").get_to(o.m_GroupId);
    o.m_GroupIdIsSet = true;
  }
  if (j.find("supiRanges") != j.end()) {
    j.at("supiRanges").get_to(o.m_SupiRanges);
    o.m_SupiRangesIsSet = true;
  }
  if (j.find("storageIdRanges") != j.end()) {
    j.at("storageIdRanges").get_to(o.m_StorageIdRanges);
    o.m_StorageIdRangesIsSet = true;
  }
}

std::string NrfInfo_servedUdsfInfo_value::getGroupId() const {
  return m_GroupId;
}
void NrfInfo_servedUdsfInfo_value::setGroupId(std::string const& value) {
  m_GroupId      = value;
  m_GroupIdIsSet = true;
}
bool NrfInfo_servedUdsfInfo_value::groupIdIsSet() const {
  return m_GroupIdIsSet;
}
void NrfInfo_servedUdsfInfo_value::unsetGroupId() {
  m_GroupIdIsSet = false;
}
std::vector<oai::_3gpp::model::SupiRange>
NrfInfo_servedUdsfInfo_value::getSupiRanges() const {
  return m_SupiRanges;
}
void NrfInfo_servedUdsfInfo_value::setSupiRanges(
    std::vector<oai::_3gpp::model::SupiRange> const& value) {
  m_SupiRanges      = value;
  m_SupiRangesIsSet = true;
}
bool NrfInfo_servedUdsfInfo_value::supiRangesIsSet() const {
  return m_SupiRangesIsSet;
}
void NrfInfo_servedUdsfInfo_value::unsetSupiRanges() {
  m_SupiRangesIsSet = false;
}
std::map<std::string, std::vector<oai::_3gpp::model::IdentityRange>>
NrfInfo_servedUdsfInfo_value::getStorageIdRanges() const {
  return m_StorageIdRanges;
}
void NrfInfo_servedUdsfInfo_value::setStorageIdRanges(
    std::map<std::string, std::vector<oai::_3gpp::model::IdentityRange>> const&
        value) {
  m_StorageIdRanges      = value;
  m_StorageIdRangesIsSet = true;
}
bool NrfInfo_servedUdsfInfo_value::storageIdRangesIsSet() const {
  return m_StorageIdRangesIsSet;
}
void NrfInfo_servedUdsfInfo_value::unsetStorageIdRanges() {
  m_StorageIdRangesIsSet = false;
}

}  // namespace oai::_3gpp::model
