/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service   © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NwdafData.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

NwdafData::NwdafData() {
  m_NwdafInstanceId  = "";
  m_NwdafEventsIsSet = false;
}

void NwdafData::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool NwdafData::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool NwdafData::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "NwdafData" : pathPrefix;

  if (nwdafEventsIsSet()) {
    const std::vector<oai::_3gpp::model::NwdafEvent>& value = m_NwdafEvents;
    const std::string currentValuePath = _pathPrefix + ".nwdafEvents";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::NwdafEvent& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".nwdafEvents") && success;

        i++;
      }
    }
  }

  return success;
}

bool NwdafData::operator==(const NwdafData& rhs) const {
  return

      (getNwdafInstanceId() == rhs.getNwdafInstanceId()) &&

      ((!nwdafEventsIsSet() && !rhs.nwdafEventsIsSet()) ||
       (nwdafEventsIsSet() && rhs.nwdafEventsIsSet() &&
        getNwdafEvents() == rhs.getNwdafEvents()))

          ;
}

bool NwdafData::operator!=(const NwdafData& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NwdafData& o) {
  j                    = nlohmann::json();
  j["nwdafInstanceId"] = o.m_NwdafInstanceId;
  if (o.nwdafEventsIsSet() || !o.m_NwdafEvents.empty())
    j["nwdafEvents"] = o.m_NwdafEvents;
}

void from_json(const nlohmann::json& j, NwdafData& o) {
  j.at("nwdafInstanceId").get_to(o.m_NwdafInstanceId);
  if (j.find("nwdafEvents") != j.end()) {
    j.at("nwdafEvents").get_to(o.m_NwdafEvents);
    o.m_NwdafEventsIsSet = true;
  }
}

std::string NwdafData::getNwdafInstanceId() const {
  return m_NwdafInstanceId;
}
void NwdafData::setNwdafInstanceId(std::string const& value) {
  m_NwdafInstanceId = value;
}
std::vector<oai::_3gpp::model::NwdafEvent> NwdafData::getNwdafEvents() const {
  return m_NwdafEvents;
}
void NwdafData::setNwdafEvents(
    std::vector<oai::_3gpp::model::NwdafEvent> const& value) {
  m_NwdafEvents      = value;
  m_NwdafEventsIsSet = true;
}
bool NwdafData::nwdafEventsIsSet() const {
  return m_NwdafEventsIsSet;
}
void NwdafData::unsetNwdafEvents() {
  m_NwdafEventsIsSet = false;
}

}  // namespace oai::_3gpp::model
