/**
 * Npcf_EventExposure
 * PCF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PcEventExposureNotif.h
 *
 * Represents notifications about Policy Control events related to an Individual
 * Policy Events Subscription resource.
 */

#ifndef PcEventExposureNotif_H_
#define PcEventExposureNotif_H_

#include <string>
#include "PcEventNotification.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Represents notifications about Policy Control events related to an
/// Individual Policy Events Subscription resource.
/// </summary>
class PcEventExposureNotif {
 public:
  PcEventExposureNotif();
  virtual ~PcEventExposureNotif() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const PcEventExposureNotif& rhs) const;
  bool operator!=(const PcEventExposureNotif& rhs) const;

  /////////////////////////////////////////////
  /// PcEventExposureNotif members

  /// <summary>
  ///
  /// </summary>
  std::string getNotifId() const;
  void setNotifId(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::PcEventNotification> getEventNotifs() const;
  void setEventNotifs(
      std::vector<oai::_3gpp::model::PcEventNotification> const& value);

  friend void to_json(nlohmann::json& j, const PcEventExposureNotif& o);
  friend void from_json(const nlohmann::json& j, PcEventExposureNotif& o);

 protected:
  std::string m_NotifId;

  std::vector<oai::_3gpp::model::PcEventNotification> m_EventNotifs;
};

}  // namespace oai::_3gpp::model

#endif /* PcEventExposureNotif_H_ */
