/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PduSessionStatusCfg.h
 *
 *
 */

#ifndef PduSessionStatusCfg_H_
#define PduSessionStatusCfg_H_

#include <string>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class PduSessionStatusCfg {
 public:
  PduSessionStatusCfg();
  virtual ~PduSessionStatusCfg() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const PduSessionStatusCfg& rhs) const;
  bool operator!=(const PduSessionStatusCfg& rhs) const;

  /////////////////////////////////////////////
  /// PduSessionStatusCfg members

  /// <summary>
  /// String representing a Data Network as defined in clause 9A of 3GPP
  /// TS 23.003;  it shall contain either a DNN Network Identifier, or a full
  /// DNN with both the Network  Identifier and Operator Identifier, as
  /// specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as
  /// string in which the labels are separated by dots  (e.g.
  /// \&quot;Label1.Label2.Label3\&quot;).
  /// </summary>
  std::string getDnn() const;
  void setDnn(std::string const& value);
  bool dnnIsSet() const;
  void unsetDnn();

  friend void to_json(nlohmann::json& j, const PduSessionStatusCfg& o);
  friend void from_json(const nlohmann::json& j, PduSessionStatusCfg& o);

 protected:
  std::string m_Dnn;
  bool m_DnnIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* PduSessionStatusCfg_H_ */
