/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Periodicity.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

Periodicity::Periodicity() {}

void Periodicity::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool Periodicity::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool Periodicity::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "Periodicity" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool Periodicity::operator==(const Periodicity& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool Periodicity::operator!=(const Periodicity& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Periodicity& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, Periodicity& o) {
  from_json(j, o.m_value);
}

Periodicity_anyOf Periodicity::getValue() const {
  return m_value;
}

void Periodicity::setValue(Periodicity_anyOf value) {
  m_value = value;
}

Periodicity_anyOf::ePeriodicity_anyOf Periodicity::getEnumValue() const {
  return m_value.getValue();
}

void Periodicity::setEnumValue(Periodicity_anyOf::ePeriodicity_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::_3gpp::model
