/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PolicyDataForIndividualUe.h
 *
 * Contains policy data for a given subscriber.
 */

#ifndef PolicyDataForIndividualUe_H_
#define PolicyDataForIndividualUe_H_

#include "UePolicySet.h"
#include "SmPolicyData.h"
#include "OperatorSpecificDataContainer.h"
#include <map>
#include "UsageMonData.h"
#include "AmPolicyData.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Contains policy data for a given subscriber.
/// </summary>
class PolicyDataForIndividualUe {
 public:
  PolicyDataForIndividualUe();
  virtual ~PolicyDataForIndividualUe() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const PolicyDataForIndividualUe& rhs) const;
  bool operator!=(const PolicyDataForIndividualUe& rhs) const;

  /////////////////////////////////////////////
  /// PolicyDataForIndividualUe members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::UePolicySet getUePolicyDataSet() const;
  void setUePolicyDataSet(oai::_3gpp::model::UePolicySet const& value);
  bool uePolicyDataSetIsSet() const;
  void unsetUePolicyDataSet();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::SmPolicyData getSmPolicyDataSet() const;
  void setSmPolicyDataSet(oai::_3gpp::model::SmPolicyData const& value);
  bool smPolicyDataSetIsSet() const;
  void unsetSmPolicyDataSet();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::AmPolicyData getAmPolicyDataSet() const;
  void setAmPolicyDataSet(oai::_3gpp::model::AmPolicyData const& value);
  bool amPolicyDataSetIsSet() const;
  void unsetAmPolicyDataSet();
  /// <summary>
  /// Contains UM policies. The value of the limit identifier is used as the key
  /// of the map.
  /// </summary>
  std::map<std::string, oai::_3gpp::model::UsageMonData> getUmData() const;
  void setUmData(
      std::map<std::string, oai::_3gpp::model::UsageMonData> const& value);
  bool umDataIsSet() const;
  void unsetUmData();
  /// <summary>
  /// Contains Operator Specific Data resource data. The key of the map is
  /// operator specific data element name and the value is the operator specific
  /// data of the UE.
  /// </summary>
  std::map<std::string, oai::_3gpp::model::OperatorSpecificDataContainer>
  getOperatorSpecificDataSet() const;
  void setOperatorSpecificDataSet(
      std::map<
          std::string, oai::_3gpp::model::OperatorSpecificDataContainer> const&
          value);
  bool operatorSpecificDataSetIsSet() const;
  void unsetOperatorSpecificDataSet();

  friend void to_json(nlohmann::json& j, const PolicyDataForIndividualUe& o);
  friend void from_json(const nlohmann::json& j, PolicyDataForIndividualUe& o);

 protected:
  oai::_3gpp::model::UePolicySet m_UePolicyDataSet;
  bool m_UePolicyDataSetIsSet;
  oai::_3gpp::model::SmPolicyData m_SmPolicyDataSet;
  bool m_SmPolicyDataSetIsSet;
  oai::_3gpp::model::AmPolicyData m_AmPolicyDataSet;
  bool m_AmPolicyDataSetIsSet;
  std::map<std::string, oai::_3gpp::model::UsageMonData> m_UmData;
  bool m_UmDataIsSet;
  std::map<std::string, oai::_3gpp::model::OperatorSpecificDataContainer>
      m_OperatorSpecificDataSet;
  bool m_OperatorSpecificDataSetIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* PolicyDataForIndividualUe_H_ */
