/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PolicyReqTrigger.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

PolicyReqTrigger::PolicyReqTrigger() {}

void PolicyReqTrigger::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool PolicyReqTrigger::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool PolicyReqTrigger::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "PolicyReqTrigger" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool PolicyReqTrigger::operator==(const PolicyReqTrigger& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool PolicyReqTrigger::operator!=(const PolicyReqTrigger& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PolicyReqTrigger& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, PolicyReqTrigger& o) {
  from_json(j, o.m_value);
}

PolicyReqTrigger_anyOf PolicyReqTrigger::getValue() const {
  return m_value;
}

void PolicyReqTrigger::setValue(PolicyReqTrigger_anyOf value) {
  m_value = value;
}

PolicyReqTrigger_anyOf::ePolicyReqTrigger_anyOf PolicyReqTrigger::getEnumValue()
    const {
  return m_value.getValue();
}

void PolicyReqTrigger::setEnumValue(
    PolicyReqTrigger_anyOf::ePolicyReqTrigger_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::_3gpp::model
