/**
 * NRF NFManagement Service
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ProSeCapability.h
 *
 * Indicate the supported ProSe Capability by the PCF.
 */

#ifndef ProSeCapability_H_
#define ProSeCapability_H_

#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Indicate the supported ProSe Capability by the PCF.
/// </summary>
class ProSeCapability {
 public:
  ProSeCapability();
  virtual ~ProSeCapability() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const ProSeCapability& rhs) const;
  bool operator!=(const ProSeCapability& rhs) const;

  /////////////////////////////////////////////
  /// ProSeCapability members

  /// <summary>
  ///
  /// </summary>
  bool isProseDirectDiscovey() const;
  void setProseDirectDiscovey(bool const value);
  bool proseDirectDiscoveyIsSet() const;
  void unsetProseDirectDiscovey();
  /// <summary>
  ///
  /// </summary>
  bool isProseDirectCommunication() const;
  void setProseDirectCommunication(bool const value);
  bool proseDirectCommunicationIsSet() const;
  void unsetProseDirectCommunication();
  /// <summary>
  ///
  /// </summary>
  bool isProseL2UetoNetworkRelay() const;
  void setProseL2UetoNetworkRelay(bool const value);
  bool proseL2UetoNetworkRelayIsSet() const;
  void unsetProseL2UetoNetworkRelay();
  /// <summary>
  ///
  /// </summary>
  bool isProseL3UetoNetworkRelay() const;
  void setProseL3UetoNetworkRelay(bool const value);
  bool proseL3UetoNetworkRelayIsSet() const;
  void unsetProseL3UetoNetworkRelay();
  /// <summary>
  ///
  /// </summary>
  bool isProseL2RemoteUe() const;
  void setProseL2RemoteUe(bool const value);
  bool proseL2RemoteUeIsSet() const;
  void unsetProseL2RemoteUe();
  /// <summary>
  ///
  /// </summary>
  bool isProseL3RemoteUe() const;
  void setProseL3RemoteUe(bool const value);
  bool proseL3RemoteUeIsSet() const;
  void unsetProseL3RemoteUe();

  friend void to_json(nlohmann::json& j, const ProSeCapability& o);
  friend void from_json(const nlohmann::json& j, ProSeCapability& o);

 protected:
  bool m_ProseDirectDiscovey;
  bool m_ProseDirectDiscoveyIsSet;
  bool m_ProseDirectCommunication;
  bool m_ProseDirectCommunicationIsSet;
  bool m_ProseL2UetoNetworkRelay;
  bool m_ProseL2UetoNetworkRelayIsSet;
  bool m_ProseL3UetoNetworkRelay;
  bool m_ProseL3UetoNetworkRelayIsSet;
  bool m_ProseL2RemoteUe;
  bool m_ProseL2RemoteUeIsSet;
  bool m_ProseL3RemoteUe;
  bool m_ProseL3RemoteUeIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* ProSeCapability_H_ */
