/**
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PsaInformation.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

PsaInformation::PsaInformation() {
  m_PsaIndIsSet       = false;
  m_DnaiListIsSet     = false;
  m_UeIpv6PrefixIsSet = false;
  m_PsaUpfId          = "";
  m_PsaUpfIdIsSet     = false;
}

void PsaInformation::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool PsaInformation::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool PsaInformation::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "PsaInformation" : pathPrefix;

  if (dnaiListIsSet()) {
    const std::vector<std::string>& value = m_DnaiList;
    const std::string currentValuePath    = _pathPrefix + ".dnaiList";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const std::string& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        i++;
      }
    }
  }

  return success;
}

bool PsaInformation::operator==(const PsaInformation& rhs) const {
  return

      ((!psaIndIsSet() && !rhs.psaIndIsSet()) ||
       (psaIndIsSet() && rhs.psaIndIsSet() &&
        getPsaInd() == rhs.getPsaInd())) &&

      ((!dnaiListIsSet() && !rhs.dnaiListIsSet()) ||
       (dnaiListIsSet() && rhs.dnaiListIsSet() &&
        getDnaiList() == rhs.getDnaiList())) &&

      ((!ueIpv6PrefixIsSet() && !rhs.ueIpv6PrefixIsSet()) ||
       (ueIpv6PrefixIsSet() && rhs.ueIpv6PrefixIsSet() &&
        getUeIpv6Prefix() == rhs.getUeIpv6Prefix())) &&

      ((!psaUpfIdIsSet() && !rhs.psaUpfIdIsSet()) ||
       (psaUpfIdIsSet() && rhs.psaUpfIdIsSet() &&
        getPsaUpfId() == rhs.getPsaUpfId()))

          ;
}

bool PsaInformation::operator!=(const PsaInformation& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PsaInformation& o) {
  j = nlohmann::json();
  if (o.psaIndIsSet()) j["psaInd"] = o.m_PsaInd;
  if (o.dnaiListIsSet() || !o.m_DnaiList.empty()) j["dnaiList"] = o.m_DnaiList;
  if (o.ueIpv6PrefixIsSet()) j["ueIpv6Prefix"] = o.m_UeIpv6Prefix;
  if (o.psaUpfIdIsSet()) j["psaUpfId"] = o.m_PsaUpfId;
}

void from_json(const nlohmann::json& j, PsaInformation& o) {
  if (j.find("psaInd") != j.end()) {
    j.at("psaInd").get_to(o.m_PsaInd);
    o.m_PsaIndIsSet = true;
  }
  if (j.find("dnaiList") != j.end()) {
    j.at("dnaiList").get_to(o.m_DnaiList);
    o.m_DnaiListIsSet = true;
  }
  if (j.find("ueIpv6Prefix") != j.end()) {
    j.at("ueIpv6Prefix").get_to(o.m_UeIpv6Prefix);
    o.m_UeIpv6PrefixIsSet = true;
  }
  if (j.find("psaUpfId") != j.end()) {
    j.at("psaUpfId").get_to(o.m_PsaUpfId);
    o.m_PsaUpfIdIsSet = true;
  }
}

oai::_3gpp::model::PsaIndication PsaInformation::getPsaInd() const {
  return m_PsaInd;
}
void PsaInformation::setPsaInd(oai::_3gpp::model::PsaIndication const& value) {
  m_PsaInd      = value;
  m_PsaIndIsSet = true;
}
bool PsaInformation::psaIndIsSet() const {
  return m_PsaIndIsSet;
}
void PsaInformation::unsetPsaInd() {
  m_PsaIndIsSet = false;
}
std::vector<std::string> PsaInformation::getDnaiList() const {
  return m_DnaiList;
}
void PsaInformation::setDnaiList(std::vector<std::string> const& value) {
  m_DnaiList      = value;
  m_DnaiListIsSet = true;
}
bool PsaInformation::dnaiListIsSet() const {
  return m_DnaiListIsSet;
}
void PsaInformation::unsetDnaiList() {
  m_DnaiListIsSet = false;
}
oai::_3gpp::model::Ipv6Prefix PsaInformation::getUeIpv6Prefix() const {
  return m_UeIpv6Prefix;
}
void PsaInformation::setUeIpv6Prefix(
    oai::_3gpp::model::Ipv6Prefix const& value) {
  m_UeIpv6Prefix      = value;
  m_UeIpv6PrefixIsSet = true;
}
bool PsaInformation::ueIpv6PrefixIsSet() const {
  return m_UeIpv6PrefixIsSet;
}
void PsaInformation::unsetUeIpv6Prefix() {
  m_UeIpv6PrefixIsSet = false;
}
std::string PsaInformation::getPsaUpfId() const {
  return m_PsaUpfId;
}
void PsaInformation::setPsaUpfId(std::string const& value) {
  m_PsaUpfId      = value;
  m_PsaUpfIdIsSet = true;
}
bool PsaInformation::psaUpfIdIsSet() const {
  return m_PsaUpfIdIsSet;
}
void PsaInformation::unsetPsaUpfId() {
  m_PsaUpfIdIsSet = false;
}

}  // namespace oai::_3gpp::model
