/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "RouteSelectionParameterSet.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

RouteSelectionParameterSet::RouteSelectionParameterSet() {
  m_Dnn                       = "";
  m_DnnIsSet                  = false;
  m_SnssaiIsSet               = false;
  m_Precedence                = 0;
  m_PrecedenceIsSet           = false;
  m_SpatialValidityAreasIsSet = false;
  m_SpatialValidityTaisIsSet  = false;
}

void RouteSelectionParameterSet::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool RouteSelectionParameterSet::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool RouteSelectionParameterSet::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "RouteSelectionParameterSet" : pathPrefix;

  if (precedenceIsSet()) {
    const int32_t& value               = m_Precedence;
    const std::string currentValuePath = _pathPrefix + ".precedence";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
  }

  if (spatialValidityAreasIsSet()) {
    const std::vector<oai::_3gpp::model::GeographicalArea>& value =
        m_SpatialValidityAreas;
    const std::string currentValuePath = _pathPrefix + ".spatialValidityAreas";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::GeographicalArea& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".spatialValidityAreas") &&
            success;

        i++;
      }
    }
  }

  if (spatialValidityTaisIsSet()) {
    const std::vector<oai::_3gpp::model::Tai>& value = m_SpatialValidityTais;
    const std::string currentValuePath = _pathPrefix + ".spatialValidityTais";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::Tai& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success =
            value.validate(msg, currentValuePath + ".spatialValidityTais") &&
            success;

        i++;
      }
    }
  }

  return success;
}

bool RouteSelectionParameterSet::operator==(
    const RouteSelectionParameterSet& rhs) const {
  return

      ((!dnnIsSet() && !rhs.dnnIsSet()) ||
       (dnnIsSet() && rhs.dnnIsSet() && getDnn() == rhs.getDnn())) &&

      ((!snssaiIsSet() && !rhs.snssaiIsSet()) ||
       (snssaiIsSet() && rhs.snssaiIsSet() &&
        getSnssai() == rhs.getSnssai())) &&

      ((!precedenceIsSet() && !rhs.precedenceIsSet()) ||
       (precedenceIsSet() && rhs.precedenceIsSet() &&
        getPrecedence() == rhs.getPrecedence())) &&

      ((!spatialValidityAreasIsSet() && !rhs.spatialValidityAreasIsSet()) ||
       (spatialValidityAreasIsSet() && rhs.spatialValidityAreasIsSet() &&
        getSpatialValidityAreas() == rhs.getSpatialValidityAreas())) &&

      ((!spatialValidityTaisIsSet() && !rhs.spatialValidityTaisIsSet()) ||
       (spatialValidityTaisIsSet() && rhs.spatialValidityTaisIsSet() &&
        getSpatialValidityTais() == rhs.getSpatialValidityTais()))

          ;
}

bool RouteSelectionParameterSet::operator!=(
    const RouteSelectionParameterSet& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const RouteSelectionParameterSet& o) {
  j = nlohmann::json();
  if (o.dnnIsSet()) j["dnn"] = o.m_Dnn;
  if (o.snssaiIsSet()) j["snssai"] = o.m_Snssai;
  if (o.precedenceIsSet()) j["precedence"] = o.m_Precedence;
  if (o.spatialValidityAreasIsSet() || !o.m_SpatialValidityAreas.empty())
    j["spatialValidityAreas"] = o.m_SpatialValidityAreas;
  if (o.spatialValidityTaisIsSet() || !o.m_SpatialValidityTais.empty())
    j["spatialValidityTais"] = o.m_SpatialValidityTais;
}

void from_json(const nlohmann::json& j, RouteSelectionParameterSet& o) {
  if (j.find("dnn") != j.end()) {
    j.at("dnn").get_to(o.m_Dnn);
    o.m_DnnIsSet = true;
  }
  if (j.find("snssai") != j.end()) {
    j.at("snssai").get_to(o.m_Snssai);
    o.m_SnssaiIsSet = true;
  }
  if (j.find("precedence") != j.end()) {
    j.at("precedence").get_to(o.m_Precedence);
    o.m_PrecedenceIsSet = true;
  }
  if (j.find("spatialValidityAreas") != j.end()) {
    j.at("spatialValidityAreas").get_to(o.m_SpatialValidityAreas);
    o.m_SpatialValidityAreasIsSet = true;
  }
  if (j.find("spatialValidityTais") != j.end()) {
    j.at("spatialValidityTais").get_to(o.m_SpatialValidityTais);
    o.m_SpatialValidityTaisIsSet = true;
  }
}

std::string RouteSelectionParameterSet::getDnn() const {
  return m_Dnn;
}
void RouteSelectionParameterSet::setDnn(std::string const& value) {
  m_Dnn      = value;
  m_DnnIsSet = true;
}
bool RouteSelectionParameterSet::dnnIsSet() const {
  return m_DnnIsSet;
}
void RouteSelectionParameterSet::unsetDnn() {
  m_DnnIsSet = false;
}
oai::_3gpp::model::Snssai RouteSelectionParameterSet::getSnssai() const {
  return m_Snssai;
}
void RouteSelectionParameterSet::setSnssai(
    oai::_3gpp::model::Snssai const& value) {
  m_Snssai      = value;
  m_SnssaiIsSet = true;
}
bool RouteSelectionParameterSet::snssaiIsSet() const {
  return m_SnssaiIsSet;
}
void RouteSelectionParameterSet::unsetSnssai() {
  m_SnssaiIsSet = false;
}
int32_t RouteSelectionParameterSet::getPrecedence() const {
  return m_Precedence;
}
void RouteSelectionParameterSet::setPrecedence(int32_t const value) {
  m_Precedence      = value;
  m_PrecedenceIsSet = true;
}
bool RouteSelectionParameterSet::precedenceIsSet() const {
  return m_PrecedenceIsSet;
}
void RouteSelectionParameterSet::unsetPrecedence() {
  m_PrecedenceIsSet = false;
}
std::vector<oai::_3gpp::model::GeographicalArea>
RouteSelectionParameterSet::getSpatialValidityAreas() const {
  return m_SpatialValidityAreas;
}
void RouteSelectionParameterSet::setSpatialValidityAreas(
    std::vector<oai::_3gpp::model::GeographicalArea> const& value) {
  m_SpatialValidityAreas      = value;
  m_SpatialValidityAreasIsSet = true;
}
bool RouteSelectionParameterSet::spatialValidityAreasIsSet() const {
  return m_SpatialValidityAreasIsSet;
}
void RouteSelectionParameterSet::unsetSpatialValidityAreas() {
  m_SpatialValidityAreasIsSet = false;
}
std::vector<oai::_3gpp::model::Tai>
RouteSelectionParameterSet::getSpatialValidityTais() const {
  return m_SpatialValidityTais;
}
void RouteSelectionParameterSet::setSpatialValidityTais(
    std::vector<oai::_3gpp::model::Tai> const& value) {
  m_SpatialValidityTais      = value;
  m_SpatialValidityTaisIsSet = true;
}
bool RouteSelectionParameterSet::spatialValidityTaisIsSet() const {
  return m_SpatialValidityTaisIsSet;
}
void RouteSelectionParameterSet::unsetSpatialValidityTais() {
  m_SpatialValidityTaisIsSet = false;
}

}  // namespace oai::_3gpp::model
