/**
 * Namf_Communication
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SmallDataRateStatusInfo.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

SmallDataRateStatusInfo::SmallDataRateStatusInfo() {
  m_Dnn = "";
}

void SmallDataRateStatusInfo::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool SmallDataRateStatusInfo::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SmallDataRateStatusInfo::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SmallDataRateStatusInfo" : pathPrefix;

  return success;
}

bool SmallDataRateStatusInfo::operator==(
    const SmallDataRateStatusInfo& rhs) const {
  return

      (getSnssai() == rhs.getSnssai()) &&

      (getDnn() == rhs.getDnn()) &&

      (getSmallDataRateStatus() == rhs.getSmallDataRateStatus())

          ;
}

bool SmallDataRateStatusInfo::operator!=(
    const SmallDataRateStatusInfo& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SmallDataRateStatusInfo& o) {
  j                        = nlohmann::json();
  j["Snssai"]              = o.m_Snssai;
  j["Dnn"]                 = o.m_Dnn;
  j["SmallDataRateStatus"] = o.m_SmallDataRateStatus;
}

void from_json(const nlohmann::json& j, SmallDataRateStatusInfo& o) {
  j.at("Snssai").get_to(o.m_Snssai);
  j.at("Dnn").get_to(o.m_Dnn);
  j.at("SmallDataRateStatus").get_to(o.m_SmallDataRateStatus);
}

oai::_3gpp::model::Snssai SmallDataRateStatusInfo::getSnssai() const {
  return m_Snssai;
}
void SmallDataRateStatusInfo::setSnssai(
    oai::_3gpp::model::Snssai const& value) {
  m_Snssai = value;
}
std::string SmallDataRateStatusInfo::getDnn() const {
  return m_Dnn;
}
void SmallDataRateStatusInfo::setDnn(std::string const& value) {
  m_Dnn = value;
}
oai::_3gpp::model::SmallDataRateStatus
SmallDataRateStatusInfo::getSmallDataRateStatus() const {
  return m_SmallDataRateStatus;
}
void SmallDataRateStatusInfo::setSmallDataRateStatus(
    oai::_3gpp::model::SmallDataRateStatus const& value) {
  m_SmallDataRateStatus = value;
}

}  // namespace oai::_3gpp::model
