/**
 * Nnef_SMContext
 * Nnef SMContext Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SmContextReleasedData.h
 *
 * Successful release of an Individual SM context with information sent to the
 * NF service consumer.
 */

#ifndef SmContextReleasedData_H_
#define SmContextReleasedData_H_

#include "SmallDataRateStatus.h"
#include "ApnRateStatus.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Successful release of an Individual SM context with information sent to the
/// NF service consumer.
/// </summary>
class SmContextReleasedData {
 public:
  SmContextReleasedData();
  virtual ~SmContextReleasedData() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SmContextReleasedData& rhs) const;
  bool operator!=(const SmContextReleasedData& rhs) const;

  /////////////////////////////////////////////
  /// SmContextReleasedData members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::SmallDataRateStatus getSmallDataRateStatus() const;
  void setSmallDataRateStatus(
      oai::_3gpp::model::SmallDataRateStatus const& value);
  bool smallDataRateStatusIsSet() const;
  void unsetSmallDataRateStatus();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::ApnRateStatus getApnRateStatus() const;
  void setApnRateStatus(oai::_3gpp::model::ApnRateStatus const& value);
  bool apnRateStatusIsSet() const;
  void unsetApnRateStatus();

  friend void to_json(nlohmann::json& j, const SmContextReleasedData& o);
  friend void from_json(const nlohmann::json& j, SmContextReleasedData& o);

 protected:
  oai::_3gpp::model::SmallDataRateStatus m_SmallDataRateStatus;
  bool m_SmallDataRateStatusIsSet;
  oai::_3gpp::model::ApnRateStatus m_ApnRateStatus;
  bool m_ApnRateStatusIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* SmContextReleasedData_H_ */
