/**
 * Nsmf_EventExposure
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SmNasFromSmf.h
 *
 * Represents information on the SM congestion control applied SM NAS messages
 * that SMF sends  to UE for PDU Session.
 */

#ifndef SmNasFromSmf_H_
#define SmNasFromSmf_H_

#include "AppliedSmccType.h"
#include <string>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Represents information on the SM congestion control applied SM NAS messages
/// that SMF sends  to UE for PDU Session.
/// </summary>
class SmNasFromSmf {
 public:
  SmNasFromSmf();
  virtual ~SmNasFromSmf() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SmNasFromSmf& rhs) const;
  bool operator!=(const SmNasFromSmf& rhs) const;

  /////////////////////////////////////////////
  /// SmNasFromSmf members

  /// <summary>
  ///
  /// </summary>
  std::string getSmNasType() const;
  void setSmNasType(std::string const& value);
  /// <summary>
  /// string with format &#39;date-time&#39; as defined in OpenAPI.
  /// </summary>
  std::string getTimeStamp() const;
  void setTimeStamp(std::string const& value);
  /// <summary>
  /// indicating a time in seconds.
  /// </summary>
  int32_t getBackoffTimer() const;
  void setBackoffTimer(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::AppliedSmccType getAppliedSmccType() const;
  void setAppliedSmccType(oai::_3gpp::model::AppliedSmccType const& value);

  friend void to_json(nlohmann::json& j, const SmNasFromSmf& o);
  friend void from_json(const nlohmann::json& j, SmNasFromSmf& o);

 protected:
  std::string m_SmNasType;

  std::string m_TimeStamp;

  int32_t m_BackoffTimer;

  oai::_3gpp::model::AppliedSmccType m_AppliedSmccType;
};

}  // namespace oai::_3gpp::model

#endif /* SmNasFromSmf_H_ */
