/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SmsfInfo.h
 *
 *
 */

#ifndef SmsfInfo_H_
#define SmsfInfo_H_

#include <string>
#include "PlmnId.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class SmsfInfo {
 public:
  SmsfInfo();
  virtual ~SmsfInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SmsfInfo& rhs) const;
  bool operator!=(const SmsfInfo& rhs) const;

  /////////////////////////////////////////////
  /// SmsfInfo members

  /// <summary>
  /// String uniquely identifying a NF instance. The format of the NF Instance
  /// ID shall be a  Universally Unique Identifier (UUID) version 4, as
  /// described in IETF RFC 4122.
  /// </summary>
  std::string getSmsfInstanceId() const;
  void setSmsfInstanceId(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::PlmnId getPlmnId() const;
  void setPlmnId(oai::_3gpp::model::PlmnId const& value);
  /// <summary>
  /// NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted as the
  /// following string \&quot;set&lt;Set
  /// ID&gt;.&lt;nftype&gt;set.5gc.mnc&lt;MNC&gt;.mcc&lt;MCC&gt;\&quot;, or
  /// \&quot;set&lt;SetID&gt;.&lt;NFType&gt;set.5gc.nid&lt;NID&gt;.mnc&lt;MNC&gt;.mcc&lt;MCC&gt;\&quot;
  /// with  &lt;MCC&gt; encoded as defined in clause 5.4.2 (\&quot;Mcc\&quot;
  /// data type definition)  &lt;MNC&gt; encoding the Mobile Network Code part
  /// of the PLMN, comprising 3 digits.    If there are only 2 significant
  /// digits in the MNC, one \&quot;0\&quot; digit shall be inserted    at the
  /// left side to fill the 3 digits coding of MNC.  Pattern:
  /// &#39;^[0-9]{3}$&#39; &lt;NFType&gt; encoded as a value defined in
  /// Table 6.1.6.3.3-1 of 3GPP TS 29.510 but    with lower case characters
  /// &lt;Set ID&gt; encoded as a string of characters consisting of alphabetic
  /// characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that
  /// shall end with either an alphabetic character or a digit.
  /// </summary>
  std::string getSmsfSetId() const;
  void setSmsfSetId(std::string const& value);
  bool smsfSetIdIsSet() const;
  void unsetSmsfSetId();

  friend void to_json(nlohmann::json& j, const SmsfInfo& o);
  friend void from_json(const nlohmann::json& j, SmsfInfo& o);

 protected:
  std::string m_SmsfInstanceId;

  oai::_3gpp::model::PlmnId m_PlmnId;

  std::string m_SmsfSetId;
  bool m_SmsfSetIdIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* SmsfInfo_H_ */
