/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SqnScheme_anyOf.h
 *
 *
 */

#ifndef SqnScheme_anyOf_H_
#define SqnScheme_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class SqnScheme_anyOf {
 public:
  SqnScheme_anyOf();
  virtual ~SqnScheme_anyOf() = default;

  enum class eSqnScheme_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    GENERAL,
    NON_TIME_BASED,
    TIME_BASED
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SqnScheme_anyOf& rhs) const;
  bool operator!=(const SqnScheme_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// SqnScheme_anyOf members

  SqnScheme_anyOf::eSqnScheme_anyOf getValue() const;
  void setValue(SqnScheme_anyOf::eSqnScheme_anyOf value);

  friend void to_json(nlohmann::json& j, const SqnScheme_anyOf& o);
  friend void from_json(const nlohmann::json& j, SqnScheme_anyOf& o);

 protected:
  SqnScheme_anyOf::eSqnScheme_anyOf m_value =
      SqnScheme_anyOf::eSqnScheme_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::_3gpp::model

#endif /* SqnScheme_anyOf_H_ */
