/**
 * Nnef_EventExposure
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TargetUeIdentification.h
 *
 * Identifies the UE to which the request applies.
 */

#ifndef TargetUeIdentification_H_
#define TargetUeIdentification_H_

#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Identifies the UE to which the request applies.
/// </summary>
class TargetUeIdentification {
 public:
  TargetUeIdentification();
  virtual ~TargetUeIdentification() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const TargetUeIdentification& rhs) const;
  bool operator!=(const TargetUeIdentification& rhs) const;

  /////////////////////////////////////////////
  /// TargetUeIdentification members

  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getSupis() const;
  void setSupis(std::vector<std::string> const& value);
  bool supisIsSet() const;
  void unsetSupis();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getInterGroupIds() const;
  void setInterGroupIds(std::vector<std::string> const& value);
  bool interGroupIdsIsSet() const;
  void unsetInterGroupIds();
  /// <summary>
  ///
  /// </summary>
  bool isAnyUeId() const;
  void setAnyUeId(bool const value);
  bool anyUeIdIsSet() const;
  void unsetAnyUeId();

  friend void to_json(nlohmann::json& j, const TargetUeIdentification& o);
  friend void from_json(const nlohmann::json& j, TargetUeIdentification& o);

 protected:
  std::vector<std::string> m_Supis;
  bool m_SupisIsSet;
  std::vector<std::string> m_InterGroupIds;
  bool m_InterGroupIdsIsSet;
  bool m_AnyUeId;
  bool m_AnyUeIdIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* TargetUeIdentification_H_ */
