/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UeContextInSmfData.h
 *
 *
 */

#ifndef UeContextInSmfData_H_
#define UeContextInSmfData_H_

#include "PgwInfo.h"
#include "EmergencyInfo.h"
#include <map>
#include <vector>
#include "PduSession.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class UeContextInSmfData {
 public:
  UeContextInSmfData();
  virtual ~UeContextInSmfData() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const UeContextInSmfData& rhs) const;
  bool operator!=(const UeContextInSmfData& rhs) const;

  /////////////////////////////////////////////
  /// UeContextInSmfData members

  /// <summary>
  /// A map (list of key-value pairs where PduSessionId serves as key) of
  /// PduSessions
  /// </summary>
  std::map<std::string, oai::_3gpp::model::PduSession> getPduSessions() const;
  void setPduSessions(
      std::map<std::string, oai::_3gpp::model::PduSession> const& value);
  bool pduSessionsIsSet() const;
  void unsetPduSessions();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::_3gpp::model::PgwInfo> getPgwInfo() const;
  void setPgwInfo(std::vector<oai::_3gpp::model::PgwInfo> const& value);
  bool pgwInfoIsSet() const;
  void unsetPgwInfo();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::EmergencyInfo getEmergencyInfo() const;
  void setEmergencyInfo(oai::_3gpp::model::EmergencyInfo const& value);
  bool emergencyInfoIsSet() const;
  void unsetEmergencyInfo();

  friend void to_json(nlohmann::json& j, const UeContextInSmfData& o);
  friend void from_json(const nlohmann::json& j, UeContextInSmfData& o);

 protected:
  std::map<std::string, oai::_3gpp::model::PduSession> m_PduSessions;
  bool m_PduSessionsIsSet;
  std::vector<oai::_3gpp::model::PgwInfo> m_PgwInfo;
  bool m_PgwInfoIsSet;
  oai::_3gpp::model::EmergencyInfo m_EmergencyInfo;
  bool m_EmergencyInfoIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* UeContextInSmfData_H_ */
