/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * UePolicySetPatch.h
 *
 * Contains the UE policy set for a given subscriber.
 */

#ifndef UePolicySetPatch_H_
#define UePolicySetPatch_H_

#include <string>
#include <map>
#include "UePolicySection.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Contains the UE policy set for a given subscriber.
/// </summary>
class UePolicySetPatch {
 public:
  UePolicySetPatch();
  virtual ~UePolicySetPatch() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const UePolicySetPatch& rhs) const;
  bool operator!=(const UePolicySetPatch& rhs) const;

  /////////////////////////////////////////////
  /// UePolicySetPatch members

  /// <summary>
  /// Contains the UE Policy Sections. The UE Policy Section Identifier is used
  /// as the key of the map.
  /// </summary>
  std::map<std::string, oai::_3gpp::model::UePolicySection>
  getUePolicySections() const;
  void setUePolicySections(
      std::map<std::string, oai::_3gpp::model::UePolicySection> const& value);
  bool uePolicySectionsIsSet() const;
  void unsetUePolicySections();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getUpsis() const;
  void setUpsis(std::vector<std::string> const& value);
  bool upsisIsSet() const;
  void unsetUpsis();
  /// <summary>
  ///
  /// </summary>
  bool isAndspInd() const;
  void setAndspInd(bool const value);
  bool andspIndIsSet() const;
  void unsetAndspInd();
  /// <summary>
  /// String representing a Permanent Equipment Identifier that may contain - an
  /// IMEI or IMEISV, as  specified in clause 6.2 of 3GPP TS 23.003; a MAC
  /// address for a 5G-RG or FN-RG via  wireline  access, with an indication
  /// that this address cannot be trusted for regulatory purpose if this address
  /// cannot be used as an Equipment Identifier of the FN-RG, as specified in
  /// clause 4.7.7  of 3GPP TS23.316. Examples are imei-012345678901234 or
  /// imeisv-0123456789012345.
  /// </summary>
  std::string getPei() const;
  void setPei(std::string const& value);
  bool peiIsSet() const;
  void unsetPei();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getOsIds() const;
  void setOsIds(std::vector<std::string> const& value);
  bool osIdsIsSet() const;
  void unsetOsIds();

  friend void to_json(nlohmann::json& j, const UePolicySetPatch& o);
  friend void from_json(const nlohmann::json& j, UePolicySetPatch& o);

 protected:
  std::map<std::string, oai::_3gpp::model::UePolicySection> m_UePolicySections;
  bool m_UePolicySectionsIsSet;
  std::vector<std::string> m_Upsis;
  bool m_UpsisIsSet;
  bool m_AndspInd;
  bool m_AndspIndIsSet;
  std::string m_Pei;
  bool m_PeiIsSet;
  std::vector<std::string> m_OsIds;
  bool m_OsIdsIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* UePolicySetPatch_H_ */
