/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UserConsent.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

UserConsent::UserConsent() {}

void UserConsent::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool UserConsent::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool UserConsent::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "UserConsent" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool UserConsent::operator==(const UserConsent& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool UserConsent::operator!=(const UserConsent& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UserConsent& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, UserConsent& o) {
  from_json(j, o.m_value);
}

MdtUserConsent_anyOf UserConsent::getValue() const {
  return m_value;
}

void UserConsent::setValue(MdtUserConsent_anyOf value) {
  m_value = value;
}

MdtUserConsent_anyOf::eMdtUserConsent_anyOf UserConsent::getEnumValue() const {
  return m_value.getValue();
}

void UserConsent::setEnumValue(
    MdtUserConsent_anyOf::eMdtUserConsent_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::_3gpp::model
