/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */

#ifndef FILE_AUSF_BCF_SEEN
#define FILE_AUSF_BCF_SEEN

#include <string>

#include <nlohmann/json.hpp>

#include "ausf_config.hpp"
#include "ausf_event.hpp"
#include "logger.hpp"

namespace oai {
namespace ausf {
namespace app {

class ausf_bcf {
 public:
  std::string ausf_instance_id;  // AUSF instance id (shared with NRF registration)

  ausf_bcf(ausf_event& ev, const std::string& instance_id);
  ausf_bcf(ausf_bcf const&) = delete;
  virtual ~ausf_bcf();

  void operator=(ausf_bcf const&) = delete;

  /*
   * Read extended NF Profile from file (generated by DID Proxy)
   * @param [nlohmann::json&] profile: Output extended profile JSON
   * @return true if successful, false otherwise
   */
  bool read_extended_profile_from_file(nlohmann::json& profile);

  /*
   * Read nfInstanceId from extended NF Profile file
   * @param [std::string&] nf_instance_id: Output nfInstanceId
   * @return true if successful, false otherwise
   */
  static bool read_nf_instance_id_from_file(std::string& nf_instance_id);

  /*
   * Trigger NF instance registration to BCF
   * @param [void]
   * @return true if registration succeeded
   */
  bool register_to_bcf();

  /*
   * Trigger NF instance update to BCF
   * @param [void]
   * @return void
   */
  void update_bcf_registration();

  /*
   * Trigger NF instance deregistration from BCF
   * @param [void]
   * @return void
   */
  void deregister_from_bcf();

 private:
  ausf_event& m_event_sub;
};

}  // namespace app
}  // namespace ausf
}  // namespace oai

#endif /* FILE_AUSF_BCF_SEEN */
